/**
 * Iori Yagami frame data — extracted from frameDataChars.ts
 * Dream Cancel Wiki KOF2002UM 精确数据
 */
export const IORI_FRAME_DATA = {
  // ── 八神庵必杀技 (Iori Yagami) ── Dream Cancel Wiki KOF2002UM 精确数据
  // 葵花 qcb+A (rekka A版 1段)
  IORI_AOIHANA: {
    startup: 5,
    active: 4,
    recovery: 18,
    damage: 60,
    hitstun: 22,
    blockstun: 18,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // 葵花 A版 2段
  IORI_AOIHANA_2: {
    startup: 7,
    active: 4,
    recovery: 18,
    damage: 50,
    hitstun: 22,
    blockstun: 18,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 葵花 A版 3段 (overhead HKD)
  IORI_AOIHANA_3: {
    startup: 5,
    active: 5,
    recovery: 18,
    damage: 60,
    hitstun: 22,
    blockstun: 18,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 葵花 C版 1段
  IORI_AOIHANA_C: {
    startup: 4,
    active: 6,
    recovery: 22,
    damage: 90,
    hitstun: 26,
    blockstun: 20,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // 葵花 C版 2段
  IORI_AOIHANA_C_2: {
    startup: 4,
    active: 6,
    recovery: 22,
    damage: 80,
    hitstun: 26,
    blockstun: 20,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 葵花 C版 3段 (overhead, HKD)
  IORI_AOIHANA_C_3: {
    startup: 4,
    active: 6,
    recovery: 22,
    damage: 90,
    hitstun: 26,
    blockstun: 20,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 闇払い qcf+A (飞行道具 弱版)
  IORI_YAMIBARAI: {
    startup: 14,
    active: 3,
    recovery: 18,
    damage: 55,
    hitstun: 25,
    blockstun: 23,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 6,
  },
  // 闇払い qcf+C (飞行道具 强版)
  IORI_YAMIBARAI_C: {
    startup: 17,
    active: 5,
    recovery: 22,
    damage: 70,
    hitstun: 28,
    blockstun: 25,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 7,
  },
  // 鬼焼き dp+A (弱版 升龙)
  IORI_ONIYAKI: {
    startup: 5,
    active: 5,
    recovery: 18,
    damage: 60,
    hitstun: 22,
    blockstun: 18,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 6,
  },
  // 鬼焼き dp+C (强版 升龙, 全身无敌)
  IORI_ONIYAKI_C: {
    startup: 4,
    active: 10,
    recovery: 22,
    damage: 90,
    hitstun: 26,
    blockstun: 20,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 9,
  },
  // 琴月陰 hcb+B (弱版 冲刺HKD)
  IORI_KOTOTSUKI: {
    startup: 10,
    active: 4,
    recovery: 15,
    damage: 60,
    hitstun: 20,
    blockstun: 18,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 琴月陰 hcb+D (强版 全屏冲刺HKD)
  IORI_KOTOTSUKI_D: {
    startup: 11,
    active: 6,
    recovery: 20,
    damage: 80,
    hitstun: 24,
    blockstun: 20,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 逆剥ぎ hcb,f+P (指令投, 换边)
  IORI_KUZUKAZE: {
    startup: 8,
    active: 3,
    recovery: 20,
    damage: 70,
    hitstun: 22,
    blockstun: 20,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // ── 八神庵DM/SDM ── Dream Cancel Wiki KOF2002UM 精确数据
  DM_MAIDEN_MASHER_A: {
    startup: 7,
    active: 2,
    recovery: 25,
    damage: 200,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  DM_MAIDEN_MASHER_C: {
    startup: 7,
    active: 2,
    recovery: 25,
    damage: 200,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  SDM_MAIDEN_MASHER: {
    startup: 7,
    active: 4,
    recovery: 27,
    damage: 350,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 30,
  },
  // 八壺·DM — Iori经典DM (Yaotome)
  DM_YATAGARASU: {
    startup: 5,
    active: 20,
    recovery: 30,
    damage: 230,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 22,
  },
  // 八壺·SDM
  SDM_YATAGARASU: {
    startup: 4,
    active: 28,
    recovery: 32,
    damage: 320,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 32,
  },
  // 八壺·HSDM — Iori隐藏超必杀
  HSDM_YAOTOME: {
    startup: 3,
    active: 22,
    recovery: 35,
    damage: 380,
    hitstun: 30,
    blockstun: 21,
    pushback: 14,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 40,
  },
} as const;
