/**
 * Yashiro frame data — KOF2002 heavy hitter / puncher
 * Dream Cancel Wiki KOF2002UM 校准数据
 */
export const YASHIRO_FRAME_DATA = {
  // ── Yashiro命令通常技 (Command Normals) ──
  // Shuu Wani ->+A (upper strike)
  YASHIRO_SHUU_WANI: {
    startup: 12,
    active: 4,
    recovery: 18,
    damage: 40,
    hitstun: 16,
    blockstun: 14,
    pushback: 3,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // Juu Zutsu ->+B (overhead)
  YASHIRO_JUU_ZUTSU: {
    startup: 18,
    active: 3,
    recovery: 22,
    damage: 36,
    hitstun: 18,
    blockstun: 16,
    pushback: 2,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // ── Yashiro必杀技 (Specials) ── KOF2002UM 校准数据
  // Upper Duke qcf+A (hook punch, fast)
  YASHIRO_UPPER_DU: {
    startup: 8,
    active: 4,
    recovery: 22,
    damage: 72,
    hitstun: 20,
    blockstun: 16,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  // Upper Duke qcf+C (hook punch, multi-hit)
  YASHIRO_UPPER_DU_C: {
    startup: 12,
    active: 8,
    recovery: 26,
    damage: 95,
    hitstun: 24,
    blockstun: 20,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 12,
  },
  // Regret Bash qcb+A (palm strike)
  YASHIRO_NIRAAI: {
    startup: 10,
    active: 4,
    recovery: 24,
    damage: 68,
    hitstun: 18,
    blockstun: 16,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  // Regret Bash qcb+C (strong palm strike)
  YASHIRO_NIRAAI_C: {
    startup: 13,
    active: 6,
    recovery: 28,
    damage: 88,
    hitstun: 22,
    blockstun: 18,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 12,
  },
  // Jet Counter qcf+B (dash attack)
  YASHIRO_MUSATSU: {
    startup: 8,
    active: 6,
    recovery: 26,
    damage: 75,
    hitstun: 20,
    blockstun: 16,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 10,
  },
  // Jet Counter qcf+D (strong dash attack, KD)
  YASHIRO_MUSATSU_D: {
    startup: 10,
    active: 8,
    recovery: 30,
    damage: 90,
    hitstun: 24,
    blockstun: 20,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 12,
  },
  // Sledgehammer dp+A (anti-air)
  YASHIRO_SLEDGEHAMMER: {
    startup: 5,
    active: 4,
    recovery: 26,
    damage: 70,
    hitstun: 20,
    blockstun: 16,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  // Sledgehammer dp+C (strong anti-air)
  YASHIRO_SLEDGEHAMMER_C: {
    startup: 7,
    active: 6,
    recovery: 30,
    damage: 92,
    hitstun: 24,
    blockstun: 20,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 14,
    invincibleStartup: 4,
  },
  // Missed hcf+K (fake)
  YASHIRO_MISSED: {
    startup: 6,
    active: 0,
    recovery: 20,
    damage: 0,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // ── Yashiro DM/SDM ── KOF2002UM 校准数据
  // Million Bash Stream qcb,qcb+A/C
  DM_MILLION_BASH_STREAM: {
    startup: 6,
    active: 20,
    recovery: 36,
    damage: 210,
    hitstun: 0,
    blockstun: 22,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 22,
    invincibleStartup: 4,
  },
  // Million Bash Stream SDM MAX qcb,qcb+AC
  SDM_MILLION_BASH_STREAM: {
    startup: 4,
    active: 26,
    recovery: 38,
    damage: 320,
    hitstun: 0,
    blockstun: 22,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 32,
    invincibleStartup: 6,
  },
  // Ore Maji Mamire hcb,hcb+P (near, command throw DM)
  DM_ORE_MAJI_MAMIRE: {
    startup: 5,
    active: 4,
    recovery: 38,
    damage: 200,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
    invincibleStartup: 3,
  },
  // Ore Maji Mamire SDM MAX hcb,hcb+AC (near, command throw SDM)
  SDM_ORE_MAJI_MAMIRE: {
    startup: 4,
    active: 6,
    recovery: 36,
    damage: 270,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
    invincibleStartup: 5,
  },
} as const;
