/**
 * Attack Frame Split Files Structural Tests
 *
 * Validates all AttackFrame[] exports from the 7 split files covering
 * Andy/Billy/Chang/Choi/Yashiro/Mature/Vice, Athena/Mai/Clark/Ralf/Joe,
 * Chris/Shermie/Xiangfei/Yamazaki/Kasumi/Mary, DM/SDM supers,
 * Iori specials, Kyo specials, and Terry/Kim/Ryo/Leona.
 */
import { describe, it, expect } from 'vitest';
import type { AttackFrame } from '../src/core/types.js';

// All 7 split files
import {
  ANDY_HISHOU_KEN_FRAMES, ANDY_HISHOU_KEN_C_FRAMES,
  ANDY_SHOURYUU_DAN_FRAMES, ANDY_SHOURYUU_DAN_C_FRAMES,
  ANDY_ZANEI_RYUSEI_KEN_FRAMES, ANDY_ZANEI_RYUSEI_KEN_D_FRAMES,
  ANDY_GEKI_HISHOU_KEN_FRAMES, DM_CHO_REPPA_DAN_FRAMES, SDM_CHO_REPPA_DAN_FRAMES,
  BILLY_SANSETSU_KON_FRAMES, BILLY_SANSETSU_KON_C_FRAMES,
  BILLY_SENPU_KON_FRAMES, BILLY_SENPU_KON_C_FRAMES,
  BILLY_HIEN_ZAN_FRAMES, BILLY_HIEN_ZAN_D_FRAMES,
  DM_KAEN_SENPU_JIN_FRAMES, SDM_KAEN_SENPU_JIN_FRAMES,
  CHANG_TEKKYUU_KAITEN_FRAMES, CHANG_TEKKYUU_KAITEN_C_FRAMES,
  CHANG_TEKKYUU_FASSHU_FRAMES, CHANG_TEKKYUU_HIEN_ZAN_FRAMES,
  DM_TEKKYUU_DAI_BOUSOU_FRAMES, SDM_TEKKYUU_DAI_BOUSOU_FRAMES,
  CHOI_SOUTEN_MEKKYAKU_FRAMES, CHOI_SAN_REN_GEKI_FRAMES,
  CHOI_HISHOU_KYAKU_FRAMES, CHOI_HISHOU_KYAKU_C_FRAMES,
  CHOI_KAITEN_HIEN_ZAN_FRAMES, CHOI_KAITEN_HIEN_ZAN_C_FRAMES,
  CHOI_HOUYOKU_TENSHIN_FRAMES, DM_SHIN_CHOU_HOUYOKU_FRAMES, SDM_SHIN_CHOU_HOUYOKU_FRAMES,
  YASHIRO_UPPER_DU_FRAMES, YASHIRO_UPPER_DU_C_FRAMES,
  YASHIRO_NIRAAI_FRAMES, YASHIRO_MUSATSU_FRAMES,
  DM_ARMAGEDDON_BUSTERS_FRAMES, SDM_ARMAGEDDON_BUSTERS_FRAMES,
  MATURE_MASSACRE_FRAMES, MATURE_MASSACRE_C_FRAMES,
  MATURE_HEAVENS_GATE_FRAMES, MATURE_ECSTASY_FRAMES,
  DM_NOCTURNAL_LIGHT_FRAMES, SDM_NOCTURNAL_LIGHT_FRAMES,
  VICE_OUTRAGE_FRAMES, VICE_OUTRAGE_C_FRAMES,
  VICE_BLACK_END_FRAMES, VICE_MAYHEM_FRAMES,
  DM_NEGATIVE_GAIN_FRAMES, SDM_NEGATIVE_GAIN_FRAMES,
} from '../src/core/attackFrames_split/andyBillyChangChoiYashiro.js';
import {
  ATHENA_PSYCHO_BALL_FRAMES, ATHENA_PSYCHO_BALL_C_FRAMES,
  ATHENA_PSYCHO_SWORD_FRAMES, ATHENA_PSYCHO_SWORD_C_FRAMES,
  ATHENA_PHOENIX_ARROW_FRAMES, DM_SHINING_CRYSTAL_BIT_FRAMES,
  MAI_KA_CHO_SEN_FRAMES, MAI_KA_CHO_SEN_C_FRAMES,
  MAI_HISHO_RYU_EN_JIN_FRAMES, MAI_RYU_EN_BU_FRAMES,
  DM_HAKA_OTOSHI_FRAMES,
  CLARK_ARGENTINE_FRAMES, CLARK_ARGENTINE_C_FRAMES,
  CLARK_FLASH_ELBOW_FRAMES, CLARK_VULCAN_FRAMES,
  DM_ARGENTINE_DM_FRAMES, SDM_ARGENTINE_DM_FRAMES,
  RALF_VULCAN_FRAMES, RALF_VULCAN_C_FRAMES,
  RALF_BACKBREAKER_FRAMES, RALF_KICK_FRAMES,
  DM_GALACTICA_PHANTOM_FRAMES,
  JOE_HURRICANE_FRAMES, JOE_HURRICANE_C_FRAMES,
  JOE_TIGER_KICK_FRAMES, JOE_TIGER_KICK_D_FRAMES,
  JOE_BAKURETSUKEN_FRAMES, JOE_OUGON_KAKATO_FRAMES,
  DM_SCREW_UPPER_FRAMES,
} from '../src/core/attackFrames_split/athenaMaiClarkRalfJoe.js';
import {
  CHRIS_SHOT_WEAVE_FRAMES, CHRIS_SHOT_WEAVE_C_FRAMES,
  CHRIS_TWISTER_DRIVE_FRAMES, CHRIS_SCRAMBLE_DASH_FRAMES,
  DM_CHAIN_SLIDE_TOUCH_FRAMES, SDM_CHAIN_SLIDE_TOUCH_FRAMES,
  SHERMIE_SHOOT_FRAMES, SHERMIE_SHOOT_C_FRAMES,
  SHERMIE_CARNIVAL_FRAMES, SHERMIE_AXLE_SPIN_FRAMES,
  DM_SHERMIE_CARNIVAL_FRAMES, SDM_SHERMIE_CARNIVAL_FRAMES,
  XIANGFEI_KYU_HO_FRAMES, XIANGFEI_KAKU_DA_FRAMES,
  XIANGFEI_NANPA_FRAMES, XIANGFEI_NANPA_C_FRAMES,
  XIANGFEI_TENPATSU_FRAMES, XIANGFEI_MAHO_HISHA_FRAMES,
  DM_CHO_KA_RINGA_FRAMES, SDM_CHO_KA_RINGA_FRAMES,
  YAMAZAKI_SNAKE_ARM_FRAMES, YAMAZAKI_SNAKE_ARM_C_FRAMES,
  YAMAZAKI_SANDSTORM_FRAMES, YAMAZAKI_BAI_GA_SE_FRAMES,
  DM_GUILLOTINE_FRAMES, SDM_GUILLOTINE_FRAMES,
  KASUMI_KOOU_KEN_FRAMES, KASUMI_KOOU_KEN_C_FRAMES,
  KASUMI_KASANE_ATE_FRAMES, KASUMI_MUKIGENZAN_FRAMES,
  DM_CHO_MUKIGENZAN_FRAMES, SDM_CHO_MUKIGENZAN_FRAMES,
  MARY_STRAIGHT_SLICER_FRAMES, MARY_STRAIGHT_SLICER_C_FRAMES,
  MARY_BACKDROP_REAL_FRAMES, MARY_SPIDER_FRAMES,
  DM_MARY_TYPHOON_FRAMES, SDM_MARY_TYPHOON_FRAMES,
} from '../src/core/attackFrames_split/chrisShermieRest.js';
import {
  DM_OROCHINAGI_FRAMES, SDM_OROCHINAGI_FRAMES, HSDM_OROCHINAGI_FRAMES,
  DM_YATAGARASU_FRAMES, SDM_YATAGARASU_FRAMES, HSDM_YAOTOME_FRAMES,
  DM_POWER_GEYSER_FRAMES, DM_PHOENIX_KICK_FRAMES,
  DM_TEN_HA_OU_FRAMES, SDM_TEN_HA_OU_FRAMES,
  DM_RYUKO_RANBU_FRAMES, SDM_RYUKO_RANBU_FRAMES, HSDM_RYUKO_RANBU_FRAMES,
  RYO_KOOUKEN_D_FRAMES, RYO_HIO_HACKER_FRAMES, RYO_ZANRETSU_KEN_FRAMES,
  DM_V_SLASHER_FRAMES,
} from '../src/core/attackFrames_split/dmSupers.js';
import {
  IORI_AOIHANA_FRAMES, IORI_AOIHANA_2_FRAMES, IORI_AOIHANA_3_FRAMES,
  IORI_AOIHANA_C_FRAMES, IORI_AOIHANA_C_2_FRAMES, IORI_AOIHANA_C_3_FRAMES,
  IORI_YAMIBARAI_FRAMES, IORI_YAMIBARAI_C_FRAMES,
  IORI_ONIYAKI_FRAMES, IORI_ONIYAKI_C_FRAMES,
  IORI_KOTOTSUKI_FRAMES, IORI_KOTOTSUKI_D_FRAMES,
  IORI_KUZUKAZE_FRAMES,
} from '../src/core/attackFrames_split/ioriSpecials.js';
import {
  KYO_75KAI_FRAMES, KYO_75KAI_2_FRAMES,
  KYO_RED_KICK_FRAMES,
  KYO_ARAGAMI_FRAMES, KYO_ARAGAMI_KONOKIZU_FRAMES, KYO_ARAGAMI_YANOSABI_FRAMES,
  KYO_NANASE_FRAMES, KYO_KOTO_TSUKI_FRAMES,
  KYO_YAKISOGI_FRAMES, KYO_DOKUGAMI_FRAMES,
  KYO_TSUMIYOMI_FRAMES, KYO_BATSUYOMI_FRAMES,
  KYO_ONIYAKI_FRAMES, KYO_ONIYAKI_C_FRAMES,
  KYO_YAMIBARAI_FRAMES, KYO_YAMIBARAI_C_FRAMES,
} from '../src/core/attackFrames_split/kyoSpecials.js';
import {
  TERRY_BURN_KNUCKLE_FRAMES, TERRY_CRACK_SHOT_FRAMES,
  TERRY_POWER_WAVE_FRAMES, TERRY_POWER_DUNK_FRAMES,
  TERRY_RISING_TACKLE_FRAMES,
  KIM_HIENZAN_FRAMES, KIM_HANGETSU_FRAMES,
  KIM_HAKI_FRAMES, KIM_HISHOU_FRAMES, KIM_SANREN_FRAMES,
  RYO_KOOU_FRAMES as RYO_KOOU_ATK_FRAMES, RYO_KOOU_C_FRAMES as RYO_KOOU_C_ATK_FRAMES,
  RYO_KO_HOU_FRAMES as RYO_KO_HOU_ATK_FRAMES, RYO_KO_HOU_C_FRAMES as RYO_KO_HOU_C_ATK_FRAMES,
  RYO_HIEN_FRAMES as RYO_HIEN_ATK_FRAMES, RYO_HAOU_FRAMES as RYO_HAOU_ATK_FRAMES,
  LEONA_MOON_SLASH_FRAMES, LEONA_MOON_SLASH_C_FRAMES,
  LEONA_EAR_RING_FRAMES, LEONA_EAR_RING_C_FRAMES,
  LEONA_GRAND_SABER_FRAMES, LEONA_BALTIC_FRAMES,
} from '../src/core/attackFrames_split/terryKimRyoLeona.js';

// ===== Helpers =====

function validateAttackFrameArray(frames: AttackFrame[], label: string) {
  expect(frames.length, `${label} has frames`).toBeGreaterThan(0);
  for (let i = 0; i < frames.length; i++) {
    const f = frames[i];
    expect(f.attack, `${label}[${i}].attack`).toBeDefined();
    expect(Array.isArray(f.attack), `${label}[${i}].attack is array`).toBe(true);
    // Some frames (grabs) have empty attack arrays and use throwBoxes instead
    const hasAttack = f.attack.length > 0;
    const hasThrow = f.throwBoxes && f.throwBoxes.length > 0;
    expect(hasAttack || hasThrow, `${label}[${i}] has attack or throwBoxes`).toBe(true);
    for (const box of f.attack) {
      expect(typeof box.ox, `${label}[${i}] box.ox`).toBe('number');
      expect(typeof box.oy, `${label}[${i}] box.oy`).toBe('number');
      expect(typeof box.w, `${label}[${i}] box.w`).toBe('number');
      expect(typeof box.h, `${label}[${i}] box.h`).toBe('number');
      expect(box.w, `${label}[${i}] box.w positive`).toBeGreaterThan(0);
      expect(box.h, `${label}[${i}] box.h positive`).toBeGreaterThan(0);
    }
    // bodyOverride can have negative w/h (offset-relative boxes)
    if (f.bodyOverride !== null) {
      expect(typeof f.bodyOverride!.ox, `${label}[${i}].bodyOverride.ox`).toBe('number');
      expect(typeof f.bodyOverride!.oy, `${label}[${i}].bodyOverride.oy`).toBe('number');
      expect(typeof f.bodyOverride!.w, `${label}[${i}].bodyOverride.w`).toBe('number');
      expect(typeof f.bodyOverride!.h, `${label}[${i}].bodyOverride.h`).toBe('number');
    }
  }
}

// ===== All frame sets collected for bulk validation =====

type NamedFrames = [string, AttackFrame[]];

const ALL_FRAME_SETS: NamedFrames[] = [
  // andyBillyChangChoiYashiro
  ['ANDY_HISHOU_KEN', ANDY_HISHOU_KEN_FRAMES],
  ['ANDY_HISHOU_KEN_C', ANDY_HISHOU_KEN_C_FRAMES],
  ['ANDY_SHOURYUU_DAN', ANDY_SHOURYUU_DAN_FRAMES],
  ['ANDY_SHOURYUU_DAN_C', ANDY_SHOURYUU_DAN_C_FRAMES],
  ['ANDY_ZANEI_RYUSEI_KEN', ANDY_ZANEI_RYUSEI_KEN_FRAMES],
  ['ANDY_ZANEI_RYUSEI_KEN_D', ANDY_ZANEI_RYUSEI_KEN_D_FRAMES],
  ['ANDY_GEKI_HISHOU_KEN', ANDY_GEKI_HISHOU_KEN_FRAMES],
  ['DM_CHO_REPPA_DAN', DM_CHO_REPPA_DAN_FRAMES],
  ['SDM_CHO_REPPA_DAN', SDM_CHO_REPPA_DAN_FRAMES],
  ['BILLY_SANSETSU_KON', BILLY_SANSETSU_KON_FRAMES],
  ['BILLY_SANSETSU_KON_C', BILLY_SANSETSU_KON_C_FRAMES],
  ['BILLY_SENPU_KON', BILLY_SENPU_KON_FRAMES],
  ['BILLY_SENPU_KON_C', BILLY_SENPU_KON_C_FRAMES],
  ['BILLY_HIEN_ZAN', BILLY_HIEN_ZAN_FRAMES],
  ['BILLY_HIEN_ZAN_D', BILLY_HIEN_ZAN_D_FRAMES],
  ['DM_KAEN_SENPU_JIN', DM_KAEN_SENPU_JIN_FRAMES],
  ['SDM_KAEN_SENPU_JIN', SDM_KAEN_SENPU_JIN_FRAMES],
  ['CHANG_TEKKYUU_KAITEN', CHANG_TEKKYUU_KAITEN_FRAMES],
  ['CHANG_TEKKYUU_KAITEN_C', CHANG_TEKKYUU_KAITEN_C_FRAMES],
  ['CHANG_TEKKYUU_FASSHU', CHANG_TEKKYUU_FASSHU_FRAMES],
  ['CHANG_TEKKYUU_HIEN_ZAN', CHANG_TEKKYUU_HIEN_ZAN_FRAMES],
  ['DM_TEKKYUU_DAI_BOUSOU', DM_TEKKYUU_DAI_BOUSOU_FRAMES],
  ['SDM_TEKKYUU_DAI_BOUSOU', SDM_TEKKYUU_DAI_BOUSOU_FRAMES],
  ['CHOI_SOUTEN_MEKKYAKU', CHOI_SOUTEN_MEKKYAKU_FRAMES],
  ['CHOI_SAN_REN_GEKI', CHOI_SAN_REN_GEKI_FRAMES],
  ['CHOI_HISHOU_KYAKU', CHOI_HISHOU_KYAKU_FRAMES],
  ['CHOI_HISHOU_KYAKU_C', CHOI_HISHOU_KYAKU_C_FRAMES],
  ['CHOI_KAITEN_HIEN_ZAN', CHOI_KAITEN_HIEN_ZAN_FRAMES],
  ['CHOI_KAITEN_HIEN_ZAN_C', CHOI_KAITEN_HIEN_ZAN_C_FRAMES],
  ['CHOI_HOUYOKU_TENSHIN', CHOI_HOUYOKU_TENSHIN_FRAMES],
  ['DM_SHIN_CHOU_HOUYOKU', DM_SHIN_CHOU_HOUYOKU_FRAMES],
  ['SDM_SHIN_CHOU_HOUYOKU', SDM_SHIN_CHOU_HOUYOKU_FRAMES],
  ['YASHIRO_UPPER_DU', YASHIRO_UPPER_DU_FRAMES],
  ['YASHIRO_UPPER_DU_C', YASHIRO_UPPER_DU_C_FRAMES],
  ['YASHIRO_NIRAAI', YASHIRO_NIRAAI_FRAMES],
  ['YASHIRO_MUSATSU', YASHIRO_MUSATSU_FRAMES],
  ['DM_ARMAGEDDON_BUSTERS', DM_ARMAGEDDON_BUSTERS_FRAMES],
  ['SDM_ARMAGEDDON_BUSTERS', SDM_ARMAGEDDON_BUSTERS_FRAMES],
  ['MATURE_MASSACRE', MATURE_MASSACRE_FRAMES],
  ['MATURE_MASSACRE_C', MATURE_MASSACRE_C_FRAMES],
  ['MATURE_HEAVENS_GATE', MATURE_HEAVENS_GATE_FRAMES],
  ['MATURE_ECSTASY', MATURE_ECSTASY_FRAMES],
  ['DM_NOCTURNAL_LIGHT', DM_NOCTURNAL_LIGHT_FRAMES],
  ['SDM_NOCTURNAL_LIGHT', SDM_NOCTURNAL_LIGHT_FRAMES],
  ['VICE_OUTRAGE', VICE_OUTRAGE_FRAMES],
  ['VICE_OUTRAGE_C', VICE_OUTRAGE_C_FRAMES],
  ['VICE_BLACK_END', VICE_BLACK_END_FRAMES],
  ['VICE_MAYHEM', VICE_MAYHEM_FRAMES],
  ['DM_NEGATIVE_GAIN', DM_NEGATIVE_GAIN_FRAMES],
  ['SDM_NEGATIVE_GAIN', SDM_NEGATIVE_GAIN_FRAMES],
  // athenaMaiClarkRalfJoe
  ['ATHENA_PSYCHO_BALL', ATHENA_PSYCHO_BALL_FRAMES],
  ['ATHENA_PSYCHO_BALL_C', ATHENA_PSYCHO_BALL_C_FRAMES],
  ['ATHENA_PSYCHO_SWORD', ATHENA_PSYCHO_SWORD_FRAMES],
  ['ATHENA_PSYCHO_SWORD_C', ATHENA_PSYCHO_SWORD_C_FRAMES],
  ['ATHENA_PHOENIX_ARROW', ATHENA_PHOENIX_ARROW_FRAMES],
  ['DM_SHINING_CRYSTAL_BIT', DM_SHINING_CRYSTAL_BIT_FRAMES],
  ['MAI_KA_CHO_SEN', MAI_KA_CHO_SEN_FRAMES],
  ['MAI_KA_CHO_SEN_C', MAI_KA_CHO_SEN_C_FRAMES],
  ['MAI_HISHO_RYU_EN_JIN', MAI_HISHO_RYU_EN_JIN_FRAMES],
  ['MAI_RYU_EN_BU', MAI_RYU_EN_BU_FRAMES],
  ['DM_HAKA_OTOSHI', DM_HAKA_OTOSHI_FRAMES],
  ['CLARK_ARGENTINE', CLARK_ARGENTINE_FRAMES],
  ['CLARK_ARGENTINE_C', CLARK_ARGENTINE_C_FRAMES],
  ['CLARK_FLASH_ELBOW', CLARK_FLASH_ELBOW_FRAMES],
  ['CLARK_VULCAN', CLARK_VULCAN_FRAMES],
  ['DM_ARGENTINE_DM', DM_ARGENTINE_DM_FRAMES],
  ['SDM_ARGENTINE_DM', SDM_ARGENTINE_DM_FRAMES],
  ['RALF_VULCAN', RALF_VULCAN_FRAMES],
  ['RALF_VULCAN_C', RALF_VULCAN_C_FRAMES],
  ['RALF_BACKBREAKER', RALF_BACKBREAKER_FRAMES],
  ['RALF_KICK', RALF_KICK_FRAMES],
  ['DM_GALACTICA_PHANTOM', DM_GALACTICA_PHANTOM_FRAMES],
  ['JOE_HURRICANE', JOE_HURRICANE_FRAMES],
  ['JOE_HURRICANE_C', JOE_HURRICANE_C_FRAMES],
  ['JOE_TIGER_KICK', JOE_TIGER_KICK_FRAMES],
  ['JOE_TIGER_KICK_D', JOE_TIGER_KICK_D_FRAMES],
  ['JOE_BAKURETSUKEN', JOE_BAKURETSUKEN_FRAMES],
  ['JOE_OUGON_KAKATO', JOE_OUGON_KAKATO_FRAMES],
  ['DM_SCREW_UPPER', DM_SCREW_UPPER_FRAMES],
  // chrisShermieRest
  ['CHRIS_SHOT_WEAVE', CHRIS_SHOT_WEAVE_FRAMES],
  ['CHRIS_SHOT_WEAVE_C', CHRIS_SHOT_WEAVE_C_FRAMES],
  ['CHRIS_TWISTER_DRIVE', CHRIS_TWISTER_DRIVE_FRAMES],
  ['CHRIS_SCRAMBLE_DASH', CHRIS_SCRAMBLE_DASH_FRAMES],
  ['DM_CHAIN_SLIDE_TOUCH', DM_CHAIN_SLIDE_TOUCH_FRAMES],
  ['SDM_CHAIN_SLIDE_TOUCH', SDM_CHAIN_SLIDE_TOUCH_FRAMES],
  ['SHERMIE_SHOOT', SHERMIE_SHOOT_FRAMES],
  ['SHERMIE_SHOOT_C', SHERMIE_SHOOT_C_FRAMES],
  ['SHERMIE_CARNIVAL', SHERMIE_CARNIVAL_FRAMES],
  ['SHERMIE_AXLE_SPIN', SHERMIE_AXLE_SPIN_FRAMES],
  ['DM_SHERMIE_CARNIVAL', DM_SHERMIE_CARNIVAL_FRAMES],
  ['SDM_SHERMIE_CARNIVAL', SDM_SHERMIE_CARNIVAL_FRAMES],
  ['XIANGFEI_KYU_HO', XIANGFEI_KYU_HO_FRAMES],
  ['XIANGFEI_KAKU_DA', XIANGFEI_KAKU_DA_FRAMES],
  ['XIANGFEI_NANPA', XIANGFEI_NANPA_FRAMES],
  ['XIANGFEI_NANPA_C', XIANGFEI_NANPA_C_FRAMES],
  ['XIANGFEI_TENPATSU', XIANGFEI_TENPATSU_FRAMES],
  ['XIANGFEI_MAHO_HISHA', XIANGFEI_MAHO_HISHA_FRAMES],
  ['DM_CHO_KA_RINGA', DM_CHO_KA_RINGA_FRAMES],
  ['SDM_CHO_KA_RINGA', SDM_CHO_KA_RINGA_FRAMES],
  ['YAMAZAKI_SNAKE_ARM', YAMAZAKI_SNAKE_ARM_FRAMES],
  ['YAMAZAKI_SNAKE_ARM_C', YAMAZAKI_SNAKE_ARM_C_FRAMES],
  ['YAMAZAKI_SANDSTORM', YAMAZAKI_SANDSTORM_FRAMES],
  ['YAMAZAKI_BAI_GA_SE', YAMAZAKI_BAI_GA_SE_FRAMES],
  ['DM_GUILLOTINE', DM_GUILLOTINE_FRAMES],
  ['SDM_GUILLOTINE', SDM_GUILLOTINE_FRAMES],
  ['KASUMI_KOOU_KEN', KASUMI_KOOU_KEN_FRAMES],
  ['KASUMI_KOOU_KEN_C', KASUMI_KOOU_KEN_C_FRAMES],
  ['KASUMI_KASANE_ATE', KASUMI_KASANE_ATE_FRAMES],
  ['KASUMI_MUKIGENZAN', KASUMI_MUKIGENZAN_FRAMES],
  ['DM_CHO_MUKIGENZAN', DM_CHO_MUKIGENZAN_FRAMES],
  ['SDM_CHO_MUKIGENZAN', SDM_CHO_MUKIGENZAN_FRAMES],
  ['MARY_STRAIGHT_SLICER', MARY_STRAIGHT_SLICER_FRAMES],
  ['MARY_STRAIGHT_SLICER_C', MARY_STRAIGHT_SLICER_C_FRAMES],
  ['MARY_BACKDROP_REAL', MARY_BACKDROP_REAL_FRAMES],
  ['MARY_SPIDER', MARY_SPIDER_FRAMES],
  ['DM_MARY_TYPHOON', DM_MARY_TYPHOON_FRAMES],
  ['SDM_MARY_TYPHOON', SDM_MARY_TYPHOON_FRAMES],
  // dmSupers
  ['DM_OROCHINAGI', DM_OROCHINAGI_FRAMES],
  ['SDM_OROCHINAGI', SDM_OROCHINAGI_FRAMES],
  ['HSDM_OROCHINAGI', HSDM_OROCHINAGI_FRAMES],
  ['DM_YATAGARASU', DM_YATAGARASU_FRAMES],
  ['SDM_YATAGARASU', SDM_YATAGARASU_FRAMES],
  ['HSDM_YAOTOME', HSDM_YAOTOME_FRAMES],
  ['DM_POWER_GEYSER', DM_POWER_GEYSER_FRAMES],
  ['DM_PHOENIX_KICK', DM_PHOENIX_KICK_FRAMES],
  ['DM_TEN_HA_OU', DM_TEN_HA_OU_FRAMES],
  ['SDM_TEN_HA_OU', SDM_TEN_HA_OU_FRAMES],
  ['DM_RYUKO_RANBU', DM_RYUKO_RANBU_FRAMES],
  ['SDM_RYUKO_RANBU', SDM_RYUKO_RANBU_FRAMES],
  ['HSDM_RYUKO_RANBU', HSDM_RYUKO_RANBU_FRAMES],
  ['RYO_KOOUKEN_D', RYO_KOOUKEN_D_FRAMES],
  ['RYO_HIO_HACKER', RYO_HIO_HACKER_FRAMES],
  ['RYO_ZANRETSU_KEN', RYO_ZANRETSU_KEN_FRAMES],
  ['DM_V_SLASHER', DM_V_SLASHER_FRAMES],
  // ioriSpecials
  ['IORI_AOIHANA', IORI_AOIHANA_FRAMES],
  ['IORI_AOIHANA_2', IORI_AOIHANA_2_FRAMES],
  ['IORI_AOIHANA_3', IORI_AOIHANA_3_FRAMES],
  ['IORI_AOIHANA_C', IORI_AOIHANA_C_FRAMES],
  ['IORI_AOIHANA_C_2', IORI_AOIHANA_C_2_FRAMES],
  ['IORI_AOIHANA_C_3', IORI_AOIHANA_C_3_FRAMES],
  ['IORI_YAMIBARAI', IORI_YAMIBARAI_FRAMES],
  ['IORI_YAMIBARAI_C', IORI_YAMIBARAI_C_FRAMES],
  ['IORI_ONIYAKI', IORI_ONIYAKI_FRAMES],
  ['IORI_ONIYAKI_C', IORI_ONIYAKI_C_FRAMES],
  ['IORI_KOTOTSUKI', IORI_KOTOTSUKI_FRAMES],
  ['IORI_KOTOTSUKI_D', IORI_KOTOTSUKI_D_FRAMES],
  ['IORI_KUZUKAZE', IORI_KUZUKAZE_FRAMES],
  // kyoSpecials
  ['KYO_75KAI', KYO_75KAI_FRAMES],
  ['KYO_75KAI_2', KYO_75KAI_2_FRAMES],
  ['KYO_RED_KICK', KYO_RED_KICK_FRAMES],
  ['KYO_ARAGAMI', KYO_ARAGAMI_FRAMES],
  ['KYO_ARAGAMI_KONOKIZU', KYO_ARAGAMI_KONOKIZU_FRAMES],
  ['KYO_ARAGAMI_YANOSABI', KYO_ARAGAMI_YANOSABI_FRAMES],
  ['KYO_NANASE', KYO_NANASE_FRAMES],
  ['KYO_KOTO_TSUKI', KYO_KOTO_TSUKI_FRAMES],
  ['KYO_YAKISOGI', KYO_YAKISOGI_FRAMES],
  ['KYO_DOKUGAMI', KYO_DOKUGAMI_FRAMES],
  ['KYO_TSUMIYOMI', KYO_TSUMIYOMI_FRAMES],
  ['KYO_BATSUYOMI', KYO_BATSUYOMI_FRAMES],
  ['KYO_ONIYAKI_SPLIT', KYO_ONIYAKI_FRAMES],
  ['KYO_ONIYAKI_C_SPLIT', KYO_ONIYAKI_C_FRAMES],
  ['KYO_YAMIBARAI_SPLIT', KYO_YAMIBARAI_FRAMES],
  ['KYO_YAMIBARAI_C_SPLIT', KYO_YAMIBARAI_C_FRAMES],
  // terryKimRyoLeona
  ['TERRY_BURN_KNUCKLE', TERRY_BURN_KNUCKLE_FRAMES],
  ['TERRY_CRACK_SHOT', TERRY_CRACK_SHOT_FRAMES],
  ['TERRY_POWER_WAVE', TERRY_POWER_WAVE_FRAMES],
  ['TERRY_POWER_DUNK', TERRY_POWER_DUNK_FRAMES],
  ['TERRY_RISING_TACKLE', TERRY_RISING_TACKLE_FRAMES],
  ['KIM_HIENZAN', KIM_HIENZAN_FRAMES],
  ['KIM_HANGETSU', KIM_HANGETSU_FRAMES],
  ['KIM_HAKI', KIM_HAKI_FRAMES],
  ['KIM_HISHOU', KIM_HISHOU_FRAMES],
  ['KIM_SANREN', KIM_SANREN_FRAMES],
  ['RYO_KOOU_ATK', RYO_KOOU_ATK_FRAMES],
  ['RYO_KOOU_C_ATK', RYO_KOOU_C_ATK_FRAMES],
  ['RYO_KO_HOU_ATK', RYO_KO_HOU_ATK_FRAMES],
  ['RYO_KO_HOU_C_ATK', RYO_KO_HOU_C_ATK_FRAMES],
  ['RYO_HIEN_ATK', RYO_HIEN_ATK_FRAMES],
  ['RYO_HAOU_ATK', RYO_HAOU_ATK_FRAMES],
  ['LEONA_MOON_SLASH', LEONA_MOON_SLASH_FRAMES],
  ['LEONA_MOON_SLASH_C', LEONA_MOON_SLASH_C_FRAMES],
  ['LEONA_EAR_RING', LEONA_EAR_RING_FRAMES],
  ['LEONA_EAR_RING_C', LEONA_EAR_RING_C_FRAMES],
  ['LEONA_GRAND_SABER', LEONA_GRAND_SABER_FRAMES],
  ['LEONA_BALTIC', LEONA_BALTIC_FRAMES],
];

// ===== Bulk structural validation =====

describe('Attack Frame Split Files — All Sets', () => {
  for (const [name, frames] of ALL_FRAME_SETS) {
    it(`${name} has valid structure`, () => {
      validateAttackFrameArray(frames, name);
    });
  }
});

// ===== Counts =====

describe('Attack Frame Split Files — Counts', () => {
  it('total frame sets is reasonable (>130)', () => {
    expect(ALL_FRAME_SETS.length).toBeGreaterThan(130);
  });

  // Per-file counts
  it('andyBillyChangChoiYashiro has >45 sets', () => {
    const andyStart = ALL_FRAME_SETS.findIndex(([n]) => n === 'ANDY_HISHOU_KEN');
    const viceEnd = ALL_FRAME_SETS.findIndex(([n]) => n === 'SDM_NEGATIVE_GAIN');
    expect(viceEnd - andyStart + 1).toBeGreaterThanOrEqual(45);
  });

  it('athenaMaiClarkRalfJoe has >25 sets', () => {
    const athenaStart = ALL_FRAME_SETS.findIndex(([n]) => n === 'ATHENA_PSYCHO_BALL');
    const joeEnd = ALL_FRAME_SETS.findIndex(([n]) => n === 'DM_SCREW_UPPER');
    expect(joeEnd - athenaStart + 1).toBeGreaterThanOrEqual(25);
  });
});

// ===== DM escalation =====

describe('Attack Frame Split Files — DM/SDM/HSDM escalation', () => {
  it('SDM_OROCHINAGI has >= DM_OROCHINAGI frames', () => {
    expect(SDM_OROCHINAGI_FRAMES.length).toBeGreaterThanOrEqual(DM_OROCHINAGI_FRAMES.length);
  });

  it('HSDM_OROCHINAGI has >= DM_OROCHINAGI frames', () => {
    expect(HSDM_OROCHINAGI_FRAMES.length).toBeGreaterThanOrEqual(DM_OROCHINAGI_FRAMES.length);
  });

  it('SDM_YATAGARASU has >= DM_YATAGARASU frames', () => {
    expect(SDM_YATAGARASU_FRAMES.length).toBeGreaterThanOrEqual(DM_YATAGARASU_FRAMES.length);
  });

  it('SDM_RYUKO_RANBU has >= DM_RYUKO_RANBU frames', () => {
    expect(SDM_RYUKO_RANBU_FRAMES.length).toBeGreaterThanOrEqual(DM_RYUKO_RANBU_FRAMES.length);
  });
});

// ===== C-version consistency =====

describe('Attack Frame Split Files — C-version consistency', () => {
  it('ANDY_HISHOU_KEN_C has frames (may differ from A)', () => {
    expect(ANDY_HISHOU_KEN_C_FRAMES.length).toBeGreaterThan(0);
  });

  it('BILLY_SANSETSU_KON_C has frames (may differ from A)', () => {
    expect(BILLY_SANSETSU_KON_C_FRAMES.length).toBeGreaterThan(0);
  });

  it('ATHENA_PSYCHO_BALL_C has same frame count as ATHENA_PSYCHO_BALL', () => {
    expect(ATHENA_PSYCHO_BALL_C_FRAMES.length).toBe(ATHENA_PSYCHO_BALL_FRAMES.length);
  });

  it('LEONA_MOON_SLASH_C has same frame count as LEONA_MOON_SLASH', () => {
    expect(LEONA_MOON_SLASH_C_FRAMES.length).toBe(LEONA_MOON_SLASH_FRAMES.length);
  });
});
