/**
 * Kyo Kusanagi frame data — extracted from frameDataChars.ts
 * Dream Cancel Wiki KOF2002UM 精确数据
 */
export const KYO_FRAME_DATA = {
  // ── 京专属必杀技 (Kyo Kusanagi) ── Dream Cancel Wiki KOF2002UM 精确数据
  // 75式·改 qcf+B (第1段)
  KYO_75KAI: {
    startup: 14,
    active: 4,
    recovery: 14,
    damage: 40,
    hitstun: 19,
    blockstun: 17,
    pushback: 3,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // 75式·改 第2段 (qcf+K 追加)
  KYO_75KAI_2: {
    startup: 7,
    active: 4,
    recovery: 14,
    damage: 40,
    hitstun: 19,
    blockstun: 17,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // R.E.D. Kicks rdp+B/D
  KYO_RED_KICK: {
    startup: 19,
    active: 5,
    recovery: 33,
    damage: 108,
    hitstun: 19,
    blockstun: 17,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 鬼焼き dp+A (2段上升拳, SKD)
  KYO_ONIYAKI: {
    startup: 6,
    active: 5,
    recovery: 38,
    damage: 58,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  // 鬼焼き dp+C (长版, 多段)
  KYO_ONIYAKI_C: {
    startup: 6,
    active: 10,
    recovery: 48,
    damage: 108,
    hitstun: 28,
    blockstun: 22,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 14,
  },
  // 暗払い qcf+A (飞行道具)
  KYO_YAMIBARAI: {
    startup: 10,
    active: 20,
    recovery: 30,
    damage: 70,
    hitstun: 28,
    blockstun: 26,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  KYO_YAMIBARAI_C: {
    startup: 11,
    active: 22,
    recovery: 28,
    damage: 100,
    hitstun: 30,
    blockstun: 28,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 10,
  },
  // 荒咬み qcf+A (rekka 1段目)
  KYO_ARAGAMI: {
    startup: 12,
    active: 4,
    recovery: 18,
    damage: 58,
    hitstun: 19,
    blockstun: 17,
    pushback: 3,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // 九傷 qcf+A→qcf+P (rekka 2段目, SKD)
  KYO_ARAGAMI_KONOKIZU: {
    startup: 8,
    active: 4,
    recovery: 31,
    damage: 42,
    hitstun: 19,
    blockstun: 17,
    pushback: 3,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 八錆 qcf+A→qcf+P→P (rekka 3段P, HKD overhead)
  KYO_ARAGAMI_YANOSABI: {
    startup: 14,
    active: 5,
    recovery: 31,
    damage: 25,
    hitstun: 19,
    blockstun: 17,
    pushback: 5,
    hitLevel: "HIGH" as const,
    knockdown: true,
  },
  // 七瀬 qcf+A→qcf+P→K (rekka 3段K, SKD)
  KYO_NANASE: {
    startup: 17,
    active: 5,
    recovery: 24,
    damage: 67,
    hitstun: 19,
    blockstun: 17,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 轢鉄 qcf+A→hcb+P→hcb+K (HKD)
  KYO_KOTO_TSUKI: {
    startup: 10,
    active: 6,
    recovery: 38,
    damage: 83,
    hitstun: 19,
    blockstun: 17,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 毒咬み qcf+C (rekka C系1段目)
  KYO_DOKUGAMI: {
    startup: 18,
    active: 4,
    recovery: 21,
    damage: 25,
    hitstun: 19,
    blockstun: 17,
    pushback: 3,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // 罪詠み qcf+C→hcb+P
  KYO_TSUMIYOMI: {
    startup: 11,
    active: 4,
    recovery: 34,
    damage: 33,
    hitstun: 19,
    blockstun: 17,
    pushback: 3,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // 罰詠み qcf+C→hcb+P→f+P (SKD)
  KYO_BATSUYOMI: {
    startup: 14,
    active: 5,
    recovery: 42,
    damage: 33,
    hitstun: 19,
    blockstun: 17,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 焼きそぎ (空中DOWN+P, KD)
  KYO_YAKISOGI: {
    startup: 11,
    active: 4,
    recovery: 30,
    damage: 60,
    hitstun: 19,
    blockstun: 17,
    pushback: 4,
    hitLevel: "HIGH" as const,
    knockdown: true,
  },
  // ── 京 Command Normals ──
  CMD_GOFU_YOU: {
    startup: 12,
    active: 5,
    recovery: 18,
    damage: 42,
    hitstun: 17,
    blockstun: 15,
    pushback: 3,
    hitLevel: "HIGH" as const,
    knockdown: false,
  },
  CMD_88SHIKI: {
    startup: 10,
    active: 6,
    recovery: 20,
    damage: 50,
    hitstun: 19,
    blockstun: 17,
    pushback: 4,
    hitLevel: "LOW" as const,
    knockdown: false,
  },
  CMD_NARAKU: {
    startup: 8,
    active: 5,
    recovery: 16,
    damage: 35,
    hitstun: 17,
    blockstun: 15,
    pushback: 3,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // ── 京DM/SDM ── Dream Cancel Wiki KOF2002UM
  DM_OROCHINAGI: {
    startup: 18,
    active: 30,
    recovery: 28,
    damage: 280,
    hitstun: 0,
    blockstun: 20,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 24,
  },
  SDM_OROCHINAGI: {
    startup: 20,
    active: 38,
    recovery: 29,
    damage: 342,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 30,
  },
  HSDM_OROCHINAGI: {
    startup: 5,
    active: 30,
    recovery: 32,
    damage: 400,
    hitstun: 0,
    blockstun: 24,
    pushback: 16,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 40,
  },
} as const;
