/**
 * Ryo Sakazaki frame data — extracted from frameDataChars.ts
 * KOF2002UM calibrated data
 */
export const RYO_FRAME_DATA = {
  // ── 坂崎亮命令通常技 (Ryo Sakazaki Command Normals) ── KOF2002UM calibrated
  // 冰柱割り →+A (Tsurizarao, overhead)
  RYO_TSURIZAO: {
    startup: 14,
    active: 4,
    recovery: 18,
    damage: 44,
    hitstun: 19,
    blockstun: 16,
    pushback: 3,
    hitLevel: "HIGH" as const,
    knockdown: false,
    chipDamage: 0,
  },
  // 落蹴 ↘+B (Orishi, low kick)
  RYO_ORISHI: {
    startup: 8,
    active: 4,
    recovery: 20,
    damage: 38,
    hitstun: 18,
    blockstun: 15,
    pushback: 2,
    hitLevel: "LOW" as const,
    knockdown: false,
    chipDamage: 0,
  },
  // ── 坂崎亮必杀技 (Ryo Sakazaki) ── KOF2002UM calibrated
  // 虎煌拳 qcf+A (Ko'ou Ken, projectile)
  RYO_KOOU: {
    startup: 12,
    active: 18,
    recovery: 34,
    damage: 75,
    hitstun: 28,
    blockstun: 26,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  // 虎煌拳 qcf+C (Ko'ou Ken, strong projectile)
  RYO_KOOU_C: {
    startup: 13,
    active: 20,
    recovery: 32,
    damage: 105,
    hitstun: 30,
    blockstun: 28,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 10,
  },
  // 虎煌拳 重版 qcf+D (Ko'ou Ken D, heavy projectile) — KOF2002UM 校准数据
  RYO_KOOUKEN_D: {
    startup: 15,
    active: 22,
    recovery: 30,
    damage: 120,
    hitstun: 32,
    blockstun: 30,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 12,
  },
  // 虎煌 dp+A (Kohou, weak DP, KD)
  RYO_KO_HOU: {
    startup: 5,
    active: 5,
    recovery: 25,
    damage: 80,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  // 虎煌 dp+C (Kohou, strong DP, KD)
  RYO_KO_HOU_C: {
    startup: 7,
    active: 10,
    recovery: 30,
    damage: 140,
    hitstun: 28,
    blockstun: 22,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 14,
  },
  // 飛燕疾風脚 qcb+K (Hien Shippu Kyaku, flying kick)
  RYO_HIEN: {
    startup: 10,
    active: 8,
    recovery: 22,
    damage: 95,
    hitstun: 24,
    blockstun: 20,
    pushback: 8,
    hitLevel: "HIGH" as const,
    knockdown: true,
  },
  // 暢連拳 hcb+P (Zanretsu Ken, multi-punch)
  RYO_HAOU: {
    startup: 10,
    active: 12,
    recovery: 22,
    damage: 80,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // 氷果斬 f+A (突进技)
  RYO_HIO_HACKER: {
    startup: 8,
    active: 6,
    recovery: 18,
    damage: 75,
    hitstun: 16,
    blockstun: 14,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // 斩裂拳 qcb+P (连打技, damage per hit ×6)
  RYO_ZANRETSU_KEN: {
    startup: 4,
    active: 4,
    recovery: 16,
    damage: 12,
    hitstun: 18,
    blockstun: 14,
    pushback: 2,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // DM 霸王翔吼拳 (Haoh Shoukou Ken, projectile DM)
  DM_TEN_HA_OU: {
    startup: 18,
    active: 10,
    recovery: 40,
    damage: 200,
    hitstun: 0,
    blockstun: 22,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 18,
  },
  // DM 龍虎乱舞 (Ryuko Ranbu, rushing DM)
  DM_RYUKO_RANBU: {
    startup: 8,
    active: 10,
    recovery: 38,
    damage: 220,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  // SDM 龍虎乱舞 (Ryuko Ranbu SDM)
  SDM_RYUKO_RANBU: {
    startup: 6,
    active: 13,
    recovery: 36,
    damage: 310,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 30,
  },
  // SDM 龍虎乱舞·EX (Ryuko Ranbu EX SDM, MAX强化版)
  SDM_RYUKO_RANBU_EX: {
    startup: 3,
    active: 18,
    recovery: 34,
    damage: 320,
    hitstun: 0,
    blockstun: 21,
    pushback: 14,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 32,
  },
  // HSDM 龍虎乱舞 (Ryuko Ranbu HSDM, hidden super)
  HSDM_RYUKO_RANBU: {
    startup: 2,
    active: 22,
    recovery: 32,
    damage: 380,
    hitstun: 30,
    blockstun: 21,
    pushback: 16,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 40,
  },
  // SDM 霸王翔吼拳 (Haoh Shoukou Ken SDM)
  SDM_TEN_HA_OU: {
    startup: 10,
    active: 22,
    recovery: 35,
    damage: 280,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 25,
  },
} as const;
