/**
 * Kim Kaphwan frame data — extracted from frameDataChars.ts / frameDataTerryKim.ts
 * Dream Cancel Wiki KOF2002UM 校准数据
 */
export const KIM_FRAME_DATA = {
  // ── 金专属必杀技 (Kim Kaphwan) ── KOF2002UM calibrated
  // 飛燕斬 dp+B (flash kick, KD)
  KIM_HIENZAN: {
    startup: 5,
    active: 6,
    recovery: 25,
    damage: 100,
    hitstun: 25,
    blockstun: 20,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 12,
  },
  // 飛燕斬 dp+D (强版, 多段 flash kick, KD)
  KIM_HIENZAN_D: {
    startup: 7,
    active: 10,
    recovery: 30,
    damage: 140,
    hitstun: 26,
    blockstun: 20,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 14,
  },
  // 半月斬 qcb+B (half-moon kick, overhead)
  KIM_HANGETSU: {
    startup: 7,
    active: 12,
    recovery: 29,
    damage: 80,
    hitstun: 19,
    blockstun: 17,
    pushback: 5,
    hitLevel: "HIGH" as const,
    knockdown: true,
  },
  // 半月斬 qcb+D (强版, slower overhead)
  KIM_HANGETSU_D: {
    startup: 9,
    active: 14,
    recovery: 31,
    damage: 110,
    hitstun: 22,
    blockstun: 19,
    pushback: 6,
    hitLevel: "HIGH" as const,
    knockdown: true,
  },
  // 覇気蹴り f+B (axe kick, LOW hitlevel)
  KIM_HAKI: {
    startup: 9,
    active: 5,
    recovery: 20,
    damage: 65,
    hitstun: 19,
    blockstun: 17,
    pushback: 3,
    hitLevel: "LOW" as const,
    knockdown: false,
  },
  // 飛翔脚 (flash kick cancel, very fast)
  KIM_HISHOU: {
    startup: 2,
    active: 8,
    recovery: 14,
    damage: 70,
    hitstun: 19,
    blockstun: 17,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 三連蹴り 1段 (triple kick, multi-hit)
  KIM_SANREN: {
    startup: 8,
    active: 14,
    recovery: 24,
    damage: 60,
    hitstun: 19,
    blockstun: 17,
    pushback: 3,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 三連蹴り 追加 (2nd+3rd hits)
  KIM_SANREN_2: {
    startup: 10,
    active: 12,
    recovery: 22,
    damage: 55,
    hitstun: 19,
    blockstun: 17,
    pushback: 3,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 崩し蹴り f+B (中段技, overhead)
  KIM_KUZUSHI_GERI: {
    startup: 10,
    active: 4,
    recovery: 20,
    damage: 50,
    hitstun: 16,
    blockstun: 14,
    pushback: 4,
    hitLevel: "HIGH" as const,
    knockdown: false,
  },
  // 滑り蹴り df+D (下段技, low slide)
  KIM_NERICHAGI: {
    startup: 8,
    active: 6,
    recovery: 22,
    damage: 45,
    hitstun: 14,
    blockstun: 12,
    pushback: 4,
    hitLevel: "LOW" as const,
    knockdown: false,
  },
  // 回転飛燕斬 (对空flash kick, anti-air)
  KIM_KAITEN_HIEN_ZAN: {
    startup: 5,
    active: 8,
    recovery: 28,
    damage: 90,
    hitstun: 22,
    blockstun: 18,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // ── 金 Command Normals ──
  KIM_HISHOU_KICK: {
    startup: 16,
    active: 4,
    recovery: 20,
    damage: 48,
    hitstun: 20,
    blockstun: 17,
    pushback: 3,
    hitLevel: "HIGH" as const,
    knockdown: false,
  },
  KIM_HANSEN: {
    startup: 10,
    active: 5,
    recovery: 22,
    damage: 52,
    hitstun: 19,
    blockstun: 16,
    pushback: 3,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // ── 金DM/SDM ── KOF2002UM calibrated
  DM_PHOENIX_KICK: {
    startup: 8,
    active: 13,
    recovery: 43,
    damage: 200,
    hitstun: 0,
    blockstun: 21,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 17,
  },
  DM_PHOENIX_HITEN: {
    startup: 8,
    active: 5,
    recovery: 30,
    damage: 180,
    hitstun: 0,
    blockstun: 21,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 14,
  },
  SDM_PHOENIX_HITEN: {
    startup: 6,
    active: 8,
    recovery: 28,
    damage: 260,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 22,
  },
  SDM_PHOENIX_HITEN_EX: {
    startup: 5,
    active: 12,
    recovery: 30,
    damage: 280,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 28,
  },
  HSDM_PHOENIX_HITEN: {
    startup: 4,
    active: 15,
    recovery: 32,
    damage: 320,
    hitstun: 0,
    blockstun: 24,
    pushback: 14,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 35,
  },
} as const;
