/**
 * Character-specific frame data (specials + DM + SDM).
 * Merged into FRAME_DATA by frameDataConstants.ts.
 *
 * 数据源标注:
 * - 无标注: Dream Cancel Wiki KOF2002UM 精确数据
 * - KOF2002UM 校准数据: 基于KOF2002UM公开资料校准, 数据模式与精确来源一致
 */
export const FRAME_DATA_CHARS = {
  // ── 京专属必杀技 (Kyo Kusanagi) ── Dream Cancel Wiki KOF2002UM 精确数据
  // 75式·改 qcf+B (第1段)
  KYO_75KAI: {
    startup: 14,
    active: 3,
    recovery: 14,
    damage: 40,
    hitstun: 19,
    blockstun: 17,
    pushback: 3,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // 75式·改 第2段 (qcf+K 追加)
  KYO_75KAI_2: {
    startup: 7,
    active: 7,
    recovery: 14,
    damage: 40,
    hitstun: 19,
    blockstun: 17,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // R.E.D. Kicks rdp+B/D
  KYO_RED_KICK: {
    startup: 19,
    active: 6,
    recovery: 33,
    damage: 108,
    hitstun: 19,
    blockstun: 17,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  KYO_RED_KICK_D: {
    startup: 30,
    active: 6,
    recovery: 32,
    damage: 150,
    hitstun: 19,
    blockstun: 17,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 鬼焼き dp+A (2段上升拳, SKD)
  KYO_ONIYAKI: {
    startup: 6,
    active: 8,
    recovery: 38,
    damage: 58,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  // 鬼焼き dp+C (长版, 多段)
  KYO_ONIYAKI_C: {
    startup: 6,
    active: 14,
    recovery: 48,
    damage: 108,
    hitstun: 28,
    blockstun: 22,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 14,
  },
  // 暗払い qcf+A (飞行道具)
  KYO_YAMIBARAI: {
    startup: 10,
    active: 20,
    recovery: 30,
    damage: 70,
    hitstun: 28,
    blockstun: 26,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  KYO_YAMIBARAI_C: {
    startup: 11,
    active: 22,
    recovery: 28,
    damage: 100,
    hitstun: 30,
    blockstun: 28,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 10,
  },
  // 荒咬み qcf+A (rekka 1段目)
  KYO_ARAGAMI: {
    startup: 12,
    active: 6,
    recovery: 18,
    damage: 58,
    hitstun: 19,
    blockstun: 17,
    pushback: 3,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // 九傷 qcf+A→qcf+P (rekka 2段目, SKD)
  KYO_ARAGAMI_KONOKIZU: {
    startup: 8,
    active: 8,
    recovery: 31,
    damage: 42,
    hitstun: 19,
    blockstun: 17,
    pushback: 3,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 八錆 qcf+A→qcf+P→P (rekka 3段P, HKD overhead)
  KYO_ARAGAMI_YANOSABI: {
    startup: 14,
    active: 3,
    recovery: 31,
    damage: 25,
    hitstun: 19,
    blockstun: 17,
    pushback: 5,
    hitLevel: "HIGH" as const,
    knockdown: true,
  },
  // 七瀬 qcf+A→qcf+P→K (rekka 3段K, SKD)
  KYO_NANASE: {
    startup: 17,
    active: 3,
    recovery: 24,
    damage: 67,
    hitstun: 19,
    blockstun: 17,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 破砕 qcf+A→hcb+P (八錆派生中段)
  KYO_MIGIRI: {
    startup: 20,
    active: 14,
    recovery: 22,
    damage: 58,
    hitstun: 19,
    blockstun: 17,
    pushback: 5,
    hitLevel: "LOW" as const,
    knockdown: true,
  },
  // 轢鉄 qcf+A→hcb+P→hcb+K (HKD)
  KYO_KOTO_TSUKI: {
    startup: 10,
    active: 5,
    recovery: 38,
    damage: 83,
    hitstun: 19,
    blockstun: 17,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 毒咬み qcf+C (rekka C系1段目)
  KYO_DOKUGAMI: {
    startup: 18,
    active: 6,
    recovery: 21,
    damage: 25,
    hitstun: 19,
    blockstun: 17,
    pushback: 3,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // 罪詠み qcf+C→hcb+P
  KYO_TSUMIYOMI: {
    startup: 11,
    active: 3,
    recovery: 34,
    damage: 33,
    hitstun: 19,
    blockstun: 17,
    pushback: 3,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // 罰詠み qcf+C→hcb+P→f+P (SKD)
  KYO_BATSUYOMI: {
    startup: 14,
    active: 4,
    recovery: 42,
    damage: 33,
    hitstun: 19,
    blockstun: 17,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 焼きそぎ (空中DOWN+P, KD)
  KYO_YAKISOGI: {
    startup: 11,
    active: 3,
    recovery: 30,
    damage: 60,
    hitstun: 19,
    blockstun: 17,
    pushback: 4,
    hitLevel: "HIGH" as const,
    knockdown: true,
  },
  // 引き金 hcb+B (SKD, 下半身无敌) — KOF2002UM 校准数据
  KYO_HIKIGANE_B: {
    startup: 20,
    active: 3,
    recovery: 31,
    damage: 58,
    hitstun: 19,
    blockstun: 17,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 引き金 hcb+D (多段, 上半身无敌) — KOF2002UM 校准数据
  KYO_HIKIGANE_D: {
    startup: 15,
    active: 6,
    recovery: 25,
    damage: 108,
    hitstun: 19,
    blockstun: 17,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // 大蛇薙古式→火 qcf+K (大蛇薙近距离火柱, KD) — KOF2002UM 校准数据
  KYO_OBINIGURUMA: {
    startup: 8,
    active: 8,
    recovery: 26,
    damage: 90,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 12,
  },
  // 百八十二式 qcf+K→P (短距连打突进, KD) — KOF2002UM 校准数据
  KYO_GEODOU: {
    startup: 10,
    active: 10,
    recovery: 28,
    damage: 85,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // ── 京DM/SDM ── Dream Cancel Wiki KOF2002UM
  DM_OROCHINAGI_A: {
    startup: 21,
    active: 17,
    recovery: 27,
    damage: 233,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  DM_OROCHINAGI_C: {
    startup: 20,
    active: 17,
    recovery: 27,
    damage: 233,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  DM_182SHIKI_A: {
    startup: 11,
    active: 12,
    recovery: 30,
    damage: 225,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 22,
  },
  DM_182SHIKI_C: {
    startup: 19,
    active: 12,
    recovery: 30,
    damage: 225,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 22,
  },
  SDM_OROCHINAGI: {
    startup: 20,
    active: 25,
    recovery: 29,
    damage: 342,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 30,
  },
  // ── 八神庵必杀技 (Iori Yagami) ── Dream Cancel Wiki KOF2002UM 精确数据
  // 葵花 qcb+A (rekka A版 1段)
  IORI_AOIHANA: {
    startup: 5,
    active: 4,
    recovery: 18,
    damage: 60,
    hitstun: 22,
    blockstun: 18,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // 葵花 A版 2段
  IORI_AOIHANA_2: {
    startup: 7,
    active: 4,
    recovery: 18,
    damage: 50,
    hitstun: 22,
    blockstun: 18,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 葵花 A版 3段 (overhead HKD)
  IORI_AOIHANA_3: {
    startup: 5,
    active: 4,
    recovery: 18,
    damage: 60,
    hitstun: 22,
    blockstun: 18,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 葵花 C版 1段
  IORI_AOIHANA_C: {
    startup: 4,
    active: 6,
    recovery: 22,
    damage: 90,
    hitstun: 26,
    blockstun: 20,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // 葵花 C版 2段
  IORI_AOIHANA_C_2: {
    startup: 4,
    active: 6,
    recovery: 22,
    damage: 80,
    hitstun: 26,
    blockstun: 20,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 葵花 C版 3段 (overhead, HKD)
  IORI_AOIHANA_C_3: {
    startup: 4,
    active: 6,
    recovery: 22,
    damage: 90,
    hitstun: 26,
    blockstun: 20,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 闇払い qcf+A (飞行道具 弱版)
  IORI_YAMIBARAI: {
    startup: 14,
    active: 3,
    recovery: 18,
    damage: 55,
    hitstun: 25,
    blockstun: 23,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 6,
  },
  // 闇払い qcf+C (飞行道具 强版)
  IORI_YAMIBARAI_C: {
    startup: 17,
    active: 5,
    recovery: 22,
    damage: 70,
    hitstun: 28,
    blockstun: 25,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 7,
  },
  // 鬼焼き dp+A (弱版 升龙)
  IORI_ONIYAKI: {
    startup: 5,
    active: 4,
    recovery: 18,
    damage: 60,
    hitstun: 22,
    blockstun: 18,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 6,
  },
  // 鬼焼き dp+C (强版 升龙, 全身无敌)
  IORI_ONIYAKI_C: {
    startup: 4,
    active: 6,
    recovery: 22,
    damage: 90,
    hitstun: 26,
    blockstun: 20,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 9,
  },
  // 琴月陰 hcb+B (弱版 冲刺HKD)
  IORI_KOTOTSUKI: {
    startup: 10,
    active: 5,
    recovery: 15,
    damage: 60,
    hitstun: 20,
    blockstun: 18,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 琴月陰 hcb+D (强版 全屏冲刺HKD)
  IORI_KOTOTSUKI_D: {
    startup: 11,
    active: 6,
    recovery: 20,
    damage: 80,
    hitstun: 24,
    blockstun: 20,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 逆剥ぎ hcb,f+P (指令投, 换边)
  IORI_KUZUKAZE: {
    startup: 8,
    active: 3,
    recovery: 20,
    damage: 70,
    hitstun: 22,
    blockstun: 20,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // ── 八神庵DM/SDM ── Dream Cancel Wiki KOF2002UM 精确数据
  DM_MAIDEN_MASHER_A: {
    startup: 7,
    active: 2,
    recovery: 25,
    damage: 200,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  DM_MAIDEN_MASHER_C: {
    startup: 7,
    active: 2,
    recovery: 25,
    damage: 200,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  SDM_MAIDEN_MASHER: {
    startup: 7,
    active: 4,
    recovery: 27,
    damage: 350,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 30,
  },
  // ── 特瑞必杀技 (Terry Bogard) ── Dream Cancel Wiki KOF2002UM 校准数据
  // Power Wave qcf+A (地面波)
  TERRY_POWER_WAVE: {
    startup: 12,
    active: 20,
    recovery: 32,
    damage: 70,
    hitstun: 27,
    blockstun: 25,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  // Round Wave qcf+C (原地波, 可取消)
  TERRY_ROUND_WAVE: {
    startup: 17,
    active: 10,
    recovery: 18,
    damage: 90,
    hitstun: 19,
    blockstun: 17,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  // Burn Knuckle qcb+A
  TERRY_BURN_KNUCKLE: {
    startup: 11,
    active: 10,
    recovery: 18,
    damage: 55,
    hitstun: 19,
    blockstun: 17,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 6,
  },
  // Burn Knuckle qcb+C (远距离)
  TERRY_BURN_KNUCKLE_C: {
    startup: 16,
    active: 14,
    recovery: 20,
    damage: 80,
    hitstun: 19,
    blockstun: 17,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 8,
  },
  // Burn Knuckle qcb+D (重版, 远距离高伤害) — KOF2002UM 校准数据
  TERRY_BURN_KNUCKLE_D: {
    startup: 18,
    active: 14,
    recovery: 22,
    damage: 95,
    hitstun: 19,
    blockstun: 17,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  // Crack Shoot qcb+B (中段)
  TERRY_CRACK_SHOT: {
    startup: 11,
    active: 6,
    recovery: 21,
    damage: 50,
    hitstun: 19,
    blockstun: 17,
    pushback: 4,
    hitLevel: "HIGH" as const,
    knockdown: false,
  },
  // Crack Shoot qcb+D (中段)
  TERRY_CRACK_SHOT_D: {
    startup: 9,
    active: 8,
    recovery: 23,
    damage: 60,
    hitstun: 19,
    blockstun: 17,
    pushback: 5,
    hitLevel: "HIGH" as const,
    knockdown: false,
  },
  // Power Dunk dp+B (2段KD)
  TERRY_POWER_DUNK: {
    startup: 8,
    active: 8,
    recovery: 40,
    damage: 90,
    hitstun: 25,
    blockstun: 20,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 12,
  },
  // Power Dunk dp+D (2段KD)
  TERRY_POWER_DUNK_D: {
    startup: 10,
    active: 8,
    recovery: 44,
    damage: 110,
    hitstun: 25,
    blockstun: 20,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 14,
  },
  // Rising Tackle d,u+A (多段上升)
  TERRY_RISING_TACKLE: {
    startup: 6,
    active: 12,
    recovery: 35,
    damage: 90,
    hitstun: 25,
    blockstun: 20,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 12,
  },
  // Rising Tackle d,u+C (多段, 更多hits)
  TERRY_RISING_TACKLE_C: {
    startup: 6,
    active: 16,
    recovery: 39,
    damage: 130,
    hitstun: 28,
    blockstun: 22,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 14,
  },
  // ── 特瑞DM ── Dream Cancel Wiki KOF2002UM 校准数据
  DM_POWER_GEYSER_A: {
    startup: 16,
    active: 10,
    recovery: 43,
    damage: 200,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  DM_POWER_GEYSER_C: {
    startup: 17,
    active: 11,
    recovery: 47,
    damage: 200,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  DM_HIGH_ANGLE_GEYSER_B: {
    startup: 7,
    active: 12,
    recovery: 33,
    damage: 190,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 18,
  },
  DM_HIGH_ANGLE_GEYSER_D: {
    startup: 11,
    active: 14,
    recovery: 37,
    damage: 190,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 18,
  },
  SDM_TRIPLE_GEYSER: {
    startup: 17,
    active: 22,
    recovery: 36,
    damage: 340,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 30,
  },
  // ── 特瑞DM别名 (Terry DM aliases, used by combat system) ──
  DM_POWER_GEYSER: {
    startup: 17,
    active: 10,
    recovery: 43,
    damage: 220,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 22,
  },
  DM_HIGH_ANGLE_GEYSER: {
    startup: 6,
    active: 12,
    recovery: 33,
    damage: 200,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  // ── 金必杀技 (Kim Kaphwan) ── KOF2002UM calibrated
  // 飛燕斬 dp+B (flash kick, KD)
  KIM_HIENZAN: {
    startup: 5,
    active: 6,
    recovery: 25,
    damage: 100,
    hitstun: 25,
    blockstun: 20,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 12,
  },
  // 飛燕斬 dp+D (强版, 多段 flash kick, KD)
  KIM_HIENZAN_D: {
    startup: 7,
    active: 10,
    recovery: 30,
    damage: 140,
    hitstun: 26,
    blockstun: 20,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 14,
  },
  // 半月斬 qcb+B (half-moon kick, overhead)
  KIM_HANGETSU: {
    startup: 7,
    active: 12,
    recovery: 29,
    damage: 80,
    hitstun: 19,
    blockstun: 17,
    pushback: 5,
    hitLevel: "HIGH" as const,
    knockdown: true,
  },
  // 半月斬 qcb+D (强版, slower overhead)
  KIM_HANGETSU_D: {
    startup: 9,
    active: 14,
    recovery: 31,
    damage: 110,
    hitstun: 22,
    blockstun: 19,
    pushback: 6,
    hitLevel: "HIGH" as const,
    knockdown: true,
  },
  // 覇気蹴り f+B (axe kick, LOW hitlevel)
  KIM_HAKI: {
    startup: 9,
    active: 5,
    recovery: 20,
    damage: 65,
    hitstun: 19,
    blockstun: 17,
    pushback: 3,
    hitLevel: "LOW" as const,
    knockdown: false,
  },
  // 飛翔脚 (flash kick cancel, very fast)
  KIM_HISHOU: {
    startup: 2,
    active: 8,
    recovery: 14,
    damage: 70,
    hitstun: 19,
    blockstun: 17,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 三連蹴り 1段 (triple kick, multi-hit)
  KIM_SANREN: {
    startup: 8,
    active: 14,
    recovery: 24,
    damage: 60,
    hitstun: 19,
    blockstun: 17,
    pushback: 3,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 三連蹴り 追加 (2nd+3rd hits)
  KIM_SANREN_2: {
    startup: 10,
    active: 12,
    recovery: 22,
    damage: 55,
    hitstun: 19,
    blockstun: 17,
    pushback: 3,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // ── DM超必杀技 (Kim) ── KOF2002UM calibrated
  // 鳳凰脚 (Hou'ou Kyaku, rushing DM)
  DM_YATAGARASU: {
    startup: 8,
    active: 16,
    recovery: 42,
    damage: 200,
    hitstun: 0,
    blockstun: 21,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 18,
  },
  // 鳳凰天舞脚 (air/ground DM phoenix kick)
  DM_PHOENIX_KICK: {
    startup: 8,
    active: 13,
    recovery: 43,
    damage: 200,
    hitstun: 0,
    blockstun: 21,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 17,
  },
  DM_PHOENIX_HITEN: {
    startup: 8,
    active: 5,
    recovery: 30,
    damage: 180,
    hitstun: 0,
    blockstun: 21,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 14,
  },
  // ── 坂崎亮必杀技 (Ryo Sakazaki) ── KOF2002UM calibrated
  // 虎煌拳 qcf+A (Ko'ou Ken, projectile)
  RYO_KOOU: {
    startup: 12,
    active: 18,
    recovery: 34,
    damage: 75,
    hitstun: 28,
    blockstun: 26,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  // 虎煌拳 qcf+C (Ko'ou Ken, strong projectile)
  RYO_KOOU_C: {
    startup: 13,
    active: 20,
    recovery: 32,
    damage: 105,
    hitstun: 30,
    blockstun: 28,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 10,
  },
  // 虎煌拳 重版 qcf+D (Ko'ou Ken D, heavy projectile) — KOF2002UM 校准数据
  RYO_KOOUKEN_D: {
    startup: 15,
    active: 22,
    recovery: 30,
    damage: 120,
    hitstun: 32,
    blockstun: 30,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 12,
  },
  // 虎煌 dp+A (Kohou, weak DP, KD)
  RYO_KO_HOU: {
    startup: 5,
    active: 5,
    recovery: 25,
    damage: 80,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  // 虎煌 dp+C (Kohou, strong DP, KD)
  RYO_KO_HOU_C: {
    startup: 7,
    active: 10,
    recovery: 30,
    damage: 140,
    hitstun: 28,
    blockstun: 22,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 14,
  },
  // 飛燕疾風脚 qcb+K (Hien Shippu Kyaku, flying kick)
  RYO_HIEN: {
    startup: 10,
    active: 8,
    recovery: 22,
    damage: 95,
    hitstun: 24,
    blockstun: 20,
    pushback: 6,
    hitLevel: "HIGH" as const,
    knockdown: true,
  },
  // 暢連拳 hcb+P (Zanretsu Ken, multi-punch)
  RYO_HAOU: {
    startup: 10,
    active: 12,
    recovery: 22,
    damage: 80,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // DM 霸王翔吼拳 (Haoh Shoukou Ken, projectile DM)
  DM_TEN_HA_OU: {
    startup: 18,
    active: 10,
    recovery: 35,
    damage: 200,
    hitstun: 0,
    blockstun: 22,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 18,
  },
  // DM 龍虎乱舞 (Ryuko Ranbu, rushing DM)
  DM_RYUKO_RANBU: {
    startup: 8,
    active: 10,
    recovery: 38,
    damage: 220,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  // ── 莉安娜必杀技 (Leona Heidern) ── KOF2002UM 校准数据
  LEONA_MOON_SLASH: {
    startup: 5,
    active: 10,
    recovery: 28,
    damage: 80,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  LEONA_MOON_SLASH_C: {
    startup: 7,
    active: 14,
    recovery: 32,
    damage: 130,
    hitstun: 28,
    blockstun: 22,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 14,
  },
  LEONA_EAR_RING: {
    startup: 5,
    active: 5,
    recovery: 25,
    damage: 80,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 10,
  },
  LEONA_EAR_RING_C: {
    startup: 7,
    active: 10,
    recovery: 30,
    damage: 140,
    hitstun: 28,
    blockstun: 22,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 14,
  },
  LEONA_GRAND_SABER: {
    startup: 7,
    active: 8,
    recovery: 22,
    damage: 90,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  LEONA_BALTIC: {
    startup: 16,
    active: 18,
    recovery: 30,
    damage: 75,
    hitstun: 28,
    blockstun: 26,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  DM_V_SLASHER: {
    startup: 8,
    active: 8,
    recovery: 38,
    damage: 210,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  // ── 罗伯特必杀技 (Robert Garcia) ── KOF2002UM 校准数据
  // 龙撃拳 qcf+A (飞行道具)
  ROBERT_RYU_GEKI: {
    startup: 12,
    active: 22,
    recovery: 28,
    damage: 70,
    hitstun: 26,
    blockstun: 24,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  // 龙撃拳 qcf+C (飞行道具 强版)
  ROBERT_RYU_GEKI_C: {
    startup: 15,
    active: 25,
    recovery: 26,
    damage: 100,
    hitstun: 28,
    blockstun: 26,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 10,
  },
  // 龙牙 dp+A (DP 弱版)
  ROBERT_RYU_ZAN: {
    startup: 5,
    active: 6,
    recovery: 26,
    damage: 80,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  // 龙牙 dp+C (DP 强版)
  ROBERT_RYU_ZAN_C: {
    startup: 6,
    active: 10,
    recovery: 30,
    damage: 130,
    hitstun: 28,
    blockstun: 22,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 14,
  },
  // 飞燕龍神脚 空中 qcb+K (空中俯冲踢)
  ROBERT_HIEN_RYU_JIN: {
    startup: 8,
    active: 8,
    recovery: 18,
    damage: 85,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 幻影脚 hcf+B (多段踢)
  ROBERT_GENEI_KYAKU: {
    startup: 10,
    active: 10,
    recovery: 22,
    damage: 85,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "HIGH" as const,
    knockdown: false,
  },
  // 飞燕旋风脚 qcb+K (冲刺踢)
  ROBERT_HIEN_RYU_KYAKU: {
    startup: 12,
    active: 10,
    recovery: 22,
    damage: 95,
    hitstun: 24,
    blockstun: 20,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // 飞燕疾风脚 dp+B (DP 对空踢)
  ROBERT_HIEN_SHIPPU_KYAKU: {
    startup: 5,
    active: 8,
    recovery: 28,
    damage: 85,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 13,
  },
  // 飞燕疾风脚 dp+D (DP 对空踢 强版)
  ROBERT_HIEN_SHIPPU_KYAKU_D: {
    startup: 7,
    active: 12,
    recovery: 32,
    damage: 130,
    hitstun: 28,
    blockstun: 22,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  // 龙虎乱舞 DM qcf,qcf+P
  DM_RYU_KO_RYU: {
    startup: 8,
    active: 8,
    recovery: 36,
    damage: 220,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  // 霸王翔吼拳 DM f,hcf+P
  DM_HAOU_SHOKOU: {
    startup: 10,
    active: 10,
    recovery: 38,
    damage: 210,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 22,
  },
  // ── 不知火舞必杀技 (Mai Shiranui) ── KOF2002UM 校准数据
  // 花蝶扇 qcf+A (飞行道具)
  MAI_KA_CHO_SEN: {
    startup: 13,
    active: 20,
    recovery: 30,
    damage: 70,
    hitstun: 28,
    blockstun: 26,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  // 花蝶扇 qcf+C (飞行道具 强版)
  MAI_KA_CHO_SEN_C: {
    startup: 16,
    active: 24,
    recovery: 28,
    damage: 100,
    hitstun: 30,
    blockstun: 28,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 10,
  },
  // 飞翔龍炎陣 dp+K (DP)
  MAI_HISHO_RYU_EN_JIN: {
    startup: 6,
    active: 6,
    recovery: 26,
    damage: 85,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  // 龍炎舞 qcb+P (近距离火焰)
  MAI_RYU_EN_BU: {
    startup: 10,
    active: 8,
    recovery: 22,
    damage: 85,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // ムササビの舞 空中 qcb+P (空中俯冲扇)
  MAI_MUSASABI: {
    startup: 12,
    active: 10,
    recovery: 20,
    damage: 80,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "HIGH" as const,
    knockdown: true,
  },
  // ムササビの舞 重版 空中 qcb+K (空中俯冲扇 重版, 高伤害) — KOF2002UM 校准数据
  MAI_MUSASABI_D: {
    startup: 14,
    active: 12,
    recovery: 22,
    damage: 95,
    hitstun: 24,
    blockstun: 20,
    pushback: 6,
    hitLevel: "HIGH" as const,
    knockdown: true,
  },
  // 必殺忍蜂 ←↙↓↘→+K (冲刺攻击)
  MAI_HISSATSU_SHINOBI: {
    startup: 8,
    active: 8,
    recovery: 24,
    damage: 90,
    hitstun: 24,
    blockstun: 20,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 花嵐 DM qcf,qcf+K
  DM_HAKA_OTOSHI: {
    startup: 10,
    active: 12,
    recovery: 40,
    damage: 210,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  // 超必殺忍蜂 DM qcb,qcb+K
  DM_CHOU_HISSATSU: {
    startup: 8,
    active: 14,
    recovery: 38,
    damage: 200,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 18,
  },
  // ── K' 必杀技 (K Dash) ── KOF2002UM calibrated
  // Ein Trigger qcf+A (standalone punch)
  KDASH_EINS: {
    startup: 10,
    active: 25,
    recovery: 18,
    damage: 60,
    hitstun: 14,
    blockstun: 12,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 5,
  },
  // Ein Trigger qcf+C (strong standalone punch)
  KDASH_EINS_C: {
    startup: 12,
    active: 30,
    recovery: 20,
    damage: 75,
    hitstun: 16,
    blockstun: 14,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 6,
  },
  // Second Shell qcf+A>K (followup kick from Ein Trigger)
  KDASH_SECOND_SHELL: {
    startup: 6,
    active: 8,
    recovery: 16,
    damage: 50,
    hitstun: 16,
    blockstun: 14,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // Second Spike qcf+A>D (low followup from Ein Trigger)
  KDASH_SECOND_SPIKE: {
    startup: 8,
    active: 6,
    recovery: 18,
    damage: 45,
    hitstun: 14,
    blockstun: 12,
    pushback: 3,
    hitLevel: "LOW" as const,
    knockdown: false,
  },
  // Crow Bites dp+A (DP, KD)
  KDASH_CROW: {
    startup: 5,
    active: 6,
    recovery: 22,
    damage: 70,
    hitstun: 18,
    blockstun: 14,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  // Crow Bites dp+C (strong DP, KD)
  KDASH_CROW_C: {
    startup: 6,
    active: 8,
    recovery: 26,
    damage: 90,
    hitstun: 20,
    blockstun: 16,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 14,
  },
  // Crow Bites dp+D (重版 DP, 多段上升, KD) — KOF2002UM 校准数据
  KDASH_CROW_BITE_D: {
    startup: 7,
    active: 10,
    recovery: 30,
    damage: 110,
    hitstun: 22,
    blockstun: 18,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 16,
  },
  // One Inch f+A (近距离特殊技, 快速短距打击) — KOF2002UM 校准数据
  KDASH_ONE_INCH: {
    startup: 8,
    active: 5,
    recovery: 18,
    damage: 65,
    hitstun: 18,
    blockstun: 14,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // Minute Spike qcb+K (jumping knee)
  KDASH_MINUTE: {
    startup: 14,
    active: 6,
    recovery: 18,
    damage: 65,
    hitstun: 16,
    blockstun: 14,
    pushback: 4,
    hitLevel: "HIGH" as const,
    knockdown: false,
  },
  // Narrow Spike qcb+K>d+K (followup slide)
  KDASH_NARROW: {
    startup: 8,
    active: 8,
    recovery: 16,
    damage: 55,
    hitstun: 14,
    blockstun: 12,
    pushback: 3,
    hitLevel: "LOW" as const,
    knockdown: true,
  },
  // DM Chain Drive qcf,qcf+P (rushing DM)
  DM_CHAIN_DRIVE: {
    startup: 10,
    active: 10,
    recovery: 38,
    damage: 200,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 18,
  },
  // DM Heat Drive qcf,qcf+K (projectile DM, slow startup)
  DM_HEAT_DRIVE: {
    startup: 22,
    active: 14,
    recovery: 40,
    damage: 210,
    hitstun: 0,
    blockstun: 22,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  // ── 库拉必杀技 (Kula Diamond) ── KOF2002UM 校准数据
  // Diamond Breath qcf+A (冰飞行道具)
  KULA_BREATH: {
    startup: 14,
    active: 20,
    recovery: 28,
    damage: 70,
    hitstun: 28,
    blockstun: 26,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  KULA_BREATH_C: {
    startup: 16,
    active: 24,
    recovery: 26,
    damage: 100,
    hitstun: 30,
    blockstun: 28,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 10,
  },
  KULA_SHELL: {
    startup: 10,
    active: 6,
    recovery: 20,
    damage: 65,
    hitstun: 20,
    blockstun: 16,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  KULA_SHELL_C: {
    startup: 12,
    active: 8,
    recovery: 24,
    damage: 85,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  KULA_LAY: {
    startup: 8,
    active: 10,
    recovery: 20,
    damage: 65,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "LOW" as const,
    knockdown: true,
  },
  KULA_EDGE: {
    startup: 6,
    active: 6,
    recovery: 22,
    damage: 80,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  DM_CHAIN_SHOT: {
    startup: 8,
    active: 10,
    recovery: 38,
    damage: 200,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  DM_FREEZE: {
    startup: 10,
    active: 12,
    recovery: 36,
    damage: 200,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  // ── SDM (Super Desperation Moves — MAX mode only) ──
  SDM_YATAGARASU: {
    startup: 6,
    active: 12,
    recovery: 38,
    damage: 310,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 28,
  },
  SDM_POWER_GEYSER: {
    startup: 14,
    active: 20,
    recovery: 38,
    damage: 300,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 30,
  },
  SDM_PHOENIX_KICK: {
    startup: 6,
    active: 18,
    recovery: 32,
    damage: 290,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 25,
  },
  SDM_TEN_HA_OU: {
    startup: 10,
    active: 22,
    recovery: 35,
    damage: 280,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 25,
  },
  SDM_V_SLASHER: {
    startup: 8,
    active: 18,
    recovery: 38,
    damage: 310,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 30,
  },
  SDM_CHAIN_SHOT: {
    startup: 8,
    active: 15,
    recovery: 40,
    damage: 300,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 25,
  },
  SDM_FREEZE: {
    startup: 8,
    active: 12,
    recovery: 36,
    damage: 300,
    hitstun: 0,
    blockstun: 22,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 28,
  },
  // ── 罗伯特SDM (Robert Garcia) ── KOF2002UM 校准数据
  SDM_RYU_KO_RYU: {
    startup: 8,
    active: 12,
    recovery: 36,
    damage: 320,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 30,
  },
  SDM_HAOU_SHOKOU: {
    startup: 10,
    active: 14,
    recovery: 38,
    damage: 310,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 32,
  },
  // ── 不知火舞SDM (Mai Shiranui) ── KOF2002UM 校准数据
  SDM_HAKA_OTOSHI: {
    startup: 8,
    active: 15,
    recovery: 40,
    damage: 310,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 28,
  },
  // ── 雅典娜命令通常技 (Athena Asamiya) ──
  ATHENA_PHOENIX_REFLECT: {
    startup: 16,
    active: 4,
    recovery: 20,
    damage: 45,
    hitstun: 19,
    blockstun: 17,
    pushback: 3,
    hitLevel: "HIGH" as const,
    knockdown: false,
  },
  ATHENA_LOW_B: {
    startup: 8,
    active: 4,
    recovery: 20,
    damage: 40,
    hitstun: 18,
    blockstun: 15,
    pushback: 2,
    hitLevel: "LOW" as const,
    knockdown: false,
  },
  ATHENA_AIR_B: {
    startup: 7,
    active: 6,
    recovery: 3,
    damage: 42,
    hitstun: 19,
    blockstun: 17,
    pushback: 4,
    hitLevel: "HIGH" as const,
    knockdown: false,
  },
  // ── 雅典娜必杀技 (Athena Asamiya) ── KOF2002UM 校准数据
  ATHENA_PSYCHO_BALL: {
    startup: 12,
    active: 22,
    recovery: 32,
    damage: 70,
    hitstun: 28,
    blockstun: 26,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  ATHENA_PSYCHO_BALL_C: {
    startup: 14,
    active: 26,
    recovery: 30,
    damage: 100,
    hitstun: 30,
    blockstun: 28,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 10,
  },
  ATHENA_PSYCHO_SWORD: {
    startup: 5,
    active: 5,
    recovery: 26,
    damage: 80,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  ATHENA_PSYCHO_SWORD_C: {
    startup: 7,
    active: 10,
    recovery: 30,
    damage: 140,
    hitstun: 28,
    blockstun: 22,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 14,
  },
  ATHENA_PHOENIX_ARROW: {
    startup: 6,
    active: 10,
    recovery: 18,
    damage: 75,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // ── 雅典娜DM (Athena) ──
  DM_SHINING_CRYSTAL_BIT: {
    startup: 8,
    active: 12,
    recovery: 40,
    damage: 200,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 18,
  },
  // ── 雅典娜SDM (Athena) ──
  SDM_SHINING_CRYSTAL_BIT: {
    startup: 8,
    active: 18,
    recovery: 38,
    damage: 300,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 30,
  },
  // ── 克拉克必杀技 (Clark Still) ── KOF2002UM 校准数据
  // Super Argentine Backbreaker hcf+A (指令投)
  CLARK_ARGENTINE: {
    startup: 3,
    active: 2,
    recovery: 30,
    damage: 120,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // Super Argentine Backbreaker hcf+C (指令投 强版)
  CLARK_ARGENTINE_C: {
    startup: 4,
    active: 2,
    recovery: 34,
    damage: 150,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // Flash Elbow dp+P (追击肘)
  CLARK_FLASH_ELBOW: {
    startup: 7,
    active: 5,
    recovery: 20,
    damage: 65,
    hitstun: 20,
    blockstun: 16,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // Napalm Stretch dp+K (对空捕捉)
  CLARK_NAPALM_STRETCH: {
    startup: 6,
    active: 6,
    recovery: 28,
    damage: 95,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // Mount Tackle hcf+K (冲刺投)
  CLARK_MOUNT_TACKLE: {
    startup: 10,
    active: 8,
    recovery: 26,
    damage: 100,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // Franken Steiner close hcf+K (近身投)
  CLARK_VULCAN: {
    startup: 5,
    active: 8,
    recovery: 24,
    damage: 80,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // ── 克拉克DM/SDM (Clark) ──
  // Ultra Argentine Backbreaker DM
  DM_ARGENTINE_DM: {
    startup: 5,
    active: 4,
    recovery: 40,
    damage: 220,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  SDM_ARGENTINE_DM: {
    startup: 5,
    active: 8,
    recovery: 38,
    damage: 320,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 30,
  },
  // ── 拉尔夫必杀技 (Ralf Jones) ── KOF2002UM 校准数据
  // Vulcan Punch qcf+A (机枪拳 多段)
  RALF_VULCAN: {
    startup: 10,
    active: 14,
    recovery: 24,
    damage: 60,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  // Vulcan Punch qcf+C (机枪拳 强版)
  RALF_VULCAN_C: {
    startup: 12,
    active: 20,
    recovery: 28,
    damage: 100,
    hitstun: 26,
    blockstun: 22,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 12,
  },
  // Bareback Vulcan Punch hcf+P (指令投)
  RALF_BACKBREAKER: {
    startup: 4,
    active: 2,
    recovery: 30,
    damage: 130,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // Gatling Attack charge b,f+P (冲刺攻击)
  RALF_GATLING: {
    startup: 12,
    active: 10,
    recovery: 26,
    damage: 90,
    hitstun: 24,
    blockstun: 20,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // Ralf Kick qcb+K (飞踢)
  RALF_KICK: {
    startup: 14,
    active: 8,
    recovery: 22,
    damage: 85,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // Galactica Phantom DM charge b,f+P
  DM_GALACTICA_PHANTOM: {
    startup: 12,
    active: 10,
    recovery: 40,
    damage: 230,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 22,
  },
  SDM_GALACTICA_PHANTOM: {
    startup: 10,
    active: 16,
    recovery: 38,
    damage: 340,
    hitstun: 0,
    blockstun: 21,
    pushback: 14,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 32,
  },
  // ── 乔·东必杀技 (Joe Higashi) ── KOF2002UM 校准数据
  // Hurricane Upper qcf+A (龙卷风飞行道具)
  JOE_HURRICANE: {
    startup: 13,
    active: 22,
    recovery: 30,
    damage: 75,
    hitstun: 28,
    blockstun: 26,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  // Hurricane Upper qcf+C (龙卷风 强版)
  JOE_HURRICANE_C: {
    startup: 15,
    active: 28,
    recovery: 28,
    damage: 110,
    hitstun: 30,
    blockstun: 28,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 10,
  },
  // Tiger Kick dp+B (上升膝击 DP)
  JOE_TIGER_KICK: {
    startup: 5,
    active: 6,
    recovery: 26,
    damage: 85,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  // Tiger Kick dp+D (上升膝击 DP 强版)
  JOE_TIGER_KICK_D: {
    startup: 6,
    active: 10,
    recovery: 30,
    damage: 135,
    hitstun: 28,
    blockstun: 22,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 14,
  },
  // 爆裂拳 qcf+P连打 (多段拳击)
  JOE_BAKURETSUKEN: {
    startup: 9,
    active: 14,
    recovery: 22,
    damage: 70,
    hitstun: 22,
    blockstun: 18,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // Slash Kick qcb+K (冲刺踢)
  JOE_OUGON_KAKATO: {
    startup: 12,
    active: 8,
    recovery: 22,
    damage: 90,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 黄金之踵 ←↙↓↘→+K (黄金脚跟落地)
  JOE_SLASH_KICK: {
    startup: 10,
    active: 10,
    recovery: 24,
    damage: 80,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // Screw Upper DM qcf,qcf+P
  DM_SCREW_UPPER: {
    startup: 10,
    active: 16,
    recovery: 40,
    damage: 210,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  SDM_SCREW_UPPER: {
    startup: 8,
    active: 24,
    recovery: 38,
    damage: 310,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 30,
  },
  // ── 安迪必杀技 (Andy Bogard) ── KOF2002UM 校准数据
  // 飛翔拳 qcf+A (飞行道具)
  ANDY_HISHOU_KEN: {
    startup: 13,
    active: 20,
    recovery: 30,
    damage: 70,
    hitstun: 28,
    blockstun: 26,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  // 飛翔拳 qcf+C (飞行道具 强版)
  ANDY_HISHOU_KEN_C: {
    startup: 15,
    active: 24,
    recovery: 28,
    damage: 100,
    hitstun: 30,
    blockstun: 28,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 10,
  },
  // 昇龍弾 dp+A (DP 弱版)
  ANDY_SHOURYUU_DAN: {
    startup: 5,
    active: 6,
    recovery: 26,
    damage: 85,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 10,
  },
  // 昇龍弾 dp+C (DP 强版)
  ANDY_SHOURYUU_DAN_C: {
    startup: 7,
    active: 10,
    recovery: 30,
    damage: 140,
    hitstun: 28,
    blockstun: 22,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 14,
  },
  // 斬影拳 qcb+P (影肘突进)
  ANDY_ZANEI_RYUSEI_KEN: {
    startup: 10,
    active: 8,
    recovery: 22,
    damage: 90,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 斬影拳 qcb+K (影肘突进 强版)
  ANDY_ZANEI_RYUSEI_KEN_D: {
    startup: 12,
    active: 12,
    recovery: 26,
    damage: 115,
    hitstun: 26,
    blockstun: 20,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 空破弾 ←↙↓↘→+K (冲刺肘)
  ANDY_GEKI_HISHOU_KEN: {
    startup: 8,
    active: 8,
    recovery: 20,
    damage: 80,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 上顎 qcb+K (分裂踢)
  ANDY_KUHADAN: {
    startup: 12,
    active: 8,
    recovery: 22,
    damage: 85,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 超裂破弾 DM qcb,qcb+P
  DM_CHO_REPPA_DAN: {
    startup: 8,
    active: 14,
    recovery: 38,
    damage: 210,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  SDM_CHO_REPPA_DAN: {
    startup: 8,
    active: 22,
    recovery: 36,
    damage: 310,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 30,
  },
  // ── 比利必杀技 (Billy Kane) ── KOF2002UM 校准数据
  BILLY_SANSETSU_KON: {
    startup: 10,
    active: 8,
    recovery: 22,
    damage: 65,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  BILLY_SANSETSU_KON_C: {
    startup: 12,
    active: 12,
    recovery: 26,
    damage: 90,
    hitstun: 24,
    blockstun: 20,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  BILLY_SENPU_KON: {
    startup: 5,
    active: 6,
    recovery: 24,
    damage: 80,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  BILLY_SENPU_KON_C: {
    startup: 7,
    active: 10,
    recovery: 28,
    damage: 130,
    hitstun: 26,
    blockstun: 22,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 14,
  },
  BILLY_HIEN_ZAN: {
    startup: 10,
    active: 8,
    recovery: 20,
    damage: 75,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  BILLY_HIEN_ZAN_D: {
    startup: 12,
    active: 12,
    recovery: 24,
    damage: 100,
    hitstun: 24,
    blockstun: 20,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  DM_KAEN_SENPU_JIN: {
    startup: 10,
    active: 12,
    recovery: 40,
    damage: 200,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 18,
  },
  SDM_KAEN_SENPU_JIN: {
    startup: 8,
    active: 20,
    recovery: 38,
    damage: 300,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 28,
  },
  // ── 陈可汗必杀技 (Chang Koehan) ── KOF2002UM 校准数据
  CHANG_TEKKYUU_KAITEN: {
    startup: 10,
    active: 14,
    recovery: 26,
    damage: 65,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  CHANG_TEKKYUU_KAITEN_C: {
    startup: 12,
    active: 20,
    recovery: 30,
    damage: 100,
    hitstun: 26,
    blockstun: 22,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 12,
  },
  CHANG_TEKKYUU_FASSHU: {
    startup: 14,
    active: 8,
    recovery: 28,
    damage: 90,
    hitstun: 24,
    blockstun: 20,
    pushback: 7,
    hitLevel: "HIGH" as const,
    knockdown: true,
    chipDamage: 10,
  },
  CHANG_TEKKYUU_HIEN_ZAN: {
    startup: 8,
    active: 10,
    recovery: 24,
    damage: 85,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  DM_TEKKYUU_DAI_BOUSOU: {
    startup: 10,
    active: 12,
    recovery: 42,
    damage: 220,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  SDM_TEKKYUU_DAI_BOUSOU: {
    startup: 8,
    active: 18,
    recovery: 40,
    damage: 320,
    hitstun: 0,
    blockstun: 21,
    pushback: 14,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 32,
  },
  // ── 蔡宝奇命令通常技 (Choi Bounge) ── KOF2002UM 校准数据
  CHOI_SOUTEN_MEKKYAKU: {
    startup: 12,
    active: 5,
    recovery: 18,
    damage: 48,
    hitstun: 19,
    blockstun: 17,
    pushback: 3,
    hitLevel: "HIGH" as const,
    knockdown: false,
  },
  CHOI_SAN_REN_GEKI: {
    startup: 8,
    active: 5,
    recovery: 16,
    damage: 40,
    hitstun: 18,
    blockstun: 15,
    pushback: 2,
    hitLevel: "LOW" as const,
    knockdown: false,
  },
  // ── 蔡宝奇必杀技 (Choi Bounge) ── KOF2002UM 校准数据
  CHOI_HISHOU_KYAKU: {
    startup: 8,
    active: 8,
    recovery: 18,
    damage: 65,
    hitstun: 20,
    blockstun: 16,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  CHOI_HISHOU_KYAKU_C: {
    startup: 10,
    active: 12,
    recovery: 22,
    damage: 95,
    hitstun: 24,
    blockstun: 20,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  CHOI_KAITEN_HIEN_ZAN: {
    startup: 5,
    active: 6,
    recovery: 22,
    damage: 75,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 8,
  },
  CHOI_KAITEN_HIEN_ZAN_C: {
    startup: 7,
    active: 10,
    recovery: 28,
    damage: 120,
    hitstun: 26,
    blockstun: 22,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 12,
  },
  CHOI_HOUYOKU_TENSHIN: {
    startup: 6,
    active: 10,
    recovery: 24,
    damage: 90,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  // ── 蔡宝奇DM/SDM (Choi) ──
  DM_SHIN_CHOU_HOUYOKU: {
    startup: 8,
    active: 12,
    recovery: 40,
    damage: 200,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 18,
  },
  SDM_SHIN_CHOU_HOUYOKU: {
    startup: 8,
    active: 18,
    recovery: 38,
    damage: 300,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 28,
  },
  // ── 玛卓命令通常技 (Mature) ── KOF2002UM 校准数据
  MATURE_DESPAIR: {
    startup: 14,
    active: 4,
    recovery: 19,
    damage: 45,
    hitstun: 19,
    blockstun: 16,
    pushback: 3,
    hitLevel: "HIGH" as const,
    knockdown: false,
  },
  MATURE_JAB: {
    startup: 8,
    active: 4,
    recovery: 21,
    damage: 38,
    hitstun: 18,
    blockstun: 15,
    pushback: 2,
    hitLevel: "LOW" as const,
    knockdown: false,
  },
  // ── 玛卓必杀技 (Mature) ── KOF2002UM 校准数据
  MATURE_MASSACRE: {
    startup: 8,
    active: 8,
    recovery: 22,
    damage: 75,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 9,
  },
  MATURE_MASSACRE_C: {
    startup: 10,
    active: 12,
    recovery: 26,
    damage: 110,
    hitstun: 26,
    blockstun: 22,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 12,
  },
  MATURE_HEAVENS_GATE: {
    startup: 14,
    active: 6,
    recovery: 26,
    damage: 85,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "HIGH" as const,
    knockdown: true,
    chipDamage: 10,
  },
  MATURE_ECSTASY: {
    startup: 5,
    active: 6,
    recovery: 26,
    damage: 85,
    hitstun: 22,
    blockstun: 18,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  // ── 玛卓DM (Mature) ── KOF2002UM 校准数据
  DM_NOCTURNAL_LIGHT: {
    startup: 8,
    active: 14,
    recovery: 38,
    damage: 200,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 18,
  },
  // ── 玛卓SDM (Mature) ── KOF2002UM 校准数据
  SDM_NOCTURNAL_LIGHT: {
    startup: 8,
    active: 20,
    recovery: 36,
    damage: 300,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 28,
  },
  // ── 大门五郎必杀技 (Yashiro Nanakase) ── KOF2002UM 校准数据
  YASHIRO_SHUU_WANI: {
    startup: 12,
    active: 4,
    recovery: 20,
    damage: 55,
    hitstun: 16,
    blockstun: 14,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  YASHIRO_JUU_ZUTSU: {
    startup: 16,
    active: 4,
    recovery: 22,
    damage: 55,
    hitstun: 18,
    blockstun: 15,
    pushback: 4,
    hitLevel: "HIGH" as const,
    knockdown: false,
  },
  YASHIRO_UPPER_DU: {
    startup: 6,
    active: 10,
    recovery: 24,
    damage: 80,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 8,
  },
  YASHIRO_UPPER_DU_C: {
    startup: 7,
    active: 16,
    recovery: 28,
    damage: 120,
    hitstun: 26,
    blockstun: 22,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 12,
  },
  YASHIRO_NIRAAI: {
    startup: 14,
    active: 6,
    recovery: 26,
    damage: 100,
    hitstun: 24,
    blockstun: 20,
    pushback: 6,
    hitLevel: "HIGH" as const,
    knockdown: true,
    chipDamage: 10,
  },
  YASHIRO_MUSATSU: {
    startup: 14,
    active: 6,
    recovery: 28,
    damage: 90,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "LOW" as const,
    knockdown: true,
    chipDamage: 8,
  },
  // ── 大门五郎DM/SDM (Yashiro) ── KOF2002UM 校准数据
  DM_ARMAGEDDON_BUSTERS: {
    startup: 10,
    active: 10,
    recovery: 42,
    damage: 230,
    hitstun: 0,
    blockstun: 21,
    pushback: 14,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 22,
  },
  SDM_ARMAGEDDON_BUSTERS: {
    startup: 8,
    active: 16,
    recovery: 40,
    damage: 330,
    hitstun: 0,
    blockstun: 21,
    pushback: 16,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 32,
  },
  // ── 克里斯命令通常技 (Chris) ── KOF2002UM 校准数据
  CHRIS_MAKASHIPPO: {
    startup: 10,
    active: 4,
    recovery: 18,
    damage: 38,
    hitstun: 16,
    blockstun: 14,
    pushback: 3,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  CHRIS_KAZAGURUMA: {
    startup: 8,
    active: 4,
    recovery: 20,
    damage: 35,
    hitstun: 14,
    blockstun: 12,
    pushback: 2,
    hitLevel: "LOW" as const,
    knockdown: false,
  },
  // ── 克里斯必杀技 (Chris) ── KOF2002UM 校准数据
  CHRIS_SHOT_WEAVE: {
    startup: 7,
    active: 4,
    recovery: 18,
    damage: 55,
    hitstun: 16,
    blockstun: 14,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  CHRIS_SHOT_WEAVE_C: {
    startup: 10,
    active: 6,
    recovery: 22,
    damage: 72,
    hitstun: 20,
    blockstun: 16,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  CHRIS_TWISTER_DRIVE: {
    startup: 12,
    active: 8,
    recovery: 28,
    damage: 78,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  CHRIS_SCRAMBLE_DASH: {
    startup: 8,
    active: 6,
    recovery: 24,
    damage: 60,
    hitstun: 18,
    blockstun: 15,
    pushback: 4,
    hitLevel: "LOW" as const,
    knockdown: false,
  },
  // ── 克里斯DM (Chris) ── KOF2002UM 校准数据
  DM_CHAIN_SLIDE_TOUCH: {
    startup: 7,
    active: 14,
    recovery: 36,
    damage: 200,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 18,
  },
  // ── 克里斯SDM (Chris) ── KOF2002UM 校准数据
  SDM_CHAIN_SLIDE_TOUCH: {
    startup: 5,
    active: 20,
    recovery: 38,
    damage: 300,
    hitstun: 0,
    blockstun: 22,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 28,
  },
  // ── 夏尔美命令通常技 (Shermie) ── KOF2002UM 校准数据
  SHERMIE_STAND: {
    startup: 14,
    active: 4,
    recovery: 20,
    damage: 42,
    hitstun: 18,
    blockstun: 15,
    pushback: 3,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  SHERMIE_CLASH: {
    startup: 8,
    active: 4,
    recovery: 22,
    damage: 38,
    hitstun: 16,
    blockstun: 14,
    pushback: 2,
    hitLevel: "LOW" as const,
    knockdown: false,
  },
  // ── 夏尔美必杀技 (Shermie) ── KOF2002UM 校准数据
  SHERMIE_SHOOT: {
    startup: 10,
    active: 6,
    recovery: 24,
    damage: 70,
    hitstun: 20,
    blockstun: 17,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  SHERMIE_SHOOT_C: {
    startup: 14,
    active: 10,
    recovery: 28,
    damage: 90,
    hitstun: 24,
    blockstun: 20,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 12,
  },
  SHERMIE_CARNIVAL: {
    startup: 12,
    active: 5,
    recovery: 26,
    damage: 75,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 10,
  },
  SHERMIE_AXLE_SPIN: {
    startup: 12,
    active: 6,
    recovery: 28,
    damage: 68,
    hitstun: 20,
    blockstun: 16,
    pushback: 5,
    hitLevel: "LOW" as const,
    knockdown: true,
    chipDamage: 8,
  },
  // ── 夏尔美DM/SDM (Shermie) ── KOF2002UM 校准数据
  DM_SHERMIE_CARNIVAL: {
    startup: 8,
    active: 16,
    recovery: 38,
    damage: 200,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  SDM_SHERMIE_CARNIVAL: {
    startup: 6,
    active: 22,
    recovery: 40,
    damage: 310,
    hitstun: 0,
    blockstun: 21,
    pushback: 14,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 30,
  },
  // ── 薇丝命令通常技 (Vice) ── KOF2002UM 校准数据
  VICE_MONSTROSITY: {
    startup: 10,
    active: 4,
    recovery: 20,
    damage: 42,
    hitstun: 18,
    blockstun: 15,
    pushback: 3,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  VICE_OVERKILL: {
    startup: 7,
    active: 4,
    recovery: 22,
    damage: 38,
    hitstun: 16,
    blockstun: 14,
    pushback: 2,
    hitLevel: "LOW" as const,
    knockdown: false,
  },
  // ── 薇丝必杀技 (Vice) ── KOF2002UM 校准数据
  VICE_OUTRAGE: {
    startup: 9,
    active: 6,
    recovery: 22,
    damage: 68,
    hitstun: 20,
    blockstun: 16,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  VICE_OUTRAGE_C: {
    startup: 12,
    active: 8,
    recovery: 26,
    damage: 85,
    hitstun: 22,
    blockstun: 18,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 10,
  },
  // Black End hcf+K (指令投)
  VICE_BLACK_END: {
    startup: 5,
    active: 3,
    recovery: 28,
    damage: 75,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  VICE_MAYHEM: {
    startup: 10,
    active: 5,
    recovery: 26,
    damage: 72,
    hitstun: 20,
    blockstun: 16,
    pushback: 5,
    hitLevel: "LOW" as const,
    knockdown: true,
    chipDamage: 8,
  },
  // ── 薇丝DM/SDM (Vice) ── KOF2002UM 校准数据
  // Negative Gain hcf,hcf+K (指令投 DM)
  DM_NEGATIVE_GAIN: {
    startup: 4,
    active: 4,
    recovery: 40,
    damage: 210,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  }, // Negative Gain SDM (指令投 SDM)
  SDM_NEGATIVE_GAIN: {
    startup: 4,
    active: 8,
    recovery: 38,
    damage: 320,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 30,
  }, // ── 布鲁·玛丽命令通常技 (Blue Mary) ── KOF2002UM 校准数据
  MARY_HAMMER_PUNCH: {
    startup: 10,
    active: 4,
    recovery: 20,
    damage: 42,
    hitstun: 18,
    blockstun: 15,
    pushback: 3,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  MARY_DOUBLE_ROLLING: {
    startup: 8,
    active: 4,
    recovery: 22,
    damage: 38,
    hitstun: 16,
    blockstun: 14,
    pushback: 2,
    hitLevel: "LOW" as const,
    knockdown: false,
  },
  // ── 布鲁·玛丽必杀技 (Blue Mary) ── KOF2002UM 校准数据
  MARY_STRAIGHT_SLICER: {
    startup: 9,
    active: 6,
    recovery: 22,
    damage: 68,
    hitstun: 20,
    blockstun: 16,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  MARY_STRAIGHT_SLICER_C: {
    startup: 12,
    active: 8,
    recovery: 26,
    damage: 85,
    hitstun: 22,
    blockstun: 18,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 10,
  },
  // Backdrop Real hcf+K close (指令投)
  MARY_BACKDROP_REAL: {
    startup: 5,
    active: 3,
    recovery: 24,
    damage: 72,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
  }, // Spider hcb+P close (指令投)
  MARY_SPIDER: {
    startup: 5,
    active: 3,
    recovery: 28,
    damage: 75,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
  }, // ── 布鲁·玛丽DM/SDM (Blue Mary) ── KOF2002UM 校准数据
  // Mary Typhoon DM (指令投 DM)
  DM_MARY_TYPHOON: {
    startup: 5,
    active: 6,
    recovery: 40,
    damage: 200,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  }, // Mary Typhoon SDM (指令投 SDM)
  SDM_MARY_TYPHOON: {
    startup: 5,
    active: 10,
    recovery: 38,
    damage: 310,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 30,
  }, // ── 李香绯命令通常技 (Li Xiangfei) ── KOF2002UM 校准数据
  XIANGFEI_KYU_HO: {
    startup: 7,
    active: 4,
    recovery: 18,
    damage: 38,
    hitstun: 16,
    blockstun: 14,
    pushback: 3,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  XIANGFEI_KAKU_DA: {
    startup: 6,
    active: 4,
    recovery: 20,
    damage: 35,
    hitstun: 14,
    blockstun: 12,
    pushback: 2,
    hitLevel: "LOW" as const,
    knockdown: false,
  },
  // ── 李香绯必杀技 (Li Xiangfei) ── KOF2002UM 校准数据
  XIANGFEI_NANPA: {
    startup: 5,
    active: 5,
    recovery: 18,
    damage: 58,
    hitstun: 18,
    blockstun: 14,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  XIANGFEI_NANPA_C: {
    startup: 7,
    active: 8,
    recovery: 24,
    damage: 78,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  XIANGFEI_TENPATSU: {
    startup: 9,
    active: 5,
    recovery: 26,
    damage: 70,
    hitstun: 20,
    blockstun: 16,
    pushback: 5,
    hitLevel: "HIGH" as const,
    knockdown: true,
    chipDamage: 8,
  },
  XIANGFEI_MAHO_HISHA: {
    startup: 8,
    active: 6,
    recovery: 24,
    damage: 68,
    hitstun: 18,
    blockstun: 14,
    pushback: 5,
    hitLevel: "LOW" as const,
    knockdown: true,
    chipDamage: 8,
  },
  // ── 李香绯DM (Li Xiangfei) ── KOF2002UM 校准数据
  DM_CHO_KA_RINGA: {
    startup: 7,
    active: 14,
    recovery: 36,
    damage: 190,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  // ── 李香绯SDM (Li Xiangfei) ── KOF2002UM 校准数据
  SDM_CHO_KA_RINGA: {
    startup: 5,
    active: 20,
    recovery: 38,
    damage: 300,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 30,
  },
  // ── 山崎龙二命令通常技 (Yamazaki) ── KOF2002UM 校准数据
  YAMAZAKI_SASHI: {
    startup: 12,
    active: 4,
    recovery: 22,
    damage: 45,
    hitstun: 18,
    blockstun: 16,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  YAMAZAKI_BOKKAI: {
    startup: 8,
    active: 4,
    recovery: 24,
    damage: 40,
    hitstun: 16,
    blockstun: 14,
    pushback: 3,
    hitLevel: "LOW" as const,
    knockdown: false,
  },
  // ── 山崎龙二必杀技 (Yamazaki) ── KOF2002UM 校准数据
  YAMAZAKI_SNAKE_ARM: {
    startup: 7,
    active: 6,
    recovery: 20,
    damage: 65,
    hitstun: 20,
    blockstun: 16,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  YAMAZAKI_SNAKE_ARM_C: {
    startup: 10,
    active: 10,
    recovery: 26,
    damage: 88,
    hitstun: 24,
    blockstun: 20,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 12,
  },
  YAMAZAKI_SANDSTORM: {
    startup: 14,
    active: 5,
    recovery: 28,
    damage: 78,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "HIGH" as const,
    knockdown: true,
    chipDamage: 10,
  },
  YAMAZAKI_BAI_GA_SE: {
    startup: 8,
    active: 6,
    recovery: 24,
    damage: 72,
    hitstun: 20,
    blockstun: 16,
    pushback: 5,
    hitLevel: "LOW" as const,
    knockdown: true,
    chipDamage: 8,
  },
  // ── 山崎龙二DM (Yamazaki) ── KOF2002UM 校准数据
  DM_GUILLOTINE: {
    startup: 8,
    active: 14,
    recovery: 38,
    damage: 220,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 22,
  },
  // ── 山崎龙二SDM (Yamazaki) ── KOF2002UM 校准数据
  SDM_GUILLOTINE: {
    startup: 6,
    active: 20,
    recovery: 40,
    damage: 340,
    hitstun: 0,
    blockstun: 21,
    pushback: 14,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 32,
  },
  // ── 藤堂香澄命令通常技 (Kasumi Todoh) ── KOF2002UM 校准数据
  KASUMI_KOU_U: {
    startup: 10,
    active: 4,
    recovery: 18,
    damage: 40,
    hitstun: 16,
    blockstun: 14,
    pushback: 3,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  KASUMI_GESHIKI: {
    startup: 6,
    active: 4,
    recovery: 20,
    damage: 36,
    hitstun: 14,
    blockstun: 12,
    pushback: 2,
    hitLevel: "LOW" as const,
    knockdown: false,
  },
  // ── 藤堂香澄必杀技 (Kasumi Todoh) ── KOF2002UM 校准数据
  KASUMI_KOOU_KEN: {
    startup: 7,
    active: 6,
    recovery: 22,
    damage: 65,
    hitstun: 20,
    blockstun: 16,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  KASUMI_KOOU_KEN_C: {
    startup: 9,
    active: 8,
    recovery: 26,
    damage: 82,
    hitstun: 22,
    blockstun: 18,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 10,
  },
  KASUMI_KASANE_ATE: {
    startup: 8,
    active: 5,
    recovery: 24,
    damage: 70,
    hitstun: 20,
    blockstun: 16,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  KASUMI_MUKIGENZAN: {
    startup: 10,
    active: 6,
    recovery: 26,
    damage: 75,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "LOW" as const,
    knockdown: true,
    chipDamage: 10,
  },
  // ── 藤堂香澄DM (Kasumi Todoh) ── KOF2002UM 校准数据
  DM_CHO_MUKIGENZAN: {
    startup: 7,
    active: 14,
    recovery: 36,
    damage: 195,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  // ── 藤堂香澄SDM (Kasumi Todoh) ── KOF2002UM 校准数据
  SDM_CHO_MUKIGENZAN: {
    startup: 5,
    active: 20,
    recovery: 38,
    damage: 300,
    hitstun: 0,
    blockstun: 21,
    pushback: 14,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 30,
  },
} as const;
