/**
 * Terry Bogard frame data — extracted from frameDataTerryKim.ts
 * Dream Cancel Wiki KOF2002UM 校准数据
 */
export const TERRY_FRAME_DATA = {
  // ── 特瑞专属必杀技 (Terry Bogard) ── Dream Cancel Wiki KOF2002UM 校准数据
  // Power Wave qcf+A (地面波)
  TERRY_POWER_WAVE: {
    startup: 12,
    active: 20,
    recovery: 32,
    damage: 70,
    hitstun: 27,
    blockstun: 25,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  // Round Wave qcf+C (原地波, 可取消)
  TERRY_ROUND_WAVE: {
    startup: 17,
    active: 10,
    recovery: 18,
    damage: 90,
    hitstun: 19,
    blockstun: 17,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  // Burn Knuckle qcb+A
  TERRY_BURN_KNUCKLE: {
    startup: 11,
    active: 10,
    recovery: 18,
    damage: 55,
    hitstun: 19,
    blockstun: 17,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 6,
  },
  // Burn Knuckle qcb+C (远距离)
  TERRY_BURN_KNUCKLE_C: {
    startup: 16,
    active: 14,
    recovery: 20,
    damage: 80,
    hitstun: 19,
    blockstun: 17,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 8,
  },
  // Burn Knuckle qcb+D (重版, 远距离高伤害)
  TERRY_BURN_KNUCKLE_D: {
    startup: 18,
    active: 14,
    recovery: 22,
    damage: 95,
    hitstun: 19,
    blockstun: 17,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  // Crack Shoot qcb+B (中段)
  TERRY_CRACK_SHOT: {
    startup: 11,
    active: 6,
    recovery: 21,
    damage: 50,
    hitstun: 19,
    blockstun: 17,
    pushback: 4,
    hitLevel: "HIGH" as const,
    knockdown: false,
  },
  // Crack Shoot qcb+D (中段)
  TERRY_CRACK_SHOT_D: {
    startup: 9,
    active: 8,
    recovery: 23,
    damage: 60,
    hitstun: 19,
    blockstun: 17,
    pushback: 5,
    hitLevel: "HIGH" as const,
    knockdown: false,
  },
  // Power Dunk dp+B (2段KD)
  TERRY_POWER_DUNK: {
    startup: 8,
    active: 8,
    recovery: 40,
    damage: 90,
    hitstun: 25,
    blockstun: 20,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 12,
  },
  // Power Dunk dp+D (2段KD)
  TERRY_POWER_DUNK_D: {
    startup: 10,
    active: 8,
    recovery: 44,
    damage: 110,
    hitstun: 25,
    blockstun: 20,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 14,
  },
  // Rising Tackle d,u+A (多段上升)
  TERRY_RISING_TACKLE: {
    startup: 6,
    active: 12,
    recovery: 35,
    damage: 90,
    hitstun: 25,
    blockstun: 20,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 12,
  },
  // Rising Tackle d,u+C (多段, 更多hits)
  TERRY_RISING_TACKLE_C: {
    startup: 6,
    active: 16,
    recovery: 39,
    damage: 130,
    hitstun: 28,
    blockstun: 22,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 14,
  },
  // Power Charge hcf+B/D (突进技)
  TERRY_POWER_CHARGE: {
    startup: 8,
    active: 6,
    recovery: 18,
    damage: 80,
    hitstun: 18,
    blockstun: 16,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // Back Knuckle f+A (指令通常技)
  TERRY_BACK_KNUCKLE: {
    startup: 5,
    active: 4,
    recovery: 12,
    damage: 45,
    hitstun: 12,
    blockstun: 10,
    pushback: 3,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // Hammer Punch f+C (中段技, overhead)
  TERRY_HAMMER_PUNCH: {
    startup: 12,
    active: 4,
    recovery: 22,
    damage: 65,
    hitstun: 18,
    blockstun: 16,
    pushback: 5,
    hitLevel: "HIGH" as const,
    knockdown: true,
  },
  // ── 特瑞DM ── Dream Cancel Wiki KOF2002UM 校准数据
  DM_POWER_GEYSER_A: {
    startup: 16,
    active: 10,
    recovery: 43,
    damage: 200,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  DM_POWER_GEYSER_C: {
    startup: 17,
    active: 11,
    recovery: 47,
    damage: 200,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  DM_HIGH_ANGLE_GEYSER_B: {
    startup: 7,
    active: 12,
    recovery: 33,
    damage: 190,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 18,
  },
  DM_HIGH_ANGLE_GEYSER_D: {
    startup: 11,
    active: 14,
    recovery: 37,
    damage: 190,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 18,
  },
  SDM_TRIPLE_GEYSER: {
    startup: 17,
    active: 22,
    recovery: 36,
    damage: 340,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 30,
  },
  // SDM Power Geyser EX (MAX版强化)
  SDM_POWER_GEYSER_EX: {
    startup: 10,
    active: 20,
    recovery: 38,
    damage: 300,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 35,
  },
  // DM别名 (used by combat system)
  DM_POWER_GEYSER: {
    startup: 17,
    active: 10,
    recovery: 43,
    damage: 220,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 22,
  },
  DM_HIGH_ANGLE_GEYSER: {
    startup: 6,
    active: 12,
    recovery: 33,
    damage: 200,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  // SDM High Angle Geyser (MAX版强化)
  SDM_HIGH_ANGLE_GEYSER: {
    startup: 7,
    active: 12,
    recovery: 38,
    damage: 280,
    hitstun: 0,
    blockstun: 24,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 24,
  },
} as const;
