/**
 * Terry Bogard + Kim Kaphwan frame data
 * Split from frameDataChars.ts
 *
 * 数据源: Dream Cancel Wiki KOF2002UM 校准数据
 */
export const TERRY_KIM_DATA = {
  // Power Wave qcf+A (地面波)
  TERRY_POWER_WAVE: {
    startup: 12,
    active: 20,
    recovery: 32,
    damage: 70,
    hitstun: 27,
    blockstun: 25,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  // Round Wave qcf+C (原地波, 可取消)
  TERRY_ROUND_WAVE: {
    startup: 17,
    active: 10,
    recovery: 18,
    damage: 90,
    hitstun: 19,
    blockstun: 17,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  // Burn Knuckle qcb+A
  TERRY_BURN_KNUCKLE: {
    startup: 11,
    active: 10,
    recovery: 18,
    damage: 55,
    hitstun: 19,
    blockstun: 17,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 6,
  },
  // Burn Knuckle qcb+C (远距离)
  TERRY_BURN_KNUCKLE_C: {
    startup: 16,
    active: 14,
    recovery: 20,
    damage: 80,
    hitstun: 19,
    blockstun: 17,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 8,
  },
  // Burn Knuckle qcb+D (重版, 远距离高伤害) — KOF2002UM 校准数据
  TERRY_BURN_KNUCKLE_D: {
    startup: 18,
    active: 14,
    recovery: 22,
    damage: 95,
    hitstun: 19,
    blockstun: 17,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  // Crack Shoot qcb+B (中段)
  TERRY_CRACK_SHOT: {
    startup: 11,
    active: 6,
    recovery: 21,
    damage: 50,
    hitstun: 19,
    blockstun: 17,
    pushback: 4,
    hitLevel: "HIGH" as const,
    knockdown: false,
  },
  // Crack Shoot qcb+D (中段)
  TERRY_CRACK_SHOT_D: {
    startup: 9,
    active: 8,
    recovery: 23,
    damage: 60,
    hitstun: 19,
    blockstun: 17,
    pushback: 5,
    hitLevel: "HIGH" as const,
    knockdown: false,
  },
  // Power Dunk dp+B (2段KD)
  TERRY_POWER_DUNK: {
    startup: 8,
    active: 8,
    recovery: 40,
    damage: 90,
    hitstun: 25,
    blockstun: 20,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 12,
  },
  // Power Dunk dp+D (2段KD)
  TERRY_POWER_DUNK_D: {
    startup: 10,
    active: 8,
    recovery: 44,
    damage: 110,
    hitstun: 25,
    blockstun: 20,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 14,
  },
  // Rising Tackle d,u+A (多段上升)
  TERRY_RISING_TACKLE: {
    startup: 6,
    active: 12,
    recovery: 35,
    damage: 90,
    hitstun: 25,
    blockstun: 20,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 12,
  },
  // Rising Tackle d,u+C (多段, 更多hits)
  TERRY_RISING_TACKLE_C: {
    startup: 6,
    active: 16,
    recovery: 39,
    damage: 130,
    hitstun: 28,
    blockstun: 22,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 14,
  },
  // Power Charge hcf+B/D (突进技)
  TERRY_POWER_CHARGE: {
    startup: 8,
    active: 6,
    recovery: 18,
    damage: 80,
    hitstun: 18,
    blockstun: 16,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // Back Knuckle f+A (指令通常技)
  TERRY_BACK_KNUCKLE: {
    startup: 5,
    active: 4,
    recovery: 12,
    damage: 45,
    hitstun: 12,
    blockstun: 10,
    pushback: 3,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // Hammer Punch f+C (中段技, overhead)
  TERRY_HAMMER_PUNCH: {
    startup: 12,
    active: 4,
    recovery: 22,
    damage: 65,
    hitstun: 18,
    blockstun: 16,
    pushback: 5,
    hitLevel: "HIGH" as const,
    knockdown: true,
  },
  // ── 特瑞DM ── Dream Cancel Wiki KOF2002UM 校准数据
  DM_POWER_GEYSER_A: {
    startup: 16,
    active: 10,
    recovery: 43,
    damage: 200,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  DM_POWER_GEYSER_C: {
    startup: 17,
    active: 11,
    recovery: 47,
    damage: 200,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  DM_HIGH_ANGLE_GEYSER_B: {
    startup: 7,
    active: 12,
    recovery: 33,
    damage: 190,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 18,
  },
  DM_HIGH_ANGLE_GEYSER_D: {
    startup: 11,
    active: 14,
    recovery: 37,
    damage: 190,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 18,
  },
  SDM_TRIPLE_GEYSER: {
    startup: 17,
    active: 22,
    recovery: 36,
    damage: 340,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 30,
  },
  // SDM Power Geyser·EX (MAX版强化Power Geyser)
  SDM_POWER_GEYSER_EX: {
    startup: 10,
    active: 20,
    recovery: 38,
    damage: 300,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 35,
  },
  // ── 特瑞DM别名 (Terry DM aliases, used by combat system) ──
  DM_POWER_GEYSER: {
    startup: 17,
    active: 10,
    recovery: 43,
    damage: 220,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 22,
  },
  DM_HIGH_ANGLE_GEYSER: {
    startup: 6,
    active: 12,
    recovery: 33,
    damage: 200,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  // ── 金必杀技 (Kim Kaphwan) ── KOF2002UM calibrated
  // 飛燕斬 dp+B (flash kick, KD)
  KIM_HIENZAN: {
    startup: 5,
    active: 6,
    recovery: 25,
    damage: 100,
    hitstun: 25,
    blockstun: 20,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 12,
  },
  // 飛燕斬 dp+D (强版, 多段 flash kick, KD)
  KIM_HIENZAN_D: {
    startup: 7,
    active: 10,
    recovery: 30,
    damage: 140,
    hitstun: 26,
    blockstun: 20,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 14,
  },
  // 半月斬 qcb+B (half-moon kick, overhead)
  KIM_HANGETSU: {
    startup: 7,
    active: 12,
    recovery: 29,
    damage: 80,
    hitstun: 19,
    blockstun: 17,
    pushback: 5,
    hitLevel: "HIGH" as const,
    knockdown: true,
  },
  // 半月斬 qcb+D (强版, slower overhead)
  KIM_HANGETSU_D: {
    startup: 9,
    active: 14,
    recovery: 31,
    damage: 110,
    hitstun: 22,
    blockstun: 19,
    pushback: 6,
    hitLevel: "HIGH" as const,
    knockdown: true,
  },
  // 覇気蹴り f+B (axe kick, LOW hitlevel)
  KIM_HAKI: {
    startup: 9,
    active: 5,
    recovery: 20,
    damage: 65,
    hitstun: 19,
    blockstun: 17,
    pushback: 3,
    hitLevel: "LOW" as const,
    knockdown: false,
  },
  // 飛翔脚 (flash kick cancel, very fast)
  KIM_HISHOU: {
    startup: 2,
    active: 8,
    recovery: 14,
    damage: 70,
    hitstun: 19,
    blockstun: 17,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 三連蹴り 1段 (triple kick, multi-hit)
  KIM_SANREN: {
    startup: 8,
    active: 14,
    recovery: 24,
    damage: 60,
    hitstun: 19,
    blockstun: 17,
    pushback: 3,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 三連蹴り 追加 (2nd+3rd hits)
  KIM_SANREN_2: {
    startup: 10,
    active: 12,
    recovery: 22,
    damage: 55,
    hitstun: 19,
    blockstun: 17,
    pushback: 3,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 崩し蹴り f+B (中段技, overhead)
  KIM_KUZUSHI_GERI: {
    startup: 10,
    active: 4,
    recovery: 20,
    damage: 50,
    hitstun: 16,
    blockstun: 14,
    pushback: 4,
    hitLevel: "HIGH" as const,
    knockdown: false,
  },
  // 滑り蹴り df+D (下段技, low slide)
  KIM_NERICHAGI: {
    startup: 8,
    active: 6,
    recovery: 22,
    damage: 45,
    hitstun: 14,
    blockstun: 12,
    pushback: 4,
    hitLevel: "LOW" as const,
    knockdown: false,
  },
  // 回転飛燕斬 (对空flash kick, anti-air)
  KIM_KAITEN_HIEN_ZAN: {
    startup: 5,
    active: 8,
    recovery: 28,
    damage: 90,
    hitstun: 22,
    blockstun: 18,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 鳳凰天舞脚 (air/ground DM phoenix kick)
  DM_PHOENIX_KICK: {
    startup: 8,
    active: 13,
    recovery: 43,
    damage: 200,
    hitstun: 0,
    blockstun: 21,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 17,
  },
  DM_PHOENIX_HITEN: {
    startup: 8,
    active: 5,
    recovery: 30,
    damage: 180,
    hitstun: 0,
    blockstun: 21,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 14,
  },
  // SDM 凤凰飞天 (Phoenix Hiten SDM)
  SDM_PHOENIX_HITEN: {
    startup: 6,
    active: 8,
    recovery: 28,
    damage: 260,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 22,
  },
  // SDM 凤凰飞天·EX (Phoenix Hiten EX SDM, MAX强化版)
  SDM_PHOENIX_HITEN_EX: {
    startup: 5,
    active: 12,
    recovery: 30,
    damage: 280,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 28,
  },
} as const;
