/**
 * Leona Heidern + Robert Garcia + Mai Shiranani frame data
 * Split from frameDataChars.ts
 *
 * 数据源: KOF2002UM 校准数据
 */
export const LEONA_ROBERT_MAI_DATA = {
  // ── 莉安娜必杀技 (Leona Heidern) ── KOF2002UM 校准数据
  LEONA_MOON_SLASH: {
    startup: 5,
    active: 10,
    recovery: 28,
    damage: 80,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  LEONA_MOON_SLASH_C: {
    startup: 7,
    active: 14,
    recovery: 32,
    damage: 130,
    hitstun: 28,
    blockstun: 22,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 14,
  },
  LEONA_EAR_RING: {
    startup: 5,
    active: 5,
    recovery: 25,
    damage: 80,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 10,
  },
  LEONA_EAR_RING_C: {
    startup: 7,
    active: 10,
    recovery: 30,
    damage: 140,
    hitstun: 28,
    blockstun: 22,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 14,
  },
  LEONA_GRAND_SABER: {
    startup: 7,
    active: 8,
    recovery: 22,
    damage: 90,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  LEONA_BALTIC: {
    startup: 16,
    active: 18,
    recovery: 30,
    damage: 75,
    hitstun: 28,
    blockstun: 26,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  DM_V_SLASHER: {
    startup: 8,
    active: 8,
    recovery: 38,
    damage: 210,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  // Moon Slasher hcb,f+P (DP-type special, stronger version)
  LEONA_MOON_SLASHER: {
    startup: 5,
    active: 10,
    recovery: 30,
    damage: 95,
    hitstun: 24,
    blockstun: 20,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 14,
  },
  // Voltech Saber (突剑) qcb+P
  LEONA_VOLTECH_SABER: {
    startup: 8,
    active: 6,
    recovery: 24,
    damage: 80,
    hitstun: 18,
    blockstun: 16,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 10,
  },
  // Glider Ceiling (滑翔天花板) 对空技
  LEONA_GLIDER_CEILING: {
    startup: 6,
    active: 8,
    recovery: 28,
    damage: 75,
    hitstun: 20,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  // Revolver Spark (左轮火花) 连打技
  LEONA_REVOLVER_SPARK: {
    startup: 4,
    active: 4,
    recovery: 20,
    damage: 10,
    hits: 8,
    hitstun: 16,
    blockstun: 14,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // Rebel Spark DM (叛逆火花·DM) qcf,qcf+K
  DM_REBEL_SPARK: {
    startup: 10,
    active: 12,
    recovery: 38,
    damage: 200,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  // Rebel Spark SDM (叛逆火花·SDM)
  SDM_REBEL_SPARK: {
    startup: 8,
    active: 15,
    recovery: 42,
    damage: 280,
    hitstun: 0,
    blockstun: 24,
    pushback: 14,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 30,
  },
  // ── 罗伯特必杀技 (Robert Garcia) ── KOF2002UM 校准数据
  // 龙撃拳 qcf+A (飞行道具)
  ROBERT_RYU_GEKI: {
    startup: 12,
    active: 22,
    recovery: 28,
    damage: 70,
    hitstun: 26,
    blockstun: 24,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  // 龙撃拳 qcf+C (飞行道具 强版)
  ROBERT_RYU_GEKI_C: {
    startup: 15,
    active: 25,
    recovery: 26,
    damage: 100,
    hitstun: 28,
    blockstun: 26,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 10,
  },
  // 龙牙 dp+A (DP 弱版)
  ROBERT_RYU_ZAN: {
    startup: 5,
    active: 6,
    recovery: 26,
    damage: 80,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  // 龙牙 dp+C (DP 强版)
  ROBERT_RYU_ZAN_C: {
    startup: 6,
    active: 10,
    recovery: 30,
    damage: 130,
    hitstun: 28,
    blockstun: 22,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 14,
  },
  // 飞燕龍神脚 空中 qcb+K (空中俯冲踢)
  ROBERT_HIEN_RYU_JIN: {
    startup: 8,
    active: 8,
    recovery: 18,
    damage: 85,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 幻影脚 hcf+B (多段踢)
  ROBERT_GENEI_KYAKU: {
    startup: 10,
    active: 10,
    recovery: 22,
    damage: 85,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "HIGH" as const,
    knockdown: false,
  },
  // 飞燕旋风脚 qcb+K (冲刺踢)
  ROBERT_HIEN_RYU_KYAKU: {
    startup: 12,
    active: 10,
    recovery: 22,
    damage: 95,
    hitstun: 24,
    blockstun: 20,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // 飞燕疾风脚 dp+B (DP 对空踢)
  ROBERT_HIEN_SHIPPU_KYAKU: {
    startup: 5,
    active: 8,
    recovery: 28,
    damage: 85,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 13,
  },
  // 飞燕疾风脚 dp+D (DP 对空踢 强版)
  ROBERT_HIEN_SHIPPU_KYAKU_D: {
    startup: 7,
    active: 12,
    recovery: 32,
    damage: 130,
    hitstun: 28,
    blockstun: 22,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  // 龙虎乱舞 DM qcf,qcf+P
  DM_RYU_KO_RYU: {
    startup: 8,
    active: 8,
    recovery: 36,
    damage: 220,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  // 霸王翔吼拳 DM f,hcf+P
  DM_HAOU_SHOKOU: {
    startup: 10,
    active: 10,
    recovery: 38,
    damage: 210,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 22,
  },
  // 双龙波 qcf+A (飞行道具)
  ROBERT_SOURYUU_HA: {
    startup: 12,
    active: 18,
    recovery: 28,
    damage: 70,
    hitstun: 14,
    blockstun: 8,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  // 双龙波·强 qcf+C (飞行道具 强版)
  ROBERT_SOURYUU_HA_C: {
    startup: 14,
    active: 22,
    recovery: 26,
    damage: 85,
    hitstun: 16,
    blockstun: 10,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 10,
  },
  // 飞燕旋风脚 qcb+B
  ROBERT_HIEN_SHURETTO: {
    startup: 8,
    active: 6,
    recovery: 24,
    damage: 85,
    hitstun: 20,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 飞燕旋风脚·强 qcb+D
  ROBERT_HIEN_SHURETTO_C: {
    startup: 10,
    active: 8,
    recovery: 28,
    damage: 100,
    hitstun: 24,
    blockstun: 20,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 龙虎乱舞·Robert版·DM qcf,qcf+P
  DM_RYUKO_RANBU_ROBERT: {
    startup: 4,
    active: 14,
    recovery: 36,
    damage: 220,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 22,
  },
  // 龙虎乱舞·Robert版·SDM
  SDM_RYUKO_RANBU_ROBERT: {
    startup: 3,
    active: 18,
    recovery: 40,
    damage: 300,
    hitstun: 0,
    blockstun: 24,
    pushback: 14,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 32,
  },
  // ── 不知火舞必杀技 (Mai Shiranui) ── KOF2002UM 校准数据
  // 花蝶扇 qcf+A (飞行道具)
  MAI_KA_CHO_SEN: {
    startup: 13,
    active: 20,
    recovery: 30,
    damage: 70,
    hitstun: 28,
    blockstun: 26,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  // 花蝶扇 qcf+C (飞行道具 强版)
  MAI_KA_CHO_SEN_C: {
    startup: 16,
    active: 24,
    recovery: 28,
    damage: 100,
    hitstun: 30,
    blockstun: 28,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 10,
  },
  // 飞翔龍炎陣 dp+K (DP)
  MAI_HISHO_RYU_EN_JIN: {
    startup: 6,
    active: 6,
    recovery: 26,
    damage: 85,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  // 龍炎舞 qcb+P (近距离火焰)
  MAI_RYU_EN_BU: {
    startup: 10,
    active: 8,
    recovery: 22,
    damage: 85,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // ムササビの舞 空中 qcb+P (空中俯冲扇)
  MAI_MUSASABI: {
    startup: 12,
    active: 10,
    recovery: 20,
    damage: 80,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "HIGH" as const,
    knockdown: true,
  },
  // ムササビの舞 重版 空中 qcb+K (空中俯冲扇 重版, 高伤害) — KOF2002UM 校准数据
  MAI_MUSASABI_D: {
    startup: 14,
    active: 12,
    recovery: 22,
    damage: 95,
    hitstun: 24,
    blockstun: 20,
    pushback: 6,
    hitLevel: "HIGH" as const,
    knockdown: true,
  },
  // 必殺忍蜂 ←↙↓↘→+K (冲刺攻击)
  MAI_HISSATSU_SHINOBI: {
    startup: 8,
    active: 8,
    recovery: 24,
    damage: 90,
    hitstun: 24,
    blockstun: 20,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 花嵐 DM qcf,qcf+K
  DM_HAKA_OTOSHI: {
    startup: 10,
    active: 12,
    recovery: 40,
    damage: 210,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  // 超必殺忍蜂 DM qcb,qcb+K
  DM_CHOU_HISSATSU: {
    startup: 8,
    active: 14,
    recovery: 38,
    damage: 200,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 18,
  },
  // SDM 必殺忍蜂 (Hissatsu Shinobi SDM)
  SDM_CHOU_HISSATSU: {
    startup: 6,
    active: 17,
    recovery: 36,
    damage: 290,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 26,
  },
  // 花蝶扇·D版 qcf+D (飞行道具 D版) — KOF2002UM 校准数据
  MAI_KACHO_SEN_D: {
    startup: 14,
    active: 22,
    recovery: 30,
    damage: 80,
    hitstun: 16,
    blockstun: 10,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 9,
  },
  // 飞翔龙炎阵·强 dp+D (对空 DP 强版) — KOF2002UM 校准数据
  MAI_HISHO_RYU_EN_JIN_C: {
    startup: 6,
    active: 10,
    recovery: 28,
    damage: 95,
    hitstun: 24,
    blockstun: 20,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 14,
  },
  // 水莲之舞 空中 qcb+K (空中技) — KOF2002UM 校准数据
  MAI_SUIREI_NO_MAIOCHI: {
    startup: 4,
    active: 6,
    recovery: 18,
    damage: 70,
    hitstun: 16,
    blockstun: 14,
    pushback: 4,
    hitLevel: "HIGH" as const,
    knockdown: true,
  },
  // 超必杀忍蜂·HSDM (Chou Hissatsu Shinobi HSDM) — KOF2002UM 校准数据
  HSDM_CHOU_HISSATSU: {
    startup: 3,
    active: 18,
    recovery: 36,
    damage: 350,
    hitstun: 28,
    blockstun: 21,
    pushback: 14,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 36,
  },
  // ── K' 必杀技 (K Dash) ── KOF2002UM calibrated
  // Ein Trigger qcf+A (standalone punch)
  KDASH_EINS: {
    startup: 10,
    active: 25,
    recovery: 18,
    damage: 60,
    hitstun: 14,
    blockstun: 12,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 5,
  },
  // Ein Trigger qcf+C (strong standalone punch)
  KDASH_EINS_C: {
    startup: 12,
    active: 30,
    recovery: 20,
    damage: 75,
    hitstun: 16,
    blockstun: 14,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 6,
  },
  // Second Shell qcf+A>K (followup kick from Ein Trigger)
  KDASH_SECOND_SHELL: {
    startup: 6,
    active: 8,
    recovery: 16,
    damage: 50,
    hitstun: 16,
    blockstun: 14,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // Second Spike qcf+A>D (low followup from Ein Trigger)
  KDASH_SECOND_SPIKE: {
    startup: 8,
    active: 6,
    recovery: 18,
    damage: 45,
    hitstun: 14,
    blockstun: 12,
    pushback: 3,
    hitLevel: "LOW" as const,
    knockdown: false,
  },
  // Crow Bites dp+A (DP, KD)
  KDASH_CROW: {
    startup: 5,
    active: 6,
    recovery: 22,
    damage: 70,
    hitstun: 18,
    blockstun: 14,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  // Crow Bites dp+C (strong DP, KD)
  KDASH_CROW_C: {
    startup: 6,
    active: 8,
    recovery: 26,
    damage: 90,
    hitstun: 20,
    blockstun: 16,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 14,
  },
  // Crow Bites dp+D (重版 DP, 多段上升, KD) — KOF2002UM 校准数据
  KDASH_CROW_BITE_D: {
    startup: 7,
    active: 10,
    recovery: 30,
    damage: 110,
    hitstun: 22,
    blockstun: 18,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 16,
  },
  // One Inch f+A (近距离特殊技, 快速短距打击) — KOF2002UM 校准数据
  KDASH_ONE_INCH: {
    startup: 8,
    active: 5,
    recovery: 18,
    damage: 65,
    hitstun: 18,
    blockstun: 14,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // Minute Spike qcb+K (jumping knee)
  KDASH_MINUTE: {
    startup: 14,
    active: 6,
    recovery: 18,
    damage: 65,
    hitstun: 16,
    blockstun: 14,
    pushback: 4,
    hitLevel: "HIGH" as const,
    knockdown: false,
  },
  // Narrow Spike qcb+K>d+K (followup slide)
  KDASH_NARROW: {
    startup: 8,
    active: 8,
    recovery: 16,
    damage: 55,
    hitstun: 14,
    blockstun: 12,
    pushback: 3,
    hitLevel: "LOW" as const,
    knockdown: true,
  },
  // DM Chain Drive qcf,qcf+P (rushing DM)
  DM_CHAIN_DRIVE: {
    startup: 10,
    active: 10,
    recovery: 38,
    damage: 200,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 18,
  },
  // DM Heat Drive qcf,qcf+K (projectile DM, slow startup)
  DM_HEAT_DRIVE: {
    startup: 22,
    active: 14,
    recovery: 40,
    damage: 210,
    hitstun: 0,
    blockstun: 22,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  // SDM Chain Drive (K' Chain Drive SDM)
  SDM_CHAIN_DRIVE: {
    startup: 8,
    active: 14,
    recovery: 36,
    damage: 300,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 28,
  },
  // SDM Heat Drive (K' Heat Drive SDM)
  SDM_HEAT_DRIVE: {
    startup: 20,
    active: 18,
    recovery: 38,
    damage: 310,
    hitstun: 0,
    blockstun: 22,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 30,
  },
  // Trigger Shell qcf+B (飞行道具) — KOF2002UM 校准数据
  KDASH_TRIGGER_SHELL: {
    startup: 10,
    active: 16,
    recovery: 26,
    damage: 65,
    hitstun: 14,
    blockstun: 8,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 7,
  },
  // Trigger Shell·强 qcf+D (飞行道具 强版) — KOF2002UM 校准数据
  KDASH_TRIGGER_SHELL_C: {
    startup: 12,
    active: 20,
    recovery: 28,
    damage: 80,
    hitstun: 16,
    blockstun: 10,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 9,
  },
  // Blackout qcb+P (瞬移技) — KOF2002UM 校准数据
  KDASH_BLACKOUT: {
    startup: 5,
    active: 1,
    recovery: 15,
    damage: 1,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // Chain Drive·HSDM qcf,qcf+BD — KOF2002UM 校准数据
  HSDM_CHAIN_DRIVE: {
    startup: 3,
    active: 16,
    recovery: 38,
    damage: 350,
    hitstun: 28,
    blockstun: 21,
    pushback: 14,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 38,
  },
  // ── 库拉必杀技 (Kula Diamond) ── KOF2002UM 校准数据
  // Diamond Breath qcf+A (冰飞行道具)
  KULA_BREATH: {
    startup: 14,
    active: 20,
    recovery: 28,
    damage: 70,
    hitstun: 28,
    blockstun: 26,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  KULA_BREATH_C: {
    startup: 16,
    active: 24,
    recovery: 26,
    damage: 100,
    hitstun: 30,
    blockstun: 28,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 10,
  },
  KULA_SHELL: {
    startup: 10,
    active: 6,
    recovery: 20,
    damage: 65,
    hitstun: 20,
    blockstun: 16,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  KULA_SHELL_C: {
    startup: 12,
    active: 8,
    recovery: 24,
    damage: 85,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  KULA_LAY: {
    startup: 8,
    active: 10,
    recovery: 20,
    damage: 65,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "LOW" as const,
    knockdown: true,
  },
  KULA_EDGE: {
    startup: 6,
    active: 6,
    recovery: 22,
    damage: 80,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  DM_CHAIN_SHOT: {
    startup: 8,
    active: 10,
    recovery: 38,
    damage: 200,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  DM_FREEZE: {
    startup: 10,
    active: 12,
    recovery: 36,
    damage: 200,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  // ── 库拉追加必杀技 (Kula Diamond 追加) ── KOF2002UM 校准数据
  // Rei Spin qcb+B (旋转踢) — KOF2002UM 校准数据
  KULA_REI_SPIN: {
    startup: 8,
    active: 6,
    recovery: 20,
    damage: 75,
    hitstun: 18,
    blockstun: 16,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  // Rei Spin·强 qcb+D (旋转踢 强版) — KOF2002UM 校准数据
  KULA_REI_SPIN_C: {
    startup: 10,
    active: 8,
    recovery: 22,
    damage: 90,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  // Crow Bite·Kula版 dp+P (对空 DP) — KOF2002UM 校准数据
  KULA_CROW_BITE_KULA: {
    startup: 5,
    active: 8,
    recovery: 26,
    damage: 80,
    hitstun: 20,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  // 冰之罚 qcb,qcb+P (冰系必杀技) — KOF2002UM 校准数据
  KULA_ICE_PENALTY: {
    startup: 6,
    active: 10,
    recovery: 28,
    damage: 95,
    hitstun: 24,
    blockstun: 20,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 12,
  },
  // Freeze Execution·HSDM qcf,qcf+BD — KOF2002UM 校准数据
  HSDM_FREEZE_EXECUTION: {
    startup: 2,
    active: 20,
    recovery: 38,
    damage: 360,
    hitstun: 30,
    blockstun: 21,
    pushback: 14,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 38,
  },
  SDM_POWER_GEYSER: {
    startup: 14,
    active: 20,
    recovery: 38,
    damage: 300,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 30,
  },
  SDM_PHOENIX_KICK: {
    startup: 6,
    active: 18,
    recovery: 32,
    damage: 290,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 25,
  },
  SDM_V_SLASHER: {
    startup: 8,
    active: 18,
    recovery: 38,
    damage: 310,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 30,
  },
  SDM_CHAIN_SHOT: {
    startup: 8,
    active: 15,
    recovery: 40,
    damage: 300,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 25,
  },
  SDM_FREEZE: {
    startup: 8,
    active: 12,
    recovery: 36,
    damage: 300,
    hitstun: 0,
    blockstun: 22,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 28,
  },
  // ── 罗伯特SDM (Robert Garcia) ── KOF2002UM 校准数据
} as const;
