/**
 * Andy + Billy + Chang + Choi + Mature + Yamazaki frame data
 * Split from frameDataChars.ts
 *
 * 数据源: KOF2002UM 校准数据
 */
export const ANDY_BILLY_CHANG_CHOI_MATURE_YAMAZAKI_DATA = {
  // ── 玛卓命令通常技 (Mature) ── KOF2002UM 校准数据
  MATURE_DESPAIR: {
    startup: 14,
    active: 4,
    recovery: 19,
    damage: 45,
    hitstun: 19,
    blockstun: 16,
    pushback: 3,
    hitLevel: "HIGH" as const,
    knockdown: false,
  },
  MATURE_JAB: {
    startup: 8,
    active: 4,
    recovery: 21,
    damage: 38,
    hitstun: 18,
    blockstun: 15,
    pushback: 2,
    hitLevel: "LOW" as const,
    knockdown: false,
  },
  // ── 玛卓必杀技 (Mature) ── KOF2002UM 校准数据
  MATURE_MASSACRE: {
    startup: 8,
    active: 8,
    recovery: 22,
    damage: 75,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 9,
  },
  MATURE_MASSACRE_C: {
    startup: 10,
    active: 12,
    recovery: 26,
    damage: 110,
    hitstun: 26,
    blockstun: 22,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 12,
  },
  MATURE_HEAVENS_GATE: {
    startup: 14,
    active: 6,
    recovery: 26,
    damage: 85,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "HIGH" as const,
    knockdown: true,
    chipDamage: 10,
  },
  MATURE_ECSTASY: {
    startup: 5,
    active: 6,
    recovery: 26,
    damage: 85,
    hitstun: 22,
    blockstun: 18,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  // Metal Massacre·EX qcb,f+K
  MATURE_METAL_MASSACRE_EX: {
    startup: 8,
    active: 10,
    recovery: 30,
    damage: 95,
    hitstun: 20,
    blockstun: 18,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 夜之气息 qcf+P (飞行道具)
  MATURE_NOCTURNAL_BREATH: {
    startup: 14,
    active: 20,
    recovery: 32,
    damage: 55,
    hitstun: 14,
    blockstun: 14,
    pushback: 3,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 6,
  },
  // Vanilla Rush qcb+P (突进爪击)
  MATURE_VANILLA_RUSH: {
    startup: 7,
    active: 6,
    recovery: 22,
    damage: 75,
    hitstun: 16,
    blockstun: 16,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // ── 玛卓DM (Mature) ── KOF2002UM 校准数据
  DM_NOCTURNAL_LIGHT: {
    startup: 8,
    active: 14,
    recovery: 38,
    damage: 200,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 18,
  },
  // ── 玛卓SDM (Mature) ── KOF2002UM 校准数据
  SDM_NOCTURNAL_LIGHT: {
    startup: 8,
    active: 20,
    recovery: 36,
    damage: 300,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 28,
  },
  // ── 大门五郎必杀技 (Yashiro Nanakase) ── KOF2002UM 校准数据
  YASHIRO_SHUU_WANI: {
    startup: 12,
    active: 4,
    recovery: 20,
    damage: 55,
    hitstun: 16,
    blockstun: 14,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  YASHIRO_JUU_ZUTSU: {
    startup: 16,
    active: 4,
    recovery: 22,
    damage: 55,
    hitstun: 18,
    blockstun: 15,
    pushback: 4,
    hitLevel: "HIGH" as const,
    knockdown: false,
  },
  YASHIRO_UPPER_DU: {
    startup: 6,
    active: 10,
    recovery: 24,
    damage: 80,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 8,
  },
  YASHIRO_UPPER_DU_C: {
    startup: 7,
    active: 16,
    recovery: 28,
    damage: 120,
    hitstun: 26,
    blockstun: 22,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 12,
  },
  YASHIRO_NIRAAI: {
    startup: 14,
    active: 6,
    recovery: 26,
    damage: 100,
    hitstun: 24,
    blockstun: 20,
    pushback: 6,
    hitLevel: "HIGH" as const,
    knockdown: true,
    chipDamage: 10,
  },
  YASHIRO_MUSATSU: {
    startup: 14,
    active: 6,
    recovery: 28,
    damage: 90,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "LOW" as const,
    knockdown: true,
    chipDamage: 8,
  },
  // 実弾肉弾 (投技)
  YASHIRO_SHIJITSU_NIKU_DAN: {
    startup: 5,
    active: 3,
    recovery: 30,
    damage: 85,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 実弾肉弾·强 (投技)
  YASHIRO_SHIJITSU_NIKU_DAN_C: {
    startup: 6,
    active: 3,
    recovery: 32,
    damage: 100,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 石破血圧 (Sekia Ketsuatsu)
  YASHIRO_SEKIA_KETSUATSU: {
    startup: 10,
    active: 6,
    recovery: 26,
    damage: 90,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  // 爆鳳CALL血 (Baku Hou Chou Ketsu) 对空
  YASHIRO_BAKU_HOU_CHOU_KETSU: {
    startup: 6,
    active: 8,
    recovery: 28,
    damage: 85,
    hitstun: 20,
    blockstun: 18,
    pushback: 6,
    hitLevel: "HIGH" as const,
    knockdown: true,
  },
  // ── 大门五郎DM/SDM (Yashiro) ── KOF2002UM 校准数据
  DM_ARMAGEDDON_BUSTERS: {
    startup: 10,
    active: 10,
    recovery: 42,
    damage: 230,
    hitstun: 0,
    blockstun: 21,
    pushback: 14,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 22,
  },
  SDM_ARMAGEDDON_BUSTERS: {
    startup: 8,
    active: 16,
    recovery: 40,
    damage: 330,
    hitstun: 0,
    blockstun: 21,
    pushback: 16,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 32,
  },
  // DM 大地爆裂 (Territory Bust DM)
  DM_TERRITORY_BUST: {
    startup: 12,
    active: 8,
    recovery: 42,
    damage: 210,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 22,
  },
  // DM Miss Head (投技DM)
  DM_MISS_HEAD: {
    startup: 4,
    active: 4,
    recovery: 42,
    damage: 210,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // ── 克里斯命令通常技 (Chris) ── KOF2002UM 校准数据
  CHRIS_MAKASHIPPO: {
    startup: 10,
    active: 4,
    recovery: 18,
    damage: 38,
    hitstun: 16,
    blockstun: 14,
    pushback: 3,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  CHRIS_KAZAGURUMA: {
    startup: 8,
    active: 4,
    recovery: 20,
    damage: 35,
    hitstun: 14,
    blockstun: 12,
    pushback: 2,
    hitLevel: "LOW" as const,
    knockdown: false,
  },
  // ── 克里斯必杀技 (Chris) ── KOF2002UM 校准数据
  CHRIS_SHOT_WEAVE: {
    startup: 7,
    active: 4,
    recovery: 18,
    damage: 55,
    hitstun: 16,
    blockstun: 14,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  CHRIS_SHOT_WEAVE_C: {
    startup: 10,
    active: 6,
    recovery: 22,
    damage: 72,
    hitstun: 20,
    blockstun: 16,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  CHRIS_TWISTER_DRIVE: {
    startup: 12,
    active: 8,
    recovery: 28,
    damage: 78,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  CHRIS_SCRAMBLE_DASH: {
    startup: 8,
    active: 6,
    recovery: 24,
    damage: 60,
    hitstun: 18,
    blockstun: 15,
    pushback: 4,
    hitLevel: "LOW" as const,
    knockdown: false,
  },
  // 月突·上段 (Tsuki Tsuka Kamitsuki)
  CHRIS_TSUKI_TSUKA_KAMITSUKI: {
    startup: 7,
    active: 5,
    recovery: 18,
    damage: 65,
    hitstun: 14,
    blockstun: 12,
    pushback: 3,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // 月突·下段 (Tsuki Tsuka Shimotsuki)
  CHRIS_TSUKI_TSUKA_SHIMOTSUKI: {
    startup: 7,
    active: 5,
    recovery: 18,
    damage: 65,
    hitstun: 14,
    blockstun: 12,
    pushback: 3,
    hitLevel: "LOW" as const,
    knockdown: false,
  },
  // 第三波 (Daisan Haga) 反击技
  CHRIS_DAISAN_HAGA: {
    startup: 3,
    active: 20,
    recovery: 28,
    damage: 55,
    hitstun: 20,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: false,
    counterOnly: true,
  },
  // 狩庭·鬼柳 (Juvi Ga Oni Yanagi)
  CHRIS_JUVI_GA_ONI_YANAGI: {
    startup: 6,
    active: 8,
    recovery: 26,
    damage: 80,
    hitstun: 18,
    blockstun: 16,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // ── 克里斯DM (Chris) ── KOF2002UM 校准数据
  DM_CHAIN_SLIDE_TOUCH: {
    startup: 7,
    active: 14,
    recovery: 36,
    damage: 200,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 18,
  },
  // ── 克里斯SDM (Chris) ── KOF2002UM 校准数据
  SDM_CHAIN_SLIDE_TOUCH: {
    startup: 5,
    active: 20,
    recovery: 38,
    damage: 300,
    hitstun: 0,
    blockstun: 22,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 28,
  },
  // DM Another Blood
  DM_ANOTHER_BLOOD: {
    startup: 5,
    active: 10,
    recovery: 38,
    damage: 200,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  // SDM Another Blood
  SDM_ANOTHER_BLOOD: {
    startup: 4,
    active: 12,
    recovery: 40,
    damage: 280,
    hitstun: 0,
    blockstun: 22,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 30,
  },
  // ── 夏尔美命令通常技 (Shermie) ── KOF2002UM 校准数据
  SHERMIE_STAND: {
    startup: 14,
    active: 4,
    recovery: 20,
    damage: 42,
    hitstun: 18,
    blockstun: 15,
    pushback: 3,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  SHERMIE_CLASH: {
    startup: 8,
    active: 4,
    recovery: 22,
    damage: 38,
    hitstun: 16,
    blockstun: 14,
    pushback: 2,
    hitLevel: "LOW" as const,
    knockdown: false,
  },
  // ── 夏尔美必杀技 (Shermie) ── KOF2002UM 校准数据
  SHERMIE_SHOOT: {
    startup: 10,
    active: 6,
    recovery: 24,
    damage: 70,
    hitstun: 20,
    blockstun: 17,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  SHERMIE_SHOOT_C: {
    startup: 14,
    active: 10,
    recovery: 28,
    damage: 90,
    hitstun: 24,
    blockstun: 20,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 12,
  },
  SHERMIE_CARNIVAL: {
    startup: 12,
    active: 5,
    recovery: 26,
    damage: 75,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 10,
  },
  SHERMIE_AXLE_SPIN: {
    startup: 12,
    active: 6,
    recovery: 28,
    damage: 68,
    hitstun: 20,
    blockstun: 16,
    pushback: 5,
    hitLevel: "LOW" as const,
    knockdown: true,
    chipDamage: 8,
  },
  // Shermie Spiral (投技)
  SHERMIE_SPIRAL: {
    startup: 5,
    active: 3,
    recovery: 30,
    damage: 80,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // Shermie Spiral·强 (投技)
  SHERMIE_SPIRAL_C: {
    startup: 6,
    active: 3,
    recovery: 32,
    damage: 95,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // Shermie Whip
  SHERMIE_WHIP: {
    startup: 8,
    active: 6,
    recovery: 24,
    damage: 70,
    hitstun: 16,
    blockstun: 14,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // Shermie Whip·强
  SHERMIE_WHIP_C: {
    startup: 10,
    active: 8,
    recovery: 28,
    damage: 85,
    hitstun: 20,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // Shermie Suplex (投技)
  SHERMIE_SUPLEX: {
    startup: 4,
    active: 3,
    recovery: 28,
    damage: 75,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // ── 夏尔美DM/SDM (Shermie) ── KOF2002UM 校准数据
  DM_SHERMIE_CARNIVAL: {
    startup: 8,
    active: 16,
    recovery: 38,
    damage: 200,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  SDM_SHERMIE_CARNIVAL: {
    startup: 6,
    active: 22,
    recovery: 40,
    damage: 310,
    hitstun: 0,
    blockstun: 21,
    pushback: 14,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 30,
  },
  // DM Shermie Flash (投技DM)
  DM_SHERMIE_FLASH: {
    startup: 5,
    active: 4,
    recovery: 40,
    damage: 190,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // SDM Shermie Flash (投技SDM)
  SDM_SHERMIE_FLASH: {
    startup: 4,
    active: 6,
    recovery: 38,
    damage: 260,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // ── 薇丝命令通常技 (Vice) ── KOF2002UM 校准数据
  VICE_MONSTROSITY: {
    startup: 10,
    active: 4,
    recovery: 20,
    damage: 42,
    hitstun: 18,
    blockstun: 15,
    pushback: 3,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  VICE_OVERKILL: {
    startup: 7,
    active: 4,
    recovery: 22,
    damage: 38,
    hitstun: 16,
    blockstun: 14,
    pushback: 2,
    hitLevel: "LOW" as const,
    knockdown: false,
  },
  // ── 薇丝必杀技 (Vice) ── KOF2002UM 校准数据
  VICE_OUTRAGE: {
    startup: 9,
    active: 6,
    recovery: 22,
    damage: 68,
    hitstun: 20,
    blockstun: 16,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  VICE_OUTRAGE_C: {
    startup: 12,
    active: 8,
    recovery: 26,
    damage: 85,
    hitstun: 22,
    blockstun: 18,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 10,
  },
  // Black End hcf+K (指令投)
  VICE_BLACK_END: {
    startup: 5,
    active: 3,
    recovery: 28,
    damage: 75,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  VICE_MAYHEM: {
    startup: 10,
    active: 5,
    recovery: 26,
    damage: 72,
    hitstun: 20,
    blockstun: 16,
    pushback: 5,
    hitLevel: "LOW" as const,
    knockdown: true,
    chipDamage: 8,
  },
  // Decide hcf+A (投技)
  VICE_DECIDE: {
    startup: 5,
    active: 3,
    recovery: 28,
    damage: 80,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // Decide·强 hcf+C (投技)
  VICE_DECIDE_C: {
    startup: 6,
    active: 3,
    recovery: 30,
    damage: 95,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // Gore Fest·特殊 hcb,f+P (投技)
  VICE_GORE_FEST_SPECIAL: {
    startup: 4,
    active: 4,
    recovery: 32,
    damage: 90,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // ── 薇丝DM/SDM (Vice) ── KOF2002UM 校准数据
  // Negative Gain hcf,hcf+K (指令投 DM)
  DM_NEGATIVE_GAIN: {
    startup: 4,
    active: 4,
    recovery: 40,
    damage: 210,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  }, // Negative Gain SDM (指令投 SDM)
  SDM_NEGATIVE_GAIN: {
    startup: 4,
    active: 8,
    recovery: 38,
    damage: 320,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 30,
  },
  // DM Gore Fest (投技DM)
  DM_GORE_FEST: {
    startup: 5,
    active: 4,
    recovery: 42,
    damage: 195,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // SDM Gore Fest (投技SDM)
  SDM_GORE_FEST: {
    startup: 4,
    active: 6,
    recovery: 40,
    damage: 270,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // DM Overkill (投技DM)
  DM_OVERKILL_DM: {
    startup: 4,
    active: 4,
    recovery: 40,
    damage: 200,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // Outrage qcb+P (近距离爪击) — KOF2002UM 校准数据
  VICE_OUTRAGE_QCB: {
    startup: 6,
    active: 5,
    recovery: 20,
    damage: 75,
    hitstun: 15,
    blockstun: 15,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  // Mayhem qcf+P (突进打) — KOF2002UM 校准数据
  VICE_MAYHEM_QCF: {
    startup: 7,
    active: 6,
    recovery: 24,
    damage: 82,
    hitstun: 16,
    blockstun: 16,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 10,
  },
  // DM Negative Flog qcf,qcf+K (突进投 DM) — KOF2002UM 校准数据
  DM_NEGATIVE_FLOG: {
    startup: 8,
    active: 10,
    recovery: 40,
    damage: 210,
    hitstun: 0,
    blockstun: 22,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 22,
  }, // ── 布鲁·玛丽命令通常技 (Blue Mary) ── KOF2002UM 校准数据
  MARY_HAMMER_PUNCH: {
    startup: 10,
    active: 4,
    recovery: 20,
    damage: 42,
    hitstun: 18,
    blockstun: 15,
    pushback: 3,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  MARY_DOUBLE_ROLLING: {
    startup: 8,
    active: 4,
    recovery: 22,
    damage: 38,
    hitstun: 16,
    blockstun: 14,
    pushback: 2,
    hitLevel: "LOW" as const,
    knockdown: false,
  },
} as const;
