/**
 * Blue Mary + Li Xiangfei + Kasumi Todoh + remaining frame data
 * Split from frameDataChars.ts
 *
 * 数据源: KOF2002UM 校准数据
 */
export const MARY_XIANGFEI_KASUMI_REST_DATA = {
  // ── 布鲁·玛丽必杀技 (Blue Mary) ── KOF2002UM 校准数据
  MARY_STRAIGHT_SLICER: {
    startup: 9,
    active: 6,
    recovery: 22,
    damage: 68,
    hitstun: 20,
    blockstun: 16,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  MARY_STRAIGHT_SLICER_C: {
    startup: 12,
    active: 8,
    recovery: 26,
    damage: 85,
    hitstun: 22,
    blockstun: 18,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 10,
  },
  // Backdrop Real hcf+K close (指令投)
  MARY_BACKDROP_REAL: {
    startup: 5,
    active: 3,
    recovery: 24,
    damage: 72,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
  }, // Spider hcb+P close (指令投)
  MARY_SPIDER: {
    startup: 5,
    active: 3,
    recovery: 28,
    damage: 75,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // M-type Spinning Fall hcf+K (旋转突进投, KD) — KOF2002UM 校准数据
  MARY_SPINNING_FALL: {
    startup: 8,
    active: 6,
    recovery: 28,
    damage: 78,
    hitstun: 20,
    blockstun: 16,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  // Vertical Arrow dp+B (对空上升踢) — KOF2002UM 校准数据
  MARY_VERTICAL_ARROW: {
    startup: 7,
    active: 5,
    recovery: 22,
    damage: 62,
    hitstun: 20,
    blockstun: 16,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 6,
  },
  // Vertical Arrow dp+D (对空上升踢強版, 多段) — KOF2002UM 校准数据
  MARY_VERTICAL_ARROW_D: {
    startup: 9,
    active: 8,
    recovery: 28,
    damage: 90,
    hitstun: 24,
    blockstun: 20,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  // Mary Snatcher hcb+K close (指令投, KD) — KOF2002UM 校准数据
  MARY_SNATCHER: {
    startup: 6,
    active: 3,
    recovery: 26,
    damage: 82,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
  }, // ── 布鲁·玛丽DM/SDM (Blue Mary) ── KOF2002UM 校准数据
  // Mary Typhoon DM (指令投 DM)
  DM_MARY_TYPHOON: {
    startup: 5,
    active: 6,
    recovery: 40,
    damage: 200,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  }, // Mary Typhoon SDM (指令投 SDM)
  SDM_MARY_TYPHOON: {
    startup: 5,
    active: 10,
    recovery: 38,
    damage: 310,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 30,
  },
  // M-type (当身技/Counter)
  MARY_M_TYPE: {
    startup: 5,
    active: 15,
    recovery: 20,
    damage: 50,
    hitstun: 18,
    blockstun: 0,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
    counterOnly: true,
  },
  // Crab Clutch (投技)
  MARY_CRAB_CLUTCH: {
    startup: 4,
    active: 3,
    recovery: 26,
    damage: 75,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 追击 (Moving Chase 移动投)
  MARY_MOVING_CHASE: {
    startup: 8,
    active: 5,
    recovery: 30,
    damage: 90,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // Dynamite Swing·DM (投技 DM)
  DM_MARY_DYNAMITE_SWING: {
    startup: 5,
    active: 4,
    recovery: 40,
    damage: 200,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // Dynamite Swing·SDM (投技 SDM)
  SDM_MARY_DYNAMITE_SWING: {
    startup: 4,
    active: 5,
    recovery: 42,
    damage: 280,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // Straight Slider qcb+K (低姿态滑踢) — KOF2002UM 校准数据
  MARY_STRAIGHT_SLIDER: {
    startup: 8,
    active: 6,
    recovery: 24,
    damage: 78,
    hitstun: 16,
    blockstun: 16,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  // Mary Spin Fall qcb,qcb+K (旋转突进, KD) — KOF2002UM 校准数据
  MARY_SPIN_FALL: {
    startup: 7,
    active: 8,
    recovery: 30,
    damage: 90,
    hitstun: 18,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  // DM Mary Dynamic qcf,qcf+K (突进连打 DM) — KOF2002UM 校准数据
  DM_MARY_DYNAMIC: {
    startup: 8,
    active: 10,
    recovery: 42,
    damage: 210,
    hitstun: 0,
    blockstun: 22,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 22,
  }, // ── 李香绯命令通常技 (Li Xiangfei) ── KOF2002UM 校准数据
  XIANGFEI_KYU_HO: {
    startup: 7,
    active: 4,
    recovery: 18,
    damage: 38,
    hitstun: 16,
    blockstun: 14,
    pushback: 3,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  XIANGFEI_KAKU_DA: {
    startup: 6,
    active: 4,
    recovery: 20,
    damage: 35,
    hitstun: 14,
    blockstun: 12,
    pushback: 2,
    hitLevel: "LOW" as const,
    knockdown: false,
  },
  // ── 李香绯必杀技 (Li Xiangfei) ── KOF2002UM 校准数据
  XIANGFEI_NANPA: {
    startup: 5,
    active: 5,
    recovery: 18,
    damage: 58,
    hitstun: 18,
    blockstun: 14,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  XIANGFEI_NANPA_C: {
    startup: 7,
    active: 8,
    recovery: 24,
    damage: 78,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  XIANGFEI_TENPATSU: {
    startup: 9,
    active: 5,
    recovery: 26,
    damage: 70,
    hitstun: 20,
    blockstun: 16,
    pushback: 5,
    hitLevel: "HIGH" as const,
    knockdown: true,
    chipDamage: 8,
  },
  XIANGFEI_MAHO_HISHA: {
    startup: 8,
    active: 6,
    recovery: 24,
    damage: 68,
    hitstun: 18,
    blockstun: 14,
    pushback: 5,
    hitLevel: "LOW" as const,
    knockdown: true,
    chipDamage: 8,
  },
  // 万臂 qcb+D (突进连打, KD) — KOF2002UM 校准数据
  XIANGFEI_MANPI: {
    startup: 10,
    active: 8,
    recovery: 26,
    damage: 80,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  // 遠山… qcb+K (突进打上, 浮空) — KOF2002UM 校准数据
  XIANGFEI_ENZAN: {
    startup: 12,
    active: 6,
    recovery: 24,
    damage: 72,
    hitstun: 20,
    blockstun: 16,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 天崩山 hcf+K (对空打上, 浮空) — KOF2002UM 校准数据
  XIANGFEI_TENPOZAN: {
    startup: 8,
    active: 6,
    recovery: 28,
    damage: 75,
    hitstun: 22,
    blockstun: 16,
    pushback: 5,
    hitLevel: "HIGH" as const,
    knockdown: true,
    chipDamage: 8,
  },
  // ── 李香绯DM (Li Xiangfei) ── KOF2002UM 校准数据
  DM_CHO_KA_RINGA: {
    startup: 7,
    active: 14,
    recovery: 36,
    damage: 190,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  // ── 李香绯SDM (Li Xiangfei) ── KOF2002UM 校准数据
  SDM_CHO_KA_RINGA: {
    startup: 5,
    active: 20,
    recovery: 38,
    damage: 300,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 30,
  },
  // ── 李香绯追加必杀技 (Li Xiangfei) ── KOF2002UM 校准数据
  // 超球弾 qcf+A (飞行道具)
  XIANGFEI_CHOU_KASAN: {
    startup: 12,
    active: 20,
    recovery: 28,
    damage: 60,
    hitstun: 14,
    blockstun: 8,
    pushback: 3,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 5,
  },
  // 超球弾 qcf+C (飞行道具·强)
  XIANGFEI_CHOU_KASAN_C: {
    startup: 16,
    active: 24,
    recovery: 26,
    damage: 75,
    hitstun: 16,
    blockstun: 10,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 7,
  },
  // 龙连打 hcf+P (连打技)
  XIANGFEI_RYU_RENDA: {
    startup: 4,
    active: 3,
    recovery: 22,
    damage: 12,
    hitstun: 18,
    blockstun: 14,
    pushback: 2,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // 天舞乱舞 dp+K (对空)
  XIANGFEI_TEN_SHO_RANBU: {
    startup: 6,
    active: 8,
    recovery: 32,
    damage: 85,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  // ── 李香绯追加DM (Li Xiangfei) ── KOF2002UM 校准数据
  // 超球弾·DM qcf×2+P (飞行道具DM)
  DM_CHOU_KYOKU_DAN: {
    startup: 14,
    active: 30,
    recovery: 34,
    damage: 180,
    hitstun: 0,
    blockstun: 22,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 18,
  },
  // 飞脚 dp+K (上升踢技, KD) — KOF2002UM 校准数据
  XIANGFEI_NIKYAKU: {
    startup: 7,
    active: 6,
    recovery: 22,
    damage: 75,
    hitstun: 16,
    blockstun: 16,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  // 栄扇楼 qcb+P (突进肘打) — KOF2002UM 校准数据
  XIANGFEI_EISANROU: {
    startup: 10,
    active: 8,
    recovery: 26,
    damage: 80,
    hitstun: 18,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 10,
  },
  // DM 鉄山靠 qcf,qcf+P (突进正拳 DM) — KOF2002UM 校准数据
  DM_TETSUZAN_KOU: {
    startup: 8,
    active: 10,
    recovery: 40,
    damage: 200,
    hitstun: 0,
    blockstun: 22,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  // ── 李香绯追加SDM (Li Xiangfei) ── KOF2002UM 校准数据
  // 超球弾·SDM qcf×2+AC (飞行道具SDM)
  SDM_CHOU_KYOKU_DAN: {
    startup: 12,
    active: 35,
    recovery: 36,
    damage: 240,
    hitstun: 0,
    blockstun: 24,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 28,
  },
  // 蛇使 qcf+P (蛇臂攻击, 突进打击) — KOF2002UM 校准数据
  YAMAZAKI_SNAKE_ARM_QCF: {
    startup: 6,
    active: 5,
    recovery: 18,
    damage: 72,
    hitstun: 14,
    blockstun: 14,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  // ドリル hcf+P hold (多段连打, 投技属性) — KOF2002UM 校准数据
  YAMAZAKI_DRILL: {
    startup: 5,
    active: 3,
    recovery: 20,
    damage: 10,
    hits: 8,
    hitstun: 14,
    blockstun: 12,
    pushback: 2,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // ── 山崎龙二命令通常技 (Yamazaki) ── KOF2002UM 校准数据
  YAMAZAKI_SASHI: {
    startup: 12,
    active: 4,
    recovery: 22,
    damage: 45,
    hitstun: 18,
    blockstun: 16,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  YAMAZAKI_BOKKAI: {
    startup: 8,
    active: 4,
    recovery: 24,
    damage: 40,
    hitstun: 16,
    blockstun: 14,
    pushback: 3,
    hitLevel: "LOW" as const,
    knockdown: false,
  },
  // ── 山崎龙二必杀技 (Yamazaki) ── KOF2002UM 校准数据
  YAMAZAKI_SNAKE_ARM: {
    startup: 7,
    active: 6,
    recovery: 20,
    damage: 65,
    hitstun: 20,
    blockstun: 16,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  YAMAZAKI_SNAKE_ARM_C: {
    startup: 10,
    active: 10,
    recovery: 26,
    damage: 88,
    hitstun: 24,
    blockstun: 20,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 12,
  },
  YAMAZAKI_SANDSTORM: {
    startup: 14,
    active: 5,
    recovery: 28,
    damage: 78,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "HIGH" as const,
    knockdown: true,
    chipDamage: 10,
  },
  YAMAZAKI_BAI_GA_SE: {
    startup: 8,
    active: 6,
    recovery: 24,
    damage: 72,
    hitstun: 20,
    blockstun: 16,
    pushback: 5,
    hitLevel: "LOW" as const,
    knockdown: true,
    chipDamage: 8,
  },
  // 砂 (当身技/Counter)
  YAMAZAKI_SUNAKE: {
    startup: 8,
    active: 10,
    recovery: 22,
    damage: 60,
    hitstun: 20,
    blockstun: 0,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
    counterOnly: true,
  },
  // 砂·强 (当身技/Counter 强版)
  YAMAZAKI_SUNAKE_C: {
    startup: 10,
    active: 12,
    recovery: 26,
    damage: 80,
    hitstun: 25,
    blockstun: 0,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    counterOnly: true,
  },
  // 蛇使·上段
  YAMAZAKI_HEBI_TSUKAI_U: {
    startup: 7,
    active: 6,
    recovery: 22,
    damage: 70,
    hitstun: 15,
    blockstun: 16,
    pushback: 5,
    hitLevel: "HIGH" as const,
    knockdown: false,
    chipDamage: 8,
  },
  // 蛇使·中段
  YAMAZAKI_HEBI_TSUKAI_M: {
    startup: 7,
    active: 6,
    recovery: 22,
    damage: 70,
    hitstun: 15,
    blockstun: 16,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  // 蛇使·下段
  YAMAZAKI_HEBI_TSUKAI_L: {
    startup: 7,
    active: 6,
    recovery: 22,
    damage: 70,
    hitstun: 15,
    blockstun: 16,
    pushback: 5,
    hitLevel: "LOW" as const,
    knockdown: false,
    chipDamage: 8,
  },
  // 逆方向 (投技)
  YAMAZAKI_GYAKUDO: {
    startup: 5,
    active: 3,
    recovery: 24,
    damage: 80,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 爆弹拳 (投技)
  YAMAZAKI_BAKUDAN_KEN: {
    startup: 4,
    active: 3,
    recovery: 28,
    damage: 85,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 蛇使い·空中 (空中蛇使, 空中可) — KOF2002UM 校准数据
  YAMAZAKI_HEBI_TSUKAI_AIR: {
    startup: 9,
    active: 6,
    recovery: 20,
    damage: 65,
    hitstun: 18,
    blockstun: 14,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  // 狂哕·弱 (突进打击) — KOF2002UM 校准数据
  YAMAZAKI_KYOUSATSU: {
    startup: 11,
    active: 8,
    recovery: 24,
    damage: 82,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  // 狂哕·強 (远距离突进) — KOF2002UM 校准数据
  YAMAZAKI_KYOUSATSU_C: {
    startup: 15,
    active: 10,
    recovery: 28,
    damage: 100,
    hitstun: 26,
    blockstun: 20,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 12,
  },
  // ── 山崎龙二DM (Yamazaki) ── KOF2002UM 校准数据
  DM_GUILLOTINE: {
    startup: 8,
    active: 14,
    recovery: 38,
    damage: 220,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 22,
  },
  // ── 山崎龙二SDM (Yamazaki) ── KOF2002UM 校准数据
  SDM_GUILLOTINE: {
    startup: 6,
    active: 20,
    recovery: 40,
    damage: 340,
    hitstun: 0,
    blockstun: 21,
    pushback: 14,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 32,
  },
  // 斩铁虫·DM (Guillotine DM)
  DM_YAMAZAKI_GUILLOTINE: {
    startup: 6,
    active: 8,
    recovery: 36,
    damage: 200,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  // 斩铁虫·SDM (Guillotine SDM)
  SDM_YAMAZAKI_GUILLOTINE: {
    startup: 5,
    active: 10,
    recovery: 38,
    damage: 260,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 30,
  },
  // ── 藤堂香澄命令通常技 (Kasumi Todoh) ── KOF2002UM 校准数据
  KASUMI_KOU_U: {
    startup: 10,
    active: 4,
    recovery: 18,
    damage: 40,
    hitstun: 16,
    blockstun: 14,
    pushback: 3,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  KASUMI_GESHIKI: {
    startup: 6,
    active: 4,
    recovery: 20,
    damage: 36,
    hitstun: 14,
    blockstun: 12,
    pushback: 2,
    hitLevel: "LOW" as const,
    knockdown: false,
  },
  // ── 藤堂香澄必杀技 (Kasumi Todoh) ── KOF2002UM 校准数据
  KASUMI_KOOU_KEN: {
    startup: 7,
    active: 6,
    recovery: 22,
    damage: 65,
    hitstun: 20,
    blockstun: 16,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  KASUMI_KOOU_KEN_C: {
    startup: 9,
    active: 8,
    recovery: 26,
    damage: 82,
    hitstun: 22,
    blockstun: 18,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 10,
  },
  KASUMI_KASANE_ATE: {
    startup: 8,
    active: 5,
    recovery: 24,
    damage: 70,
    hitstun: 20,
    blockstun: 16,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  KASUMI_MUKIGENZAN: {
    startup: 10,
    active: 6,
    recovery: 26,
    damage: 75,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "LOW" as const,
    knockdown: true,
    chipDamage: 10,
  },
  // 白山天 hcf+K (对空反击, 浮空) — KOF2002UM 校准数据
  KASUMI_HAKUSANTEN: {
    startup: 9,
    active: 6,
    recovery: 26,
    damage: 70,
    hitstun: 22,
    blockstun: 16,
    pushback: 5,
    hitLevel: "HIGH" as const,
    knockdown: true,
    chipDamage: 8,
  },
  // 藤堂流·投 hcf+P close (指令投, KD) — KOF2002UM 校准数据
  KASUMI_TODOH_NAGE: {
    startup: 6,
    active: 3,
    recovery: 26,
    damage: 80,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 崩撃 hcb+P (突进正拳, KD) — KOF2002UM 校准数据
  KASUMI_HOGEKI: {
    startup: 14,
    active: 6,
    recovery: 28,
    damage: 90,
    hitstun: 24,
    blockstun: 20,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 12,
  },
  // ── 藤堂香澄DM (Kasumi Todoh) ── KOF2002UM 校准数据
  DM_CHO_MUKIGENZAN: {
    startup: 7,
    active: 14,
    recovery: 36,
    damage: 195,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  // ── 藤堂香澄SDM (Kasumi Todoh) ── KOF2002UM 校准数据
  SDM_CHO_MUKIGENZAN: {
    startup: 5,
    active: 20,
    recovery: 38,
    damage: 300,
    hitstun: 0,
    blockstun: 21,
    pushback: 14,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 30,
  },
  // ── 藤堂香澄追加必杀技 (Kasumi Todoh) ── KOF2002UM 校准数据
  // 无二返 qcb+B (当身技)
  KASUMI_MUKOU_GAESHI: {
    startup: 3,
    active: 20,
    recovery: 18,
    damage: 40,
    hitstun: 16,
    blockstun: 0,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
    counterOnly: true,
  },
  // 无二返 qcb+D (当身技·强)
  KASUMI_MUKOU_GAESHI_C: {
    startup: 3,
    active: 25,
    recovery: 22,
    damage: 55,
    hitstun: 20,
    blockstun: 0,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    counterOnly: true,
  },
  // 殺陣陽旋 hcf+A
  KASUMI_SASSHO_IN_SHIN: {
    startup: 8,
    active: 6,
    recovery: 24,
    damage: 70,
    hitstun: 16,
    blockstun: 14,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  // 殺陣陽旋 hcf+C (强)
  KASUMI_SASSHO_IN_SHIN_C: {
    startup: 10,
    active: 8,
    recovery: 28,
    damage: 85,
    hitstun: 20,
    blockstun: 18,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  // 波及乱舞 qcf+K
  KASUMI_HAKI_RAN_MAN: {
    startup: 6,
    active: 4,
    recovery: 22,
    damage: 65,
    hitstun: 14,
    blockstun: 12,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 6,
  },
  // ── 藤堂香澄追加DM (Kasumi Todoh) ── KOF2002UM 校准数据
  // 超无二返·DM qcb×2+K (当身DM)
  DM_CHOU_MUKOU_GAESHI: {
    startup: 2,
    active: 30,
    recovery: 36,
    damage: 200,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
    counterOnly: true,
  },
  // ── 藤堂香澄追加SDM (Kasumi Todoh) ── KOF2002UM 校准数据
  // 超无二返·SDM qcb×2+BD (当身SDM)
  SDM_CHOU_MUKOU_GAESHI: {
    startup: 1,
    active: 35,
    recovery: 38,
    damage: 270,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
    counterOnly: true,
  },
  // 三連撃水 qcb+P (三连突进打击) — KOF2002UM 校准数据
  KASUMI_SANREN_GEKISUI: {
    startup: 6,
    active: 5,
    recovery: 20,
    damage: 70,
    hitstun: 14,
    blockstun: 14,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  // 白投 hcf+K (指令投, KD) — KOF2002UM 校准数据
  KASUMI_HAKUBI_NAGE: {
    startup: 5,
    active: 4,
    recovery: 28,
    damage: 100,
    hitstun: 25,
    blockstun: 0,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // DM 三神雷 qcf,qcf+K (突进打击 DM) — KOF2002UM 校准数据
  DM_SAN_SHIN_RAI: {
    startup: 8,
    active: 8,
    recovery: 38,
    damage: 200,
    hitstun: 0,
    blockstun: 22,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  // ── SDM 补全: 缺少SDM的DM角色的超必杀技强化版 ── KOF2002UM 校准
  // Kyo
  SDM_HIGH_ANGLE_GEYSER: {
    startup: 7, active: 12, recovery: 38,
    damage: 280, hitstun: 0, blockstun: 24, pushback: 12,
    hitLevel: "MID" as const, knockdown: true, chipDamage: 24,
  },
  // Athena
  SDM_GALACTIC_PHANTOM: {
    startup: 9, active: 14, recovery: 42,
    damage: 300, hitstun: 0, blockstun: 24, pushback: 12,
    hitLevel: "MID" as const, knockdown: true, chipDamage: 32,
  },
  // Joe
  SDM_BOMBER_TIGER: {
    startup: 7, active: 12, recovery: 38,
    damage: 280, hitstun: 0, blockstun: 24, pushback: 12,
    hitLevel: "MID" as const, knockdown: true, chipDamage: 24,
  },
  // Kim
  SDM_HI_EN_KYAKU: {
    startup: 7, active: 10, recovery: 36,
    damage: 270, hitstun: 0, blockstun: 23, pushback: 11,
    hitLevel: "MID" as const, knockdown: true, chipDamage: 23,
  },
  // Chang
  SDM_DAISAN_NO_KON: {
    startup: 8, active: 12, recovery: 40,
    damage: 280, hitstun: 0, blockstun: 24, pushback: 12,
    hitLevel: "MID" as const, knockdown: true, chipDamage: 24,
  },
  // Choi
  SDM_TEKKYUU_DAI_SESSA: {
    startup: 7, active: 10, recovery: 38,
    damage: 270, hitstun: 0, blockstun: 23, pushback: 11,
    hitLevel: "MID" as const, knockdown: true, chipDamage: 23,
  },
  // Yashiro
  SDM_TERRITORY_BUST: {
    startup: 8, active: 12, recovery: 40,
    damage: 280, hitstun: 0, blockstun: 24, pushback: 12,
    hitLevel: "MID" as const, knockdown: true, chipDamage: 24,
  },
  // Vice
  SDM_NEGATIVE_FLOG: {
    startup: 7, active: 12, recovery: 38,
    damage: 280, hitstun: 0, blockstun: 24, pushback: 12,
    hitLevel: "MID" as const, knockdown: true, chipDamage: 24,
  },
  // Mary
  SDM_MARY_DYNAMIC: {
    startup: 7, active: 12, recovery: 40,
    damage: 280, hitstun: 0, blockstun: 24, pushback: 12,
    hitLevel: "MID" as const, knockdown: true, chipDamage: 24,
  },
  // Xiangfei
  SDM_TETSUZAN_KOU: {
    startup: 7, active: 12, recovery: 38,
    damage: 270, hitstun: 0, blockstun: 24, pushback: 12,
    hitLevel: "MID" as const, knockdown: true, chipDamage: 24,
  },
  // Kasumi
  SDM_SAN_SHIN_RAI: {
    startup: 7, active: 10, recovery: 36,
    damage: 270, hitstun: 0, blockstun: 23, pushback: 11,
    hitLevel: "MID" as const, knockdown: true, chipDamage: 23,
  },
} as const;
