/**
 * K' + Kula + Athena + Clark + Ralf + Joe frame data
 * Split from frameDataChars.ts
 *
 * 数据源: KOF2002UM 校准数据
 */
export const KDASH_KULA_ATHENA_CLARK_RALF_JOE_DATA = {
  SDM_RYU_KO_RYU: {
    startup: 8,
    active: 12,
    recovery: 36,
    damage: 320,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 30,
  },
  SDM_HAOU_SHOKOU: {
    startup: 10,
    active: 14,
    recovery: 38,
    damage: 310,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 32,
  },
  // ── 不知火舞SDM (Mai Shiranui) ── KOF2002UM 校准数据
  SDM_HAKA_OTOSHI: {
    startup: 8,
    active: 15,
    recovery: 40,
    damage: 310,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 28,
  },
  // ── 雅典娜命令通常技 (Athena Asamiya) ──
  ATHENA_PHOENIX_REFLECT: {
    startup: 16,
    active: 4,
    recovery: 20,
    damage: 45,
    hitstun: 19,
    blockstun: 17,
    pushback: 3,
    hitLevel: "HIGH" as const,
    knockdown: false,
  },
  ATHENA_LOW_B: {
    startup: 8,
    active: 4,
    recovery: 20,
    damage: 40,
    hitstun: 18,
    blockstun: 15,
    pushback: 2,
    hitLevel: "LOW" as const,
    knockdown: false,
  },
  ATHENA_AIR_B: {
    startup: 7,
    active: 6,
    recovery: 3,
    damage: 42,
    hitstun: 19,
    blockstun: 17,
    pushback: 4,
    hitLevel: "HIGH" as const,
    knockdown: false,
  },
  // ── 雅典娜必杀技 (Athena Asamiya) ── KOF2002UM 校准数据
  ATHENA_PSYCHO_BALL: {
    startup: 12,
    active: 22,
    recovery: 32,
    damage: 70,
    hitstun: 28,
    blockstun: 26,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  ATHENA_PSYCHO_BALL_C: {
    startup: 14,
    active: 26,
    recovery: 30,
    damage: 100,
    hitstun: 30,
    blockstun: 28,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 10,
  },
  ATHENA_PSYCHO_SWORD: {
    startup: 5,
    active: 5,
    recovery: 26,
    damage: 80,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  // 精神剑·强 dp+C (对空 强版)
  ATHENA_PSYCHO_SWORD_C: {
    startup: 5,
    active: 10,
    recovery: 28,
    damage: 90,
    hitstun: 22,
    blockstun: 20,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 12,
  },
  ATHENA_PHOENIX_ARROW: {
    startup: 6,
    active: 10,
    recovery: 18,
    damage: 75,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 精神传送 qcb+A (瞬移技)
  ATHENA_PSYCHO_TELEPORT: {
    startup: 5,
    active: 1,
    recovery: 15,
    damage: 1,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // 精神传送·强 qcb+C (瞬移技, 长距离)
  ATHENA_PSYCHO_TELEPORT_C: {
    startup: 8,
    active: 1,
    recovery: 15,
    damage: 1,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // ── 雅典娜DM (Athena) ──
  DM_SHINING_CRYSTAL_BIT: {
    startup: 8,
    active: 12,
    recovery: 40,
    damage: 200,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 18,
  },
  // ── 雅典娜SDM (Athena) ──
  SDM_SHINING_CRYSTAL_BIT: {
    startup: 8,
    active: 18,
    recovery: 38,
    damage: 300,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 30,
  },
  // 凤凰箭DM (空中DM) qcf,qcf+P in air
  DM_PHOENIX_FANG_ARROW: {
    startup: 7,
    active: 12,
    recovery: 38,
    damage: 180,
    hitstun: 0,
    blockstun: 21,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 18,
  },
  // 凤凰箭SDM (空中SDM)
  SDM_PHOENIX_FANG_ARROW: {
    startup: 6,
    active: 15,
    recovery: 36,
    damage: 240,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 28,
  },
  // ── 克拉克必杀技 (Clark Still) ── KOF2002UM 校准数据
  // Super Argentine Backbreaker hcf+A (指令投)
  CLARK_ARGENTINE: {
    startup: 3,
    active: 2,
    recovery: 30,
    damage: 120,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // Super Argentine Backbreaker hcf+C (指令投 强版)
  CLARK_ARGENTINE_C: {
    startup: 4,
    active: 2,
    recovery: 34,
    damage: 150,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // Flash Elbow dp+P (追击肘)
  CLARK_FLASH_ELBOW: {
    startup: 7,
    active: 5,
    recovery: 20,
    damage: 65,
    hitstun: 20,
    blockstun: 16,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // Napalm Stretch dp+K (对空捕捉)
  CLARK_NAPALM_STRETCH: {
    startup: 6,
    active: 6,
    recovery: 28,
    damage: 95,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // Mount Tackle hcf+K (冲刺投)
  CLARK_MOUNT_TACKLE: {
    startup: 10,
    active: 8,
    recovery: 26,
    damage: 100,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // Franken Steiner close hcf+K (近身投)
  CLARK_VULCAN: {
    startup: 5,
    active: 8,
    recovery: 24,
    damage: 80,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // ── 克拉克DM/SDM (Clark) ──
  // Ultra Argentine Backbreaker DM
  DM_ARGENTINE_DM: {
    startup: 5,
    active: 4,
    recovery: 40,
    damage: 220,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  SDM_ARGENTINE_DM: {
    startup: 5,
    active: 8,
    recovery: 38,
    damage: 320,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 30,
  },
  // DM Super Argentine Backbreaker hcb,hcb+P (command grab DM)
  DM_SUPER_ARGENTINE_BACKBREAKER: {
    startup: 4,
    active: 3,
    recovery: 42,
    damage: 200,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // ── 拉尔夫必杀技 (Ralf Jones) ── KOF2002UM 校准数据
  // Vulcan Punch qcf+A (机枪拳 多段)
  RALF_VULCAN: {
    startup: 10,
    active: 14,
    recovery: 24,
    damage: 60,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  // Vulcan Punch qcf+C (机枪拳 强版)
  RALF_VULCAN_C: {
    startup: 12,
    active: 20,
    recovery: 28,
    damage: 100,
    hitstun: 26,
    blockstun: 22,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 12,
  },
  // Bareback Vulcan Punch hcf+P (指令投)
  RALF_BACKBREAKER: {
    startup: 4,
    active: 2,
    recovery: 30,
    damage: 130,
    hitstun: 0,
    blockstun: 0,
    pushback: 0,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // Gatling Attack charge b,f+P (冲刺攻击)
  RALF_GATLING: {
    startup: 12,
    active: 10,
    recovery: 26,
    damage: 90,
    hitstun: 24,
    blockstun: 20,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // Ralf Kick qcb+K (飞踢)
  RALF_KICK: {
    startup: 14,
    active: 8,
    recovery: 22,
    damage: 85,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // Galactica Phantom DM charge b,f+P
  DM_GALACTICA_PHANTOM: {
    startup: 12,
    active: 10,
    recovery: 40,
    damage: 230,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 22,
  },
  SDM_GALACTICA_PHANTOM: {
    startup: 10,
    active: 16,
    recovery: 38,
    damage: 340,
    hitstun: 0,
    blockstun: 21,
    pushback: 14,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 32,
  },
  // DM Galactic Phantom charge b,f+P (alternate name variant)
  DM_GALACTIC_PHANTOM: {
    startup: 18,
    active: 8,
    recovery: 44,
    damage: 280,
    hitstun: 0,
    blockstun: 21,
    pushback: 14,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 30,
  },
  // ── 乔·东必杀技 (Joe Higashi) ── KOF2002UM 校准数据
  // Hurricane Upper qcf+A (龙卷风飞行道具)
  JOE_HURRICANE: {
    startup: 13,
    active: 22,
    recovery: 30,
    damage: 75,
    hitstun: 28,
    blockstun: 26,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  // Hurricane Upper qcf+C (龙卷风 强版)
  JOE_HURRICANE_C: {
    startup: 15,
    active: 28,
    recovery: 28,
    damage: 110,
    hitstun: 30,
    blockstun: 28,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 10,
  },
  // Tiger Kick dp+B (上升膝击 DP)
  JOE_TIGER_KICK: {
    startup: 5,
    active: 6,
    recovery: 26,
    damage: 85,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  // Tiger Kick dp+D (上升膝击 DP 强版)
  JOE_TIGER_KICK_D: {
    startup: 6,
    active: 10,
    recovery: 30,
    damage: 135,
    hitstun: 28,
    blockstun: 22,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 14,
  },
  // 爆裂拳 qcf+P连打 (多段拳击)
  JOE_BAKURETSUKEN: {
    startup: 9,
    active: 14,
    recovery: 22,
    damage: 70,
    hitstun: 22,
    blockstun: 18,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // Slash Kick qcb+K (冲刺踢)
  JOE_OUGON_KAKATO: {
    startup: 12,
    active: 8,
    recovery: 22,
    damage: 90,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 黄金之踵 dp+K (DP-type golden heel kick)
  JOE_OUGON_NO_KAKATO: {
    startup: 7,
    active: 8,
    recovery: 26,
    damage: 90,
    hitstun: 24,
    blockstun: 20,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 12,
  },
  // 黄金之踵 ←↙↓↘→+K (黄金脚跟落地)
  JOE_SLASH_KICK: {
    startup: 10,
    active: 10,
    recovery: 24,
    damage: 80,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // 爆裂拳·强 qcf+K连打 (多段拳击 强版)
  JOE_BAKURETSUKEN_C: {
    startup: 6,
    active: 8,
    recovery: 24,
    damage: 90,
    hitstun: 20,
    blockstun: 18,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 黄金之跟 dp+K (上升踢技)
  JOE_GOLDEN_HEEL: {
    startup: 8,
    active: 6,
    recovery: 22,
    damage: 75,
    hitstun: 16,
    blockstun: 16,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // 爆裂虎·DM qcf,qcf+K
  DM_BOMBER_TIGER: {
    startup: 8,
    active: 10,
    recovery: 40,
    damage: 210,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 22,
  },
  // Screw Upper DM qcf,qcf+P
  DM_SCREW_UPPER: {
    startup: 10,
    active: 16,
    recovery: 40,
    damage: 210,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  SDM_SCREW_UPPER: {
    startup: 8,
    active: 24,
    recovery: 38,
    damage: 310,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 30,
  },
  // ── 安迪必杀技 (Andy Bogard) ── KOF2002UM 校准数据
  // 飛翔拳 qcf+A (飞行道具)
  ANDY_HISHOU_KEN: {
    startup: 13,
    active: 20,
    recovery: 30,
    damage: 70,
    hitstun: 28,
    blockstun: 26,
    pushback: 4,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  // 飛翔拳 qcf+C (飞行道具 强版)
  ANDY_HISHOU_KEN_C: {
    startup: 15,
    active: 24,
    recovery: 28,
    damage: 100,
    hitstun: 30,
    blockstun: 28,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 10,
  },
  // 昇龍弾 dp+A (DP 弱版)
  ANDY_SHOURYUU_DAN: {
    startup: 5,
    active: 6,
    recovery: 26,
    damage: 85,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 10,
  },
  // 昇龍弾 dp+C (DP 强版)
  ANDY_SHOURYUU_DAN_C: {
    startup: 7,
    active: 10,
    recovery: 30,
    damage: 140,
    hitstun: 28,
    blockstun: 22,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 14,
  },
  // 斬影拳 qcb+P (影肘突进)
  ANDY_ZANEI_RYUSEI_KEN: {
    startup: 10,
    active: 8,
    recovery: 22,
    damage: 90,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 斬影拳 qcb+K (影肘突进 强版)
  ANDY_ZANEI_RYUSEI_KEN_D: {
    startup: 12,
    active: 12,
    recovery: 26,
    damage: 115,
    hitstun: 26,
    blockstun: 20,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 空破弾 ←↙↓↘→+K (冲刺肘)
  ANDY_GEKI_HISHOU_KEN: {
    startup: 8,
    active: 8,
    recovery: 20,
    damage: 80,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 斩影拳 qcb+P (shadow elbow rush, alternate variant)
  ANDY_ZANEIKEN: {
    startup: 8,
    active: 8,
    recovery: 24,
    damage: 80,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 上顎 qcb+K (分裂踢)
  ANDY_KUHADAN: {
    startup: 12,
    active: 8,
    recovery: 22,
    damage: 85,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 不知火流·炎阵 dp+P (对空)
  ANDY_SHIRANUI_RYUU_EN_JIN: {
    startup: 6,
    active: 8,
    recovery: 24,
    damage: 80,
    hitstun: 20,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 飞燕脚·DM qcf,qcf+K
  DM_HI_EN_KYAKU: {
    startup: 6,
    active: 12,
    recovery: 38,
    damage: 200,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  // 超裂破弾 DM qcb,qcb+P
  DM_CHO_REPPA_DAN: {
    startup: 8,
    active: 14,
    recovery: 38,
    damage: 210,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  SDM_CHO_REPPA_DAN: {
    startup: 8,
    active: 22,
    recovery: 36,
    damage: 310,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 30,
  },
  // ── 比利必杀技 (Billy Kane) ── KOF2002UM 校准数据
  BILLY_SANSETSU_KON: {
    startup: 10,
    active: 8,
    recovery: 22,
    damage: 65,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  BILLY_SANSETSU_KON_C: {
    startup: 12,
    active: 12,
    recovery: 26,
    damage: 90,
    hitstun: 24,
    blockstun: 20,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  BILLY_SENPU_KON: {
    startup: 5,
    active: 6,
    recovery: 24,
    damage: 80,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  BILLY_SENPU_KON_C: {
    startup: 7,
    active: 10,
    recovery: 28,
    damage: 130,
    hitstun: 26,
    blockstun: 22,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 14,
  },
  BILLY_HIEN_ZAN: {
    startup: 10,
    active: 8,
    recovery: 20,
    damage: 75,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  BILLY_HIEN_ZAN_D: {
    startup: 12,
    active: 12,
    recovery: 24,
    damage: 100,
    hitstun: 24,
    blockstun: 20,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 超火炎旋风拳 qcb,f+P
  BILLY_CHOU_KAEN_SENPU_JIN: {
    startup: 10,
    active: 8,
    recovery: 28,
    damage: 85,
    hitstun: 20,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 12,
  },
  // 流星踢 qcf+K
  BILLY_RYUSEI_KYAKU: {
    startup: 8,
    active: 6,
    recovery: 22,
    damage: 75,
    hitstun: 16,
    blockstun: 16,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 大太极拳 qcb+P
  BILLY_DAI_TAIKYOKU_KEN: {
    startup: 8,
    active: 8,
    recovery: 24,
    damage: 85,
    hitstun: 20,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 大三之棍·DM qcf,qcf+P
  DM_DAISAN_NO_KON: {
    startup: 10,
    active: 12,
    recovery: 40,
    damage: 200,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  DM_KAEN_SENPU_JIN: {
    startup: 10,
    active: 12,
    recovery: 40,
    damage: 200,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 18,
  },
  SDM_KAEN_SENPU_JIN: {
    startup: 8,
    active: 20,
    recovery: 38,
    damage: 300,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 28,
  },
  // ── 陈可汗必杀技 (Chang Koehan) ── KOF2002UM 校准数据
  CHANG_TEKKYUU_KAITEN: {
    startup: 10,
    active: 14,
    recovery: 26,
    damage: 65,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
    chipDamage: 8,
  },
  CHANG_TEKKYUU_KAITEN_C: {
    startup: 12,
    active: 20,
    recovery: 30,
    damage: 100,
    hitstun: 26,
    blockstun: 22,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 12,
  },
  CHANG_TEKKYUU_FASSHU: {
    startup: 14,
    active: 8,
    recovery: 28,
    damage: 90,
    hitstun: 24,
    blockstun: 20,
    pushback: 7,
    hitLevel: "HIGH" as const,
    knockdown: true,
    chipDamage: 10,
  },
  CHANG_TEKKYUU_HIEN_ZAN: {
    startup: 8,
    active: 10,
    recovery: 24,
    damage: 85,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  // 铁球大回转 hcf+P (连打属性)
  CHANG_TEKKYUU_TAIGYOKU: {
    startup: 6,
    active: 20,
    recovery: 24,
    damage: 70,
    hitstun: 18,
    blockstun: 16,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // 大破坏 qcb,f+P
  CHANG_DAI_HAKKI: {
    startup: 10,
    active: 8,
    recovery: 30,
    damage: 90,
    hitstun: 22,
    blockstun: 20,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 铁球石火块 qcb+P
  CHANG_TEKKYUU_SEKIKAI: {
    startup: 6,
    active: 6,
    recovery: 22,
    damage: 80,
    hitstun: 18,
    blockstun: 16,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // 铁球大杀阵·DM qcf,qcf+P
  DM_TEKKYUU_DAI_SESSA: {
    startup: 10,
    active: 14,
    recovery: 42,
    damage: 210,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 22,
  },
  DM_TEKKYUU_DAI_BOUSOU: {
    startup: 10,
    active: 12,
    recovery: 42,
    damage: 220,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 20,
  },
  SDM_TEKKYUU_DAI_BOUSOU: {
    startup: 8,
    active: 18,
    recovery: 40,
    damage: 320,
    hitstun: 0,
    blockstun: 21,
    pushback: 14,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 32,
  },
  // ── 蔡宝奇命令通常技 (Choi Bounge) ── KOF2002UM 校准数据
  CHOI_SOUTEN_MEKKYAKU: {
    startup: 12,
    active: 5,
    recovery: 18,
    damage: 48,
    hitstun: 19,
    blockstun: 17,
    pushback: 3,
    hitLevel: "HIGH" as const,
    knockdown: false,
  },
  CHOI_SAN_REN_GEKI: {
    startup: 8,
    active: 5,
    recovery: 16,
    damage: 40,
    hitstun: 18,
    blockstun: 15,
    pushback: 2,
    hitLevel: "LOW" as const,
    knockdown: false,
  },
  // ── 蔡宝奇必杀技 (Choi Bounge) ── KOF2002UM 校准数据
  CHOI_HISHOU_KYAKU: {
    startup: 8,
    active: 8,
    recovery: 18,
    damage: 65,
    hitstun: 20,
    blockstun: 16,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  CHOI_HISHOU_KYAKU_C: {
    startup: 10,
    active: 12,
    recovery: 22,
    damage: 95,
    hitstun: 24,
    blockstun: 20,
    pushback: 7,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  CHOI_KAITEN_HIEN_ZAN: {
    startup: 5,
    active: 6,
    recovery: 22,
    damage: 75,
    hitstun: 22,
    blockstun: 18,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 8,
  },
  CHOI_KAITEN_HIEN_ZAN_C: {
    startup: 7,
    active: 10,
    recovery: 28,
    damage: 120,
    hitstun: 26,
    blockstun: 22,
    pushback: 8,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 12,
  },
  CHOI_HOUYOKU_TENSHIN: {
    startup: 6,
    active: 10,
    recovery: 24,
    damage: 90,
    hitstun: 22,
    blockstun: 18,
    pushback: 6,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 10,
  },
  // 突刺 qcf+P
  CHOI_TATAKI_KOMYAKU: {
    startup: 4,
    active: 4,
    recovery: 16,
    damage: 55,
    hitstun: 16,
    blockstun: 14,
    pushback: 3,
    hitLevel: "MID" as const,
    knockdown: false,
  },
  // 龙卷突 qcb+K
  CHOI_TATSUMAKI_SHITOTSU: {
    startup: 6,
    active: 8,
    recovery: 22,
    damage: 70,
    hitstun: 16,
    blockstun: 16,
    pushback: 5,
    hitLevel: "MID" as const,
    knockdown: true,
  },
  // ── 蔡宝奇DM/SDM (Choi) ──
  DM_SHIN_CHOU_HOUYOKU: {
    startup: 8,
    active: 12,
    recovery: 40,
    damage: 200,
    hitstun: 0,
    blockstun: 21,
    pushback: 10,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 18,
  },
  SDM_SHIN_CHOU_HOUYOKU: {
    startup: 8,
    active: 18,
    recovery: 38,
    damage: 300,
    hitstun: 0,
    blockstun: 21,
    pushback: 12,
    hitLevel: "MID" as const,
    knockdown: true,
    chipDamage: 28,
  },
} as const;
